### ISSUE TITLE
Start very slow and cannot recognize voice after power interupt

### ISSUE THREAD

**Issue by jackynguyen93** [google/aiyprojects-raspbian#118]
I used USB card sound to connect microphone and speaker (with external power supply) and it worked well. After Power outage, I started RPi again but it took a long time to start voice-recognizer. I used trigger clap to start assistant and after it recognized clap signal, it showed "recognizing ....." for forever. 
Also, my raspberry pi became very slow when I do apt-get update.

**Comment by drigz** [comment]
This sounds like it's not AIY-related. If it doesn't resolve itself (eg due to a temporary network issue), I'd suggest asking on the Raspberry Pi forums: https://www.raspberrypi.org/forums/index.php
