### ISSUE TITLE
install-deps.sh errors out when "${HOME}/.config/" doesn't exists

### ISSUE THREAD

**Issue by divx118** [google/aiyprojects-raspbian#135]
Relevant code line where it fails.
https://github.com/google/aiyprojects-raspbian/blob/master/scripts/install-deps.sh#L44

**Comment by drigz** [comment]
Which distro are you using if you don't have ~/.config?

Does `echo $XDG_CONFIG_HOME` give any output?

**Comment by divx118** [comment]
Sorry forgot to mention stretch lite raspbian, so no X.

**Comment by ensonic** [comment]
I probably won't hurt to just add a `mkdir ~/.config` to the script.

**Comment by divx118** [comment]
Yeah, just a simple `mkdir -p /${HOME}/.config` So you don't have to check if it exists.

**Comment by divx118** [comment]
Since the focus will be the voicekit branch where this is not an issue I will close this.
