### ISSUE TITLE
voicekit branch still uses hard coded home directory

### ISSUE THREAD

**Issue by mpember** [google/aiyprojects-raspbian#139]
While most of the code has been updated to support a home directory other than "/home/pi", **src/aiy/_apis/_speech.py** still uses a hard-coded path when looking for the **cloud_speech.json** file.

Is there a reason this was kept?

**Comment by mpember** [comment]
@drigz does the change intentionally remove support for the legacy file location?

**Comment by drigz** [comment]
Intentionally - that was only printed in the first run of magazines, so new users won't be using it.

If I'm wrong and people are using it, I'm happy to readd the legacy support.
