### ISSUE TITLE
Requirement for clear documentation or a proper wiki

### ISSUE THREAD

**Issue by shivasiddharth** [google/aiyprojects-raspbian#140]
Hello,
The documentation of the AIY Projects in the offical [webpage](https://aiyprojects.withgoogle.com/voice/) seems to contradict with master branch. I have been around for quite sometime so its not an issue, but for a newbie or  someone who is visiting the git for first time, it could be perplexing. 
Also if @drigz reply to #138 is mentioned in the readme or hacking.md file, it will throw more light on the existence of two separate branches for the AIY projects.
Regards

**Comment by drigz** [comment]
Could you have a look at these pull requests? #144 #145
Do they address the issue you're describing?

**Comment by shivasiddharth** [comment]
@drigz , Yes thats what i was talking about.
