### ISSUE TITLE
Configuring LED signals?

### ISSUE THREAD

**Issue by gleonard3** [google/aiyprojects-raspbian#15]
What is the syntax for modifying the configuration file in ~/voice-recognizer-raspi/config/status-led.ini.default??  I need to turn off the "device ready" blinking, before my wife stabs me.

**Comment by drigz** [comment]
Does ensonic's answer on #2 help?

**Comment by gleonard3** [comment]
Yes, it does, thanks.  Changed "ready": "beacon-dark" to "ready": "off".
Sorry for the extra noise.

George Leonard,
(408) 372-7763

**Comment by drigz** [comment]
Glad you've responded - I was terrified you'd fallen victim to mariticide. Have fun with the kit!

**Comment by LegoChicken** [comment]
I've tried modify the latest version of led.py to change "ready":
https://github.com/google/aiyprojects-raspbian/blob/master/src/led.py#L50
"ready": aiy.common.LED.LED_BEACON_DARK,
to
"ready": aiy.common.LED.LED_OFF
I then restarted the service:
sudo service voice-recognizer restart
(note: from memory so may not have got exact syntax right)
It seemed to make no difference. Any ideas what is wrong? I would really like to stop it pulsing when just sitting there.

**Comment by drigz** [comment]
You need to restart the LED service:

`sudo service status-led restart`

**Comment by LegoChicken** [comment]
Oh, I'll give that a try at home. Are there any other services associated with the project. I'll create a short script in to restart all of them.

**Comment by LegoChicken** [comment]
I can see the list in:
https://github.com/google/aiyprojects-raspbian/tree/master/systemd
Would be useful to install a script (e.g. /usr/bin) that restarts everything, so those changing the code can experiment easily. I'll raise another issue for this.

**Comment by addamm1** [comment]
Just found something in /AIY-voice-kit-python/src/aiy/_drivers. If you go into _status_ui.py, you can change what the actions do. I changed the ready one to "aiy.voicehat.LED.OFF" because i didn't like the led blinking all the time. Someone else probably found this, but just wanted to share.
