### ISSUE TITLE
Some commands no longer work after 13/10

### ISSUE THREAD

**Issue by shavanni** [google/aiyprojects-raspbian#150]
As of 13/10, some commands no longer work correctly.
Sing me a song now returns "here is information about sing me a song"
Sing a song now returns " here is a matching video"
Tell me a story now returns "here are matching news articles" 

All were working correctly on 12/10

**Comment by sheridat** [comment]
Hi, Firstly thanks for giving me some new things to ask it!.
I have just tried those three - I am running the voicekit version of the software.
The first two resulted in it singing me a song. The tell me a story resulted in the opening sentences if a Tale of Two cities. 

How strange. Does the fault replicate after a reboot?

**Comment by shavanni** [comment]
No joy I'm afraid. I'm using the gpio trigger, not ok Google but I've done nothing to change it do it seems like a server side problem.

**Comment by ensonic** [comment]
If you are using the assistant, maybe you could report this there:
https://github.com/googlesamples/assistant-sdk-python
since we merely integrated this library.

**Comment by shavanni** [comment]
I have raised it there.  Apparently it's a known issue
