### ISSUE TITLE
VoiceKit : Getting the text spoken to the Assistant - Opinion is this an acceptable way to do it?

### ISSUE THREAD

**Issue by sheridat** [google/aiyprojects-raspbian#151]
Hi,  Before changing over to the voicekit branch, I programmed my AIY to change the channel on my cable TIVO box (see the post below if your interested in doing that).

I had an actor `actor.add_keyword(_('Channel'), virgin_channel(say, 'Channel'))` and so could say for example "channel BBC1" and in my class strip out channel from the keyword and hence have BBC1 which I could do something with:

I've messed around with the assistant library with local commands demo and managed to get the text I spoke. It works but - is this an acceptable/decent way to do this? I did the following:

1. After the import statements created a global variable `mychannel = "unknow"`
2. Created a function to check whether I can obtain the text I spoke 
```
def channel():
        print(mychannel)
        aiy.audio.say(mychannel)
```
3. Altered the processes event as follows
```
elif text.startswith ('Channel'):
            global mychannel
            mychannel = text
            print (mychannel) # just for debugging
            assistant.stop_conversation()
            channel()
```

[https://www.raspberrypi.org/forums/viewtopic.php?f=114&t=194351]

**Comment by drigz** [comment]
This question is more appropriate for the RPi forums - from our point of view you use the API however you like.
