### ISSUE TITLE
Led doesn't light on

### ISSUE THREAD

**Issue by Premier** [google/aiyprojects-raspbian#152]
As in subject, the led doesn't light on nor blink. I've followed the documentation and switched 180° the led, also, but it doesn't flash.

**Comment by drigz** [comment]
Are you running one of the demos, such as `assistant_library_demo.py`? In the new version of the image, the LED doesn't light until you run one of the scripts.

If you are running one of the scripts, this is a hardware issue (GitHub is for software issues) - you can try posting in the [RPi forums](https://www.raspberrypi.org/forums/viewforum.php?f=114) to ask for help with the assembly, or contacting the retailer if you think the kit is faulty.

Hope this helps!
