### ISSUE TITLE
BrokenPipeError

### ISSUE THREAD

**Issue by Pixel06** [google/aiyprojects-raspbian#153]
Hi, I tried to configure my raspberry pi 3 (with the standard version of raspbian) for the voice kit with _HACKING.md_. The led works but when I run _chek_audio.py_ it returns an error: "BrokenPipeError: [Errno32] Broken pipe". Can you help me, please? Thanks.

**Comment by t1m0thyj** [comment]
Have you tried the troubleshooting steps listed [here](https://developers.google.com/assistant/sdk/develop/python/hardware/audio), particularly 2 and 3? It sounds like your Pi is trying to use the wrong playback/recording device.

**Comment by Pixel06** [comment]
No, I'm going to try it, thanks

**Comment by drigz** [comment]
Good suggestion, @t1m0thyj. @Pixel06, did you try the troubleshooting steps out?

**Comment by dmitriykovalev** [comment]
Please reopen if problem still exists.
