### ISSUE TITLE
Timers and reminders go on forever?

### ISSUE THREAD

**Issue by joeynuggetz** [google/aiyprojects-raspbian#174]
How do you stop a timer? The AIY plays a tone over and over.

**Comment by t1m0thyj** [comment]
Saying "OK Google, stop" should do it.

**Comment by joeynuggetz** [comment]
Perhaps the biotch couldn't hear me above all the noise. How do I lower the volume on the speaker? Can't seem to find a way to do it via voice.

**Comment by LondonSi72** [comment]
Say 'Ok Google, lower volume 10%' a few times does the trick. I tried saying 'set volume 50%' but that doesn't seem to work...

**Comment by drigz** [comment]
@joeynuggetz, please mind your language on this project.

Thanks for responding, @t1m0thyj and @LondonSi72. Reducing the volume is what we'd recommend.
