### ISSUE TITLE
How about an image update?

### ISSUE THREAD

**Issue by sheridat** [google/aiyprojects-raspbian#179]
Hi,  the current image is aiyprojects-2017-09-11.img.xz

That image is missing a few things such as:
1. The assistant_library_with_local_commands_demo.py (which is ultra useful to all newbies)
2. The buzzer driver.

Any chance of updating the image?

**Comment by ngineerken** [comment]
Also consider moving to the Stretch (Debian 9) as the latest Raspberry Pi is at.

**Comment by sheridat** [comment]
I'm closing based upon the new combined image for aiyprojects resolves the above.
