### ISSUE TITLE
Cannot erase shopping list

### ISSUE THREAD

**Issue by MarsNL** [google/aiyprojects-raspbian#180]
Hi, I added items to the shopping list but
cannot remove them as the AIY needs to have
an connection with the Google Home app.
Is there any way to clear it?

**Comment by drigz** [comment]
Not as far as I'm aware, see #6.

You could try [the support forums](https://github.com/google/aiyprojects-raspbian/blob/voicekit/README.md#support) to see if there are known workarounds.

**Comment by sheridat** [comment]
Hi, go to [](https://express.google.com/  ) and sign in (if your not using chrome and aren't signed in).
On the left hand side menu you will see "list" -click on it
You can then delete whichever items you want.

**Comment by MarsNL** [comment]
Thanks :))

**Comment by drigz** [comment]
Good suggestion, @sheridat.

Closing as a duplicate of #6.

**Comment by dmitriykovalev** [comment]
Duplicate of #6
