### ISSUE TITLE
Enable multiple users (Voice Match) like google home

### ISSUE THREAD

**Issue by janvda** [google/aiyprojects-raspbian#192]
It would be interesting if it would be possible to enable multiple user (voice match) like google home.
See https://support.google.com/googlehome/answer/7323910?hl=en

**Comment by drigz** [comment]
We can only do what the Assistant SDK provides here. If you're interested, you could [file an issue upstream](https://github.com/googlesamples/assistant-sdk-python/issues).

**Comment by janvda** [comment]
Thanks for the response.  I have filed an issue upstream = https://github.com/googlesamples/assistant-sdk-python/issues/135
so you can close this issue.
kr
Jan.
