### ISSUE TITLE
Triggering doesn't work in the button demo

### ISSUE THREAD

**Issue by drigz** [google/aiyprojects-raspbian#204]
Reported at https://github.com/google/aiyprojects-raspbian/issues/202#issuecomment-353341576 by @thomwiggers.

In the hotword-and-button demo, the button doesn't trigger the assistant to listen anymore. I haven't had much time to test it but my suspicions were that either `Assistant.start_conversation()` doesn't work, or that perhaps there is some issue with the threading.

**Comment by divx118** [comment]
Is there a hotword and button demo? IMO there is only hotword **or** button demo. I combined the 2 demos for my own use which works. Or did I miss a pull request...

**Comment by thomwiggers** [comment]
See https://github.com/google/aiyprojects-raspbian/blob/voicekit/src/assistant_library_with_button_demo.py

**Comment by divx118** [comment]
@thomwiggers Yeah sorry, my mistake.

**Comment by drigz** [comment]
I'm not seeing this any more. If anyone else sees it, please comment and I'll reopen it.
