### ISSUE TITLE
Is there new image for raspberry pi zero w?

### ISSUE THREAD

**Issue by idealist33** [google/aiyprojects-raspbian#208]
I have an old image name of "aiyprojects-2017-05-03.img" and it works fine when using google assistant.
However as it is an an old image, there is no google cloud speech example.

I cloned github of here and followed HACKING.md but it was not perfect for raspberry pi zero w. 
Many python errors come out...this github might not be targeted for rpi zero w.

Is there any new image which contains same examples of latest github for raspberry pi zero w ?

**Comment by PeterMalkin** [comment]
Yes, you can get it here:
https://dl.google.com/dl/aiyprojects/vision/aiyprojects-2017-12-18.img.xz

**Comment by idealist33** [comment]
Thanks, but is this image for raspberry pi 3 b only? it does not work perfectly with my pi zero w.

**Comment by PeterMalkin** [comment]
I have tested it on Raspberri pi 0 W

**Comment by sheridat** [comment]
@idealist33  Your not being specific in saying what is not working for you. Anything to do with activating the assistant by saying "OK Google" or "Hey Google" does not work on the W

**Comment by idealist33** [comment]
@sheridat Thanks a lot. Hotword and some python libraries havn't been loaded when executing python scripts. I will try the lated aiy image.

**Comment by jjfretired** [comment]
Download and installed aiyprojects 2017-12-18.img.xz.  Using the instructions for HACKING.md to install the dependencies It failed to clone https://github.com/google/aiyprojects-raspbian.git voice-recognizer-raspi.  After logging into github it failed with Repository not found"

**Comment by drigz** [comment]
@idealist33 Hotwording doesn't work with the Pi 0 at the moment, as there are performance problems with the less powerful processor. Check out the [compatibility table](https://aiyprojects.withgoogle.com/voice/#users-guide-3-using-your-device).
