### ISSUE TITLE
grpc Demo not working

### ISSUE THREAD

**Issue by endamaco** [google/aiyprojects-raspbian#216]
Hi,
trying the grpc demo when pushing the arcade button I get this error:

`Press the button and speak
[2017-12-30 15:25:07,757] INFO:recorder:started recording
Listening...
Traceback (most recent call last):
  File "src/assistant_grpc_demo.py", line 54, in <module>
    main()
  File "src/assistant_grpc_demo.py", line 42, in main
    text, audio = assistant.recognize()
  File "/home/pi/voice-recognizer-raspi/src/aiy/assistant/grpc.py", line 49, in recognize
    response = self._request.do_request()
  File "/home/pi/voice-recognizer-raspi/src/aiy/_apis/_speech.py", line 258, in do_request
    service = self._make_service(self._channel_factory.make_channel())
  File "/home/pi/voice-recognizer-raspi/src/aiy/_apis/_speech.py", line 370, in _make_service
    return embedded_assistant_pb2.EmbeddedAssistantStub(channel)
AttributeError: module 'google.assistant.embedded.v1alpha1.embedded_assistant_pb2' has no attribute 'EmbeddedAssistantStub'
Segmentation fault
`
These are my packages:

google-assistant-grpc==0.1.0
google-assistant-library==0.1.0
google-assistant-sdk==0.4.1

**Comment by drigz** [comment]
What version of the Raspberry Pi do you have? Which image file did you flash? (eg aiyprojects-2017-09-11.img.xz)

**Comment by endamaco** [comment]
It's the raspberry 3 and I'm using the source code from this GitHub.. downloaded 1 week ago

**Comment by drigz** [comment]
We don't support google-assistant-library==0.1.0 yet - see #207.

If you install the dependencies with env/bin/pip install -r requirements.txt you should get the correct versions.

**Comment by drigz** [comment]
One correction: `env/bin/pip install -r requirements.txt` won't install `google-assistant-library` - you can use `./scripts/install-deps.sh` to install all dependencies.

I'm going to close this - please reopen if it still doesn't work if you follow the instructions in https://github.com/google/aiyprojects-raspbian/blob/aiyprojects/HACKING.md.
