### ISSUE TITLE
[FEATURE] Change Speak Language from source code?

### ISSUE THREAD

**Issue by amolinachile** [google/aiyprojects-raspbian#219]
im test this project, and works fine, my project its about Autonomous Robot for my Doguhter, and add google voicer feature, its for simple orders(start, back, left, right, etc), but for conversation in spanish
like this "Ok google, tell me a joke", and works, but in Spanish "Ok google, Dime una broma"
wont works, for now, im onlye change languaje for local tts

Google Assistant Support more languages(Spanish Mexico, Spanish Chile, etc)
But im beginer with the api
¿some function, method, argument to set language in assistant_library_with_local_commands_demo.py?

**Comment by drigz** [comment]
This is not possible with the google-assistant-library at the moment - follow https://github.com/googlesamples/assistant-sdk-python/issues/150 for progress.

For the Cloud Speech API (and soon for google-assistant-grpc, once we've upgraded to v1alpha2) you can use: `aiy.i18n.set_language_code('es-ES')`
