### ISSUE TITLE
Does Google Voice Kit supports Pi 1 B+?

### ISSUE THREAD

**Issue by gengivan** [google/aiyprojects-raspbian#221]
Hi,

I have an old Pi 1 B+, does aiyproject supports? Or is there any other customized project supports?

Thanks,
Ivan

**Comment by aallan** [comment]
As far as I know, no. Neither of the AIYProjects kits support the original Pi 1.

**Comment by t1m0thyj** [comment]
No, but there is this project: https://github.com/warchildmd/google-assistant-hotword-raspi

It makes hotword activation work with Google Assistant for the Pi 1 and Zero.

**Comment by drigz** [comment]
Yep, it's not officially supported. You can see supported devices on [the website](https://aiyprojects.withgoogle.com/voice/#users-guide-3-using-your-device).
