### ISSUE TITLE
How do you auto start assistant with actual kit?

### ISSUE THREAD

**Issue by Consoli0** [google/aiyprojects-raspbian#222]
I didnt find a way to autostart the assistant that workes.

**Comment by t1m0thyj** [comment]
The "Running automatically" section of HACKING.md<https://github.com/google/aiyprojects-raspbian/blob/aiyprojects/HACKING.md> explains how to do this. If you don't have a folder in /home/pi called "AIY-projects-python", substitute "voice-recognizer-raspi" instead.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by drigz** [comment]
@Consoli0, did you have any troubles following the instructions in HACKING.md?
