### ISSUE TITLE
Vision Bonnet Camera not working

### ISSUE THREAD

**Issue by annoscholten** [google/aiyprojects-raspbian#224]
Running on a Pi 0 W V1.1, but the camera won't connect.

The camera works when I connect it directly to the Pi 0 W, it works fine:

[   23.968383] googlevisionbonnet spi0.0: Initializing
[   24.424624] googlevisionbonnet spi0.0: Resetting myriad on probe
[   24.424641] googlevisionbonnet spi0.0: Resetting myriad
[   28.343088] googlevisionbonnet spi0.0: Writing myriad firmware
[   34.492645] googlevisionbonnet spi0.0: Myriad booting
[   34.712593] googlevisionbonnet spi0.0: Myriad ready

(env) pi@raspberrypi:~ $
~/AIY-projects-python/src/examples/vision/joy/joy_detection_demo.py
Starting JoyDetector...
ERROR:root:Camera is not running.
ERROR:root:CameraInference: Camera inference is not running.
ERROR:root:StopCameraInference: Camera inference is not running.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/pi/AIY-projects-python/src/examples/vision/joy/joy_detection_demo.py",
line 127, in _run_detector
    faces = face_detection.get_faces(result)
  File "/home/pi/AIY-projects-python/src/aiy/vision/models/face_detection.py",
line 63, in get_faces
    assert len(result.tensors) == 3
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/AIY-projects-python/src/examples/vision/joy/joy_detection_demo.py",
line 138, in _run_detector
    break
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 758,
in __exit__
    self.close()
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 752, in close
    raise exc
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 1995,
in _control_callback
    "No data recevied from sensor. Check all connections, "
picamera.exc.PiCameraRuntimeError: No data recevied from sensor. Check
all connections, including the SUNNY chip on the camera board

Are there any diagnostics I can run?

**Comment by dmitriykovalev** [comment]
Joy Demo service starts automatically when Pi boots. It should be already working in you case, could you check with `sudo systemctl status joy_detection_demo.service`?

In order to run other examples you probably need to stop and disable this service:
```
sudo systemctl stop joy_detection_demo.service
sudo systemctl disable joy_detection_demo.service
```

**Comment by annoscholten** [comment]
Hi Dimitri,

Thanks for the followup.  The service is not running because the 'Camera is not running' per: sudo systemctl status joy_detection_demo.service and my error log above.

When I connect the camera directly into the Pi 0 W (without the Vision Bonnet), the camera works ok.

When I connect the camera to the Vision Bonnet, I get 'Camera is not running'...

**Comment by dmitriykovalev** [comment]
According to your log, you are trying to manually run `~/AIY-projects-python/src/examples/vision/joy/joy_detection_demo.py` command. That wouldn't work because `joy_detection_demo.service` should be already running and using the camera (it cannot be shared between processes). 

Can you please reboot the Pi and right after that run `sudo systemctl status joy_detection_demo.service` and copy the output here?

In addition, it would be very helpful if you run `dmesg` and copy output as well.

**Comment by annoscholten** [comment]
Hi Dimitri,

See below:
● joy_detection_demo.service - AIY Joy Detection Demo
   Loaded: loaded (/lib/systemd/system/joy_detection_demo.service;
enabled; vendor preset: enabled)
   Active: active (running) since Tue 2018-01-02 12:36:13 CST; 52min ago
Main PID: 253 (python)
   CGroup: /system.slice/joy_detection_demo.service
           └─253 /home/pi/AIY-projects-python/env/bin/python
/home/pi/AIY-projects-python/src/examples/vision/

Jan 02 12:36:13 raspberrypi systemd[1]: Started AIY Joy Detection Demo.
Jan 02 13:24:43 raspberrypi python[253]: ERROR:root:Camera is not running.
Jan 02 13:24:43 raspberrypi python[253]: ERROR:root:CameraInference:
Camera inference is not running.
Jan 02 13:24:43 raspberrypi python[253]:
ERROR:root:StopCameraInference: Camera inference is not running.



dmesg:

pi@raspberrypi:~ $ dmesg
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 4.9.59+ (dc4@dc4-XPS13-9333) (gcc version
4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611) ) #1047 Sun Oct
29 11:47:10 GMT 2017
[    0.000000] CPU: ARMv6-compatible processor [410fb767] revision 7
(ARMv7), cr=00c5387d
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT
nonaliasing instruction cache
[    0.000000] OF: fdt:Machine model: Raspberry Pi Zero W Rev 1.1
[    0.000000] cma: Reserved 8 MiB at 0x17400000
[    0.000000] Memory policy: Data cache writeback
[    0.000000] On node 0 totalpages: 98304
[    0.000000] free_area_init_node: node 0, pgdat c0914e10,
node_mem_map d7c8b900
[    0.000000]   Normal zone: 864 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 98304 pages, LIFO batch:31
[    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
[    0.000000] pcpu-alloc: [0] 0
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.
Total pages: 97440
[    0.000000] Kernel command line: 8250.nr_uarts=0
bcm2708_fb.fbwidth=1600 bcm2708_fb.fbheight=1200 bcm2708_fb.fbswap=1
smsc95xx.macaddr=B8:27:EB:1B:63:4A vc_mem.mem_base=0x1ec00000
vc_mem.mem_size=0x20000000  dwc_otg.lpm_enable=0 console=ttyS0,115200
console=tty1 root=PARTUUID=fb718213-02 rootfstype=ext4
elevator=deadline fsck.repair=yes rootwait quiet splash
plymouth.ignore-serial-consoles
[    0.000000] PID hash table entries: 2048 (order: 1, 8192 bytes)
[    0.000000] Dentry cache hash table entries: 65536 (order: 6, 262144 bytes)
[    0.000000] Inode-cache hash table entries: 32768 (order: 5, 131072 bytes)
[    0.000000] Memory: 370980K/393216K available (5950K kernel code,
491K rwdata, 1948K rodata, 396K init, 725K bss, 14044K reserved, 8192K
cma-reserved)
[    0.000000] Virtual kernel memory layout:
                   vector  : 0xffff0000 - 0xffff1000   (   4 kB)
                   fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
                   vmalloc : 0xd8800000 - 0xff800000   ( 624 MB)
                   lowmem  : 0xc0000000 - 0xd8000000   ( 384 MB)
                   modules : 0xbf000000 - 0xc0000000   (  16 MB)
                     .text : 0xc0008000 - 0xc05d7a48   (5951 kB)
                     .init : 0xc0841000 - 0xc08a4000   ( 396 kB)
                     .data : 0xc08a4000 - 0xc091ef48   ( 492 kB)
                      .bss : 0xc091ef48 - 0xc09d4648   ( 726 kB)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS:16 nr_irqs:16 16
[    0.000031] sched_clock: 32 bits at 1000kHz, resolution 1000ns,
wraps every 2147483647500ns
[    0.000063] clocksource: timer: mask: 0xffffffff max_cycles:
0xffffffff, max_idle_ns: 1911260446275 ns
[    0.000154] bcm2835: system timer (irq = 27)
[    0.000629] Console: colour dummy device 80x30
[    0.000654] console [tty1] enabled
[    0.000678] Calibrating delay loop... 697.95 BogoMIPS (lpj=3489792)
[    0.060311] pid_max: default: 32768 minimum: 301
[    0.060739] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.060756] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.062004] Disabling memory control group subsystem
[    0.062140] CPU: Testing write buffer coherency: ok
[    0.062196] ftrace: allocating 21715 entries in 64 pages
[    0.180437] Setting up static identity map for 0x8200 - 0x8238
[    0.182413] devtmpfs: initialized
[    0.192708] VFP support v0.3: implementor 41 architecture 1 part 20
variant b rev 5
[    0.193130] clocksource: jiffies: mask: 0xffffffff max_cycles:
0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.193158] futex hash table entries: 256 (order: -1, 3072 bytes)
[    0.194439] pinctrl core: initialized pinctrl subsystem
[    0.195871] NET: Registered protocol family 16
[    0.198415] DMA: preallocated 1024 KiB pool for atomic coherent allocations
[    0.208104] hw-breakpoint: found 6 breakpoint and 1 watchpoint registers.
[    0.208120] hw-breakpoint: maximum watchpoint size is 4 bytes.
[    0.208221] Serial: AMBA PL011 UART driver
[    0.211141] bcm2835-mbox 2000b880.mailbox: mailbox enabled
[    0.211872] uart-pl011 20201000.serial: could not find pctldev for
node /soc/gpio@7e200000/uart0_pins, deferring probe
[    0.262820] bcm2835-dma 20007000.dma: DMA legacy API manager at
d880d000, dmachans=0x1
[    0.265490] SCSI subsystem initialized
[    0.265735] usbcore: registered new interface driver usbfs
[    0.265847] usbcore: registered new interface driver hub
[    0.266042] usbcore: registered new device driver usb
[    0.270479] raspberrypi-firmware soc:firmware: Attached to firmware
from 2017-08-08 12:05
[    0.272497] clocksource: Switched to clocksource timer
[    0.326634] VFS: Disk quotas dquot_6.6.0
[    0.326755] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    0.327082] FS-Cache: Loaded
[    0.327425] CacheFiles: Loaded
[    0.346848] NET: Registered protocol family 2
[    0.348219] TCP established hash table entries: 4096 (order: 2, 16384 bytes)
[    0.348309] TCP bind hash table entries: 4096 (order: 2, 16384 bytes)
[    0.348403] TCP: Hash tables configured (established 4096 bind 4096)
[    0.348502] UDP hash table entries: 256 (order: 0, 4096 bytes)
[    0.348529] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    0.348825] NET: Registered protocol family 1
[    0.349570] RPC: Registered named UNIX socket transport module.
[    0.349582] RPC: Registered udp transport module.
[    0.349587] RPC: Registered tcp transport module.
[    0.349591] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.350857] hw perfevents: enabled with armv6_1176 PMU driver, 3
counters available
[    0.353425] workingset: timestamp_bits=14 max_order=17 bucket_order=3
[    0.374168] FS-Cache: Netfs 'nfs' registered for caching
[    0.375938] NFS: Registering the id_resolver key type
[    0.375985] Key type id_resolver registered
[    0.375991] Key type id_legacy registered
[    0.380459] Block layer SCSI generic (bsg) driver version 0.4
loaded (major 251)
[    0.380822] io scheduler noop registered
[    0.380835] io scheduler deadline registered (default)
[    0.381308] io scheduler cfq registered
[    0.387261] BCM2708FB: allocated DMA memory 57500000
[    0.387324] BCM2708FB: allocated DMA channel 0 @ d880d000
[    0.435539] Console: switching to colour frame buffer device 200x75
[    0.475488] bcm2835-rng 20104000.rng: hwrng registered
[    0.475691] vc-mem: phys_addr:0x00000000 mem_base=0x1ec00000
mem_size:0x20000000(512 MiB)
[    0.476793] vc-sm: Videocore shared memory driver
[    0.504602] brd: module loaded
[    0.518483] loop: module loaded
[    0.518504] Loading iSCSI transport class v2.0-870.
[    0.519434] usbcore: registered new interface driver smsc95xx
[    0.519469] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    0.519677] dwc_otg: FIQ enabled
[    0.519686] dwc_otg: NAK holdoff enabled
[    0.519691] dwc_otg: FIQ split-transaction FSM enabled
[    0.519712] Module dwc_common_port init
[    0.520189] usbcore: registered new interface driver usb-storage
[    0.520716] mousedev: PS/2 mouse device common for all mice
[    0.522634] bcm2835-wdt 20100000.watchdog: Broadcom BCM2835 watchdog timer
[    0.523275] bcm2835-cpufreq: min=700000 max=1000000
[    0.523994] sdhci: Secure Digital Host Controller Interface driver
[    0.524006] sdhci: Copyright(c) Pierre Ossman
[    0.524582] sdhost-bcm2835 20202000.sdhost: could not get clk,
deferring probe
[    0.527110] mmc-bcm2835 20300000.mmc: could not get clk, deferring probe
[    0.527297] sdhci-pltfm: SDHCI platform and OF driver helper
[    0.527904] ledtrig-cpu: registered to indicate activity on CPUs
[    0.528090] hidraw: raw HID events driver (C) Jiri Kosina
[    0.528388] usbcore: registered new interface driver usbhid
[    0.528396] usbhid: USB HID core driver
[    0.529770] vchiq: vchiq_init_state: slot_zero = 0xd7580000, is_master = 0
[    0.531918] [vc_sm_connected_init]: start
[    0.542949] [vc_sm_connected_init]: end - returning 0
[    0.543515] Initializing XFRM netlink socket
[    0.543563] NET: Registered protocol family 17
[    0.543765] Key type dns_resolver registered
[    0.545891] registered taskstats version 1
[    0.555656] uart-pl011 20201000.serial: cts_event_workaround enabled
[    0.555803] 20201000.serial: ttyAMA0 at MMIO 0x20201000 (irq = 81,
base_baud = 0) is a PL011 rev2
[    0.558581] sdhost: log_buf @ d7510000 (57510000)
[    0.632602] mmc0: sdhost-bcm2835 loaded - DMA enabled (>1)
[    0.635238] mmc-bcm2835 20300000.mmc: mmc_debug:0 mmc_debug2:0
[    0.635252] mmc-bcm2835 20300000.mmc: DMA channel allocated
[    0.671957] random: fast init done
[    0.712763] of_cfs_init
[    0.713043] of_cfs_init: OK
[    0.714030] Waiting for root device PARTUUID=fb718213-02...
[    0.730771] mmc1: queuing unknown CIS tuple 0x80 (2 bytes)
[    0.732481] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    0.734488] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    0.737595] mmc1: queuing unknown CIS tuple 0x80 (7 bytes)
[    0.775469] mmc0: host does not support reading read-only switch,
assuming write-enable
[    0.778831] mmc0: new high speed SDHC card at address aaaa
[    0.780194] mmcblk0: mmc0:aaaa SS08G 7.40 GiB
[    0.784199]  mmcblk0: p1 p2
[    0.848851] mmc1: new high speed SDIO card at address 0001
[    0.851069] EXT4-fs (mmcblk0p2): mounted filesystem with ordered
data mode. Opts: (null)
[    0.851176] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
[    0.852329] devtmpfs: mounted
[    0.853829] Freeing unused kernel memory: 396K
[    0.853839] This architecture does not have kernel memory protection.
[    1.347554] systemd[1]: System time before build time, advancing clock.
[    1.511607] NET: Registered protocol family 10
[    1.530515] ip_tables: (C) 2000-2006 Netfilter Core Team
[    1.587156] systemd[1]: systemd 232 running in system mode. (+PAM
+AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP
+GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
[    1.588311] systemd[1]: Detected architecture arm.
[    1.593157] systemd[1]: Set hostname to <raspberrypi>.
[    2.798287] systemd[1]: Set up automount Arbitrary Executable File
Formats File System Automount Point.
[    2.799509] systemd[1]: Listening on udev Kernel Socket.
[    2.800347] systemd[1]: Listening on Syslog Socket.
[    2.802243] systemd[1]: Created slice System Slice.
[    2.804371] systemd[1]: Created slice system-autologin.slice.
[    2.812969] systemd[1]: Mounting Debug File System...
[    2.815127] systemd[1]: Created slice User and Session Slice.
[    3.931072] 20980000.usb supply vusb_d not found, using dummy regulator
[    3.931254] 20980000.usb supply vusb_a not found, using dummy regulator
[    4.392751] dwc2 20980000.usb: EPs: 8, dedicated fifos, 4080 entries in SPRAM
[    4.393788] dwc2 20980000.usb: DWC OTG Controller
[    4.393874] dwc2 20980000.usb: new USB bus registered, assigned bus number 1
[    4.393961] dwc2 20980000.usb: irq 33, io mem 0x00000000
[    4.394446] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[    4.394467] usb usb1: New USB device strings: Mfr=3, Product=2,
SerialNumber=1
[    4.394479] usb usb1: Product: DWC OTG Controller
[    4.394490] usb usb1: Manufacturer: Linux 4.9.59+ dwc2_hsotg
[    4.394499] usb usb1: SerialNumber: 20980000.usb
[    4.395964] hub 1-0:1.0: USB hub found
[    4.396081] hub 1-0:1.0: 1 port detected
[    4.456114] i2c /dev entries driver
[    4.492920] pwm_soft: loading out-of-tree module taints kernel.
[    4.494149] SoftPWM v0.1 initializing.
[    4.494165] Clock resolution is 1ns
[    4.494284] SoftPWM initialized.
[    4.822682] usb 1-1: new low-speed USB device number 2 using dwc2
[    5.067035] usb 1-1: New USB device found, idVendor=0461, idProduct=4d15
[    5.067067] usb 1-1: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[    5.067079] usb 1-1: Product: USB Optical Mouse
[    5.100724] input: USB Optical Mouse as
/devices/platform/soc/20980000.usb/usb1/1-1/1-1:1.0/0003:0461:4D15.0001/input/input0
[    5.101686] hid-generic 0003:0461:4D15.0001: input,hidraw0: USB HID
v1.11 Mouse [USB Optical Mouse] on usb-20980000.usb-1/input0
[   41.888459] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[   42.283903] systemd-journald[99]: Received request to flush runtime
journal from PID 1
[   44.402891] gpiomem-bcm2835 20200000.gpiomem: Initialised:
Registers at 0x20200000
[   45.563027] brcmfmac: F1 signature read @0x18000000=0x1541a9a6
[   45.587591] usbcore: registered new interface driver brcmfmac
[   45.925467] brcmfmac: Firmware version = wl0: Aug  7 2017 00:46:29
version 7.45.41.46 (r666254 CY) FWID 01-f8a78378
[   45.926949] brcmfmac: brcmf_c_preinit_dcmds: CLM version = API:
12.2 Data: 7.11.15 Compiler: 1.24.2 ClmImport: 1.24.1 Creation:
2014-05-26 10:53:55 Inc Data: 9.10.41 Inc Compiler: 1.29.4 Inc
ClmImport: 1.36.3 Creation: 2017-08-07 00:37:47
[   51.121920] random: crng init done
[   51.875152] uart-pl011 20201000.serial: no DMA platform data
[   52.477906] using random self ethernet address
[   52.477928] using random host ethernet address
[   53.857518] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   53.857545] brcmfmac: power management disabled
[   56.347228] Adding 102396k swap on /var/swap.  Priority:-1
extents:1 across:102396k SSFS
[   56.582575] Bluetooth: Core ver 2.22
[   56.622959] NET: Registered protocol family 31
[   56.622976] Bluetooth: HCI device and connection manager initialized
[   56.623001] Bluetooth: HCI socket layer initialized
[   56.623016] Bluetooth: L2CAP socket layer initialized
[   56.623065] Bluetooth: SCO socket layer initialized
[   56.675644] Bluetooth: HCI UART driver ver 2.3
[   56.675663] Bluetooth: HCI UART protocol H4 registered
[   56.675668] Bluetooth: HCI UART protocol Three-wire (H5) registered
[   56.675858] Bluetooth: HCI UART protocol Broadcom registered
[   56.703239] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[   57.963957] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   57.963973] Bluetooth: BNEP filters: protocol multicast
[   57.963996] Bluetooth: BNEP socket layer initialized
[   58.151698] usb0: HOST MAC 3a:c5:e8:9a:99:83
[   58.161521] usb0: MAC c6:50:5c:42:73:58
[   58.161769] dwc2 20980000.usb: bound driver configfs-gadget
[   58.246567] Bluetooth: RFCOMM TTY layer initialized
[   58.246607] Bluetooth: RFCOMM socket layer initialized
[   58.246643] Bluetooth: RFCOMM ver 1.11
[   58.261463] aiy-io-i2c 1-0051: AIYIO Status:OK-V0.1
[   58.595639] googlevisionbonnet spi0.0: Initializing
[   59.029684] googlevisionbonnet spi0.0: Resetting myriad on probe
[   59.029702] googlevisionbonnet spi0.0: Resetting myriad
[   59.123795] IPv6: ADDRCONF(NETDEV_UP): usb0: link is not ready
[   60.406799] ktd202x 1-0030: ktd202x driver loaded for a ktd2026.
[   63.073094] googlevisionbonnet spi0.0: Writing myriad firmware
[   65.117154] systemd[1]: Found device /dev/ttyGS0.
[   65.265198] systemd[1]: apt-daily-upgrade.timer: Adding 56min
36.194911s random time.
[   65.266046] systemd[1]: apt-daily.timer: Adding 5h 2min 6.814011s
random time.
[   69.112722] googlevisionbonnet spi0.0: Myriad booting
[   69.304790] googlevisionbonnet spi0.0: Myriad ready
[   82.342686] fuse init (API version 7.26)
[  103.850121] Registered device pwm22
[  103.885585] Starting timer (pulse).
[  103.885704] Stopping timer.
[  103.885864] Starting timer (period).
[  104.053746] Starting timer (pulse).
[  104.054327] Starting timer (period).
[  104.222224] Starting timer (pulse).
[  104.224838] Starting timer (period).
[  104.394414] Stopping timer.
[  104.401353] Unregistered device pwm22
[  309.562456] Bluetooth: HIDP (Human Interface Emulation) ver 1.2
[  309.562515] Bluetooth: HIDP socket layer initialized
[  309.632569] hid-generic 0005:045E:0705.0002: unknown main item tag 0x0
[  309.634034] input: Microsoft Wireless Entertainment Keyboard 7000
as /devices/platform/soc/20201000.serial/tty/ttyAMA0/hci0/hci0:11/0005:045E:0705.0002/input/input1
[  309.647262] hid-generic 0005:045E:0705.0002: input,hidraw1:
BLUETOOTH HID v1.0c Keyboard [Microsoft Wireless Entertainment
Keyboard 7000] on b8:27:eb:b1:c9:e0

**Comment by annoscholten** [comment]
Dimitri - that was right after a reboot and no other manual commands.

Anno

**Comment by dmitriykovalev** [comment]
Perfect, thank you! Looks like you connected camera cables in a wrong way. Most likely this is the cable between Pi and Vision Bonnet. You should be able to see contact pads from both sides (if look from top and from the bottom to the whole assembly). Can you please attach a photograph?

Just in case, please also verify connection between Vision Bonnet and Camera. In this case you shouldn't see contact pads from the top (it's opposite to the short cable between Vision Bonnet and Pi).

**Comment by annoscholten** [comment]
Hi Dimitri,

I believe I have them correct (per your notes above), but please see attached photos.
Anno
![img_0044](https://user-images.githubusercontent.com/6282596/34498210-3b883800-efc6-11e7-8580-528e98de974b.png)
![img_0042](https://user-images.githubusercontent.com/6282596/34498213-3ead52a4-efc6-11e7-81bc-5bc6efc03725.png)
![img_0040](https://user-images.githubusercontent.com/6282596/34498215-40972af4-efc6-11e7-92af-31f78c462909.png)

**Comment by dmitriykovalev** [comment]
That looks correct. Can you also verify connector on the Camera side? (most likely it's correct, otherwise camera plugged in directly to the Pi wouldn't work).  

What's the Camera module version by the way? We only support V2 for now.

**Comment by annoscholten** [comment]
Hi Dimitri,

Well, your last statement may be the issue.  See photo's below, but this may not be a V2 camera?

![img_0046](https://user-images.githubusercontent.com/6282596/34499523-12b0de90-efcc-11e7-9ffc-4259f21c9891.png)
![img_0045](https://user-images.githubusercontent.com/6282596/34499526-14d2e380-efcc-11e7-8e44-8d6cd6e39775.png)

**Comment by dmitriykovalev** [comment]
Yep, that seems to be a 5MP camera. Check this [image](https://images-na.ssl-images-amazon.com/images/I/41vGRDyVq6L._SX355_.jpg), it has the same label as yours on the flex + "Rev 1.3" label.  For now we have only support for official Camera V2: https://www.raspberrypi.org/products/camera-module-v2/

**Comment by annoscholten** [comment]
Yes, that's it.  Totally missed that in the instructions.....

Thank you for the attention and help on this!  Off to go get a v2 camera now ...

**Comment by dmitriykovalev** [comment]
Sure, no problem! We'll improve error reporting mechanism, so it would be easier to detect. Let us know how everything goes with V2.

**Comment by annoscholten** [comment]
Do you know if there'll be an issue with the: https://www.raspberrypi.org/products/pi-noir-camera-v2/

(For low light applications)

**Comment by dmitriykovalev** [comment]
Pi Camera NoIR V2 should _technically_ work because it's the same sensor as Pi V2 but our internal ISP pipeline is not optimized for it.

**Comment by annoscholten** [comment]
ok, thank you, I'll stick with tried and true..

**Comment by annoscholten** [comment]
Just an update... I installed the V2 camera and everything runs well - including all the demos.

**Comment by dmitriykovalev** [comment]
Good to know, thanks for the update! Closing issue now.

**Comment by sainttelant** [comment]
@dmitriykovalev hey, guy, will you intend to figure out a way to support V1.3 camera in the future? thanks

**Comment by dmitriykovalev** [comment]
@sainttelant V2.1 and V1.3 have different sensors (Sony vs OmniVision). Our internal processing is heavily optimized for V2.1 sensor. We have experimental code which can work with V1.3 but inference quality is worse. For now there are no plans to make it official.

**Comment by sainttelant** [comment]
@dmitriykovalev 
thanks by the way, it seemed we have to choose V2.1 camera this time,maybe someday v1.3  supports perfectly, let us know..

**Comment by santhoshnp** [comment]
hi all i need help, in my vision bonnet kit camera is not enabling. i tried su
![screenshot 44](https://user-images.githubusercontent.com/39831264/44718636-4a407500-aade-11e8-99a8-5acb2478ebf9.png)
do raspi-config but no output

**Comment by dmitriykovalev** [comment]
@santhoshnp  check that your camera is proper connected physically.

**Comment by santhoshnp** [comment]
Thank for reply bro,


![whatsapp image 2018-08-29 at 11 00 40 am 1](https://user-images.githubusercontent.com/39831264/44767669-7b6f8280-ab7c-11e8-8f0c-5114e1a705b1.jpeg)
![whatsapp image 2018-08-29 at 11 00 39 am 1](https://user-images.githubusercontent.com/39831264/44767684-89bd9e80-ab7c-11e8-976d-1ea5fbe2eeb9.jpeg)
![whatsapp image 2018-08-29 at 11 00 39 am 2](https://user-images.githubusercontent.com/39831264/44767686-8a563500-ab7c-11e8-9cc4-c9f30f8041f2.jpeg)
![whatsapp image 2018-08-29 at 11 00 39 am](https://user-images.githubusercontent.com/39831264/44767687-8aeecb80-ab7c-11e8-8cbf-d1f23cda3fa5.jpeg)
![whatsapp image 2018-08-29 at 11 00 40 am](https://user-images.githubusercontent.com/39831264/44767688-8aeecb80-ab7c-11e8-9622-e674da997f4e.jpeg)

**Comment by santhoshnp** [comment]
I also have one doubt in joy detector,
while running vision kit it should be in active or inactive position,

**Comment by manoj7410** [comment]
@santhoshnp One thing you can try is to connect your camera directly with PI0 (Where short flex is connected currently). Then run the command "raspistill -o output.jpg" and check if camera is working. 

By default joy_detection is enabled and make sure you stop it by running the command "sudo systemctl stop joy_detection_demo"

**Comment by santhoshnp** [comment]
@manoj bro camera is working well in pi0 but camera is not enabling in vision bonnet i don't why.

**Comment by dmitriykovalev** [comment]
@santhoshnp check camera connector latches for short flex cable (Pi board and Vision Bonnet board), they must be locked (not loose).

**Comment by santhoshnp** [comment]
@dmitri
raspistill -w 1640 -h 922 -o image.jpg
mmal: Cannot read camera info, keeping the defaults for OV5647
mmal: mmal_vc_component_create: failed to create component 'vc.ril.camera' (1:ENOMEM)
mmal: mmal_component_create_core: could not create component 'vc.ril.camera' (1)
mmal: Failed to create camera component
mmal: main: Failed to create camera component
mmal: Camera is not detected. Please check carefully the camera module is installed correctly

**Comment by santhoshnp** [comment]
any one help me how to update raspistill camera app v1.3.11 why because i am using v2.1
please help me
raspistill -v
mmal: Cannot read camera info, keeping the defaults for OV5647

raspistill Camera App v1.3.11

Width 2592, Height 1944, quality 85, filename (null)
Time delay 5000, Raw no
Thumbnail enabled Yes, width 64, height 48, quality 35
Link to latest frame enabled  no
Full resolution preview No
Capture method : Single capture

Preview Yes, Full screen Yes
Preview window 0,0,1024,768
Opacity 255
Sharpness 0, Contrast 0, Brightness 50
Saturation 0, ISO 0, Video Stabilisation No, Exposure compensation 0
Exposure Mode 'auto', AWB Mode 'auto', Image Effect 'none'
Flicker Avoid Mode 'off'
Metering Mode 'average', Colour Effect Enabled No with U = 128, V = 128
Rotation 0, hflip No, vflip No
ROI x 0.000000, y 0.000000, w 1.000000 h 1.000000
mmal: mmal_vc_component_create: failed to create component 'vc.ril.camera' (1:ENOMEM)
mmal: mmal_component_create_core: could not create component 'vc.ril.camera' (1)
mmal: Failed to create camera component
mmal: main: Failed to create camera component
mmal: Camera is not detected. Please check carefully the camera module is installed correctly

**Comment by dmitriykovalev** [comment]
@santhoshnp check flex connectors.

**Comment by santhoshnp** [comment]
I think my camera version 2.1 but when I type raspistill -v (display the version as v1,3)
I think this is the problem.
can any one help me

![screenshot 47](https://user-images.githubusercontent.com/39831264/44893966-1c8c4380-ad0b-11e8-8d40-6ea717246c45.png)

**Comment by trsbalaji** [comment]
Hi, I bought vision kit version 1.1. Normal Raspberry pi zero w boots fine. Once connected  MIPI flat flex cable to Raspberrypi zero w board is not booting.

https://aiyprojects.withgoogle.com/vision-v1/

Please help me.

**Comment by trsbalaji** [comment]
Hi, I bought vision kit version 1.1. Normal Raspberry pi zero w boots fine. Once connected MIPI flat flex cable to Raspberrypi zero w board is not booting.

https://aiyprojects.withgoogle.com/vision-v1/

Please help me.

**Comment by magdesign** [comment]
Answer to [post](https://github.com/google/aiyprojects-raspbian/issues/224#issuecomment-354880794)

**Pi Camera NoIR V2  does not work.**

**Comment by ssanzr** [comment]
@dmitriykovalev, have you tried the Pi Camera NoIR V2? According to @magdesign it does not work.

Has anyone tried it?

Thanks!
