### ISSUE TITLE
Update aiyprojects please

### ISSUE THREAD

**Issue by amerinoo** [google/aiyprojects-raspbian#237]
Hello,
You put in the README " The newest code is in the aiyprojects branch, which supports all AIY kits. The voicekit branch is deprecated, and users should switch to the aiyprojects" so, could you update the code with the new improvements please?
This line is deprecated "with Assistant(credentials, model_id) as assistant:" and it is in aiyprojects branch and the examples don't work.

Thank you.

**Comment by drigz** [comment]
Sorry about the delay! I've got changes ready for this 
(and for the update to v1alpha2 of the Assistant gRPC API, which has my favourite feature - changing languages between requests with `aiy.i18n.set_language_code`) and they're on their way through testing & release.

The new process for testing code before we push it to GitHub is slower, but it should avoid some of the breakages we've had before.

**Comment by janvda** [comment]
Any idea when the aiyprojects branch will be updated for this ?
Currently my aiyprojects installation is no longer working as I have upgraded to Assistant SDK v0.1.0.

**Comment by dmitriykovalev** [comment]
`aiyprojects` has been updated several times since this was opened, closing now.
