### ISSUE TITLE
aiyprojects branch - HACKING.md inaccurate

### ISSUE THREAD

**Issue by sheridat** [google/aiyprojects-raspbian#242]
The HACKING.md needs a couple of changes related to the revised folder structure of the aiyprojects branch - change src/ to src/examples/voice/.

 The aiyprojects HACKING.md says

_You can find sample scripts in the **src** directory showing how to use the
Assistant SDK.

To execute any of these scripts on the Raspberry Pi, login to it and run
(replacing the filename with the script you want to run):

cd ~/AIY-projects-python
source env/bin/activate
python3 **src**/assistant_library_demo.py_

Perhaps it needs changing to this

You can find sample scripts in the **src/examples/voice** directory showing how to use the
Assistant SDK.

To execute any of these scripts on the Raspberry Pi, login to it and run
(replacing the filename with the script you want to run):

cd ~/AIY-projects-python
source env/bin/activate
**python3 src/examples/voice/assistant_library_demo.py**

Additionally, the check_audio.py script must be run with sudo inside the virtualenv, eg:

```
sudo env/bin/python checkpoints/check_audio.py
```

otherwise, you'll get the error:

```
Traceback (most recent call last):
  File "checkpoints/check_audio.py", line 27, in <module>
    import aiy.audio  # noqa
ImportError: No module named 'aiy'
```

**Comment by drigz** [comment]
Thanks for reporting - I've made an internal change to fix this, although I'll take a little while to go through review and be pushed to GitHub. This is because of our new release process, where changes happen to an internal repo first, and we periodically publish our internal repo to GitHub, which should stop problems like #203 happening again.

**Comment by sheridat** [comment]
@drigz great - closing as it is in the pipeline

**Comment by drigz** [comment]
Reopening as the release process is taking a while - this way people know that this is a known issue on the aiyprojects branch.

**Comment by dmitriykovalev** [comment]
`HACKING.md` was completely rewritten recently.
