### ISSUE TITLE
aiyprojects branch  -hat.py - non existent entity - Voice Bonnet

### ISSUE THREAD

**Issue by sheridat** [google/aiyprojects-raspbian#244]
Hi, Came across this in -hat.py

HAT_PATH = '/proc/device-tree/hat/'
HAT_PRODUCT_ID_RE = re.compile('0x[0-9A-Fa-f]+')
AIY_HATS = {
    1: 'Voice Hat',
    2: 'Vision Bonnet',
    3: 'Voice Bonnet',
}

Is it a fault or early notice of a product launch?
Ps - I don't have a clue what this code does - but I am pretty sure I don't need to.

**Comment by drigz** [comment]
\*taps nose knowingly\*
