### ISSUE TITLE
AIY Vision Bonnet

### ISSUE THREAD

**Issue by mphillips53** [google/aiyprojects-raspbian#252]
Raspberry pi zero w v1.1
Although dmesg reports that the bonnet booted correctly, none of the samples work for me. The joy_detection_demo starts with no errors but does not open a preview window overlay The joy_score is always 0.0f. The face_dection_demo starts with no errors and a preview window overlay opens but the app reports no faces were detected regardless of the number of frames chosen. All of the gpiozero demos launch without errors but none of the expected outputs occur(i.e., no led light on or off, no button pressed events on or off, etc.).
I verified through the spi interface that a payload is sent to the bonnet and a payload is received without any errors thrown.
Using gpio, I can read and write outputs to each pin.  Is there a test routine that I can run directly on the bonnet to see if it works?

**Comment by dmitriykovalev** [comment]
Please check [Troubleshooting](https://aiyprojects.withgoogle.com/vision/#assembly-guide-8-troubleshooting) section on our website. If that doesn't help, can you copy-paste your dmesg output?

**Comment by dmitriykovalev** [comment]
@mphillips53, please reopen if you still have issues.
