### ISSUE TITLE
step 13 page 45 book start voice unit

### ISSUE THREAD

**Issue by Lepracon68** [google/aiyprojects-raspbian#257]
In the book "Magpi essentials" AIY projects , page 45 , step 13 it says:
start the voice unit
Double click the "start dev terminal" icon and enter:
src/assistant_library_demo.py

That gives back the error message:
No such file or directory

when i search i found them at:
src/examples/voice

When i enter there (in src/examples/voice):
assistant_library_demo.py

it returns:
bash: assistant_library_demo.py: command not found

But when i do "ls" i see it's there and green.

I am new to this RaspberryPI thing and Voice is my first thing i do. Can anyone tell me how to proceed ?

**Comment by Lepracon68** [comment]
i found on the internet https://aiyprojects.withgoogle.com/voice#users-guide-3-using-your-device

3.1. START THE ASSISTANT LIBRARY DEMO APP
For the device to begin acting as your Google Assistant much like Google Home, start the assistant library demo app by double-clicking "Start dev terminal" on the Desktop and entering:

src/examples/voice/assistant_library_demo.py

The assistant library app has hotword detection built-in. To start a conversation with the Google Assistant, say "Okay, Google" or "Hey Google". When you are done, press Ctrl-C to end the application.

This returns :
You need client secrets to use the assistant API

So , also not correct, but with a solution beneath it (follow these instructions), so i am moving on and destroying the book which came with the package

**Comment by Lepracon68** [comment]
my mistake, 
assitent.json  instead of assistant.json, changed that, and will try on

**Comment by drigz** [comment]
The book is still pretty :)

But yes, unfortunately it is not up-to-date for the latest image - the examples moved when the Vision Kit was published to avoid confusing Vision Kit users. I'll look into adding a warning to help users like yourself.

**Comment by Lepracon68** [comment]
Thanks . i am a bit of a noob here, but loving it so far !

**Comment by Lepracon68** [comment]
It works with the assitant_library_demo
Thank you.

**Comment by drigz** [comment]
Glad to hear it's working :) We've added a warning which will be in the next image.
