### ISSUE TITLE
Vision: example object_detection.py raises exception SpicommOverflowError

### ISSUE THREAD

**Issue by saltrupiano** [google/aiyprojects-raspbian#260]
Using Pi Zero W:
pi@raspberrypi:~ $ cat /proc/cpuinfo | grep Revision
Revision	: 9000c1
- 2.5A power supply
- micro USB to USB hub for keyboard, mouse, USB mass storage
- mini HDMI to HDMI to VGA monitor

Running Pi OS image "aiyprojects-2018-01-03.img.xz"

googlevisionbonnet status:
pi@raspberrypi:~ $ dmesg | grep googlevisionbonnet
[   37.874139] googlevisionbonnet spi0.0: Initializing
[   37.935338] googlevisionbonnet spi0.0: Resetting myriad on probe
[   37.935357] googlevisionbonnet spi0.0: Resetting myriad
[   41.473213] googlevisionbonnet spi0.0: Writing myriad firmware
[   47.312605] googlevisionbonnet spi0.0: Myriad booting
[   47.524096] googlevisionbonnet spi0.0: Myriad ready

joy_detector_demo seemed to run fine.

After stopping and disabling the joy_detector demo and running source ~/AIY-projects-python/env/bin/activate, running face_detection_camera.py also seems fine. It displays the live input from the camera and recognizes faces and applies bounding boxes to the displayed output on the monitor.

Next tried object_detection, but this doesn't run, because it raises exception SpicommOverflowError:

(env) pi@raspberrypi:~/AIY-projects-python/src/examples/vision $ python object_detection.py --input /home/pi/Pictures/IMG_7088.JPG 
Traceback (most recent call last):
  File "object_detection.py", line 56, in <module>
    main()
  File "object_detection.py", line 47, in main
    result = inference.run(image_center)
  File "/home/pi/AIY-projects-python/src/aiy/vision/inference.py", line 70, in run
    return self._engine.image_inference(self._key, image, params)
  File "/home/pi/AIY-projects-python/src/aiy/vision/inference.py", line 284, in image_inference
    return self._communicate(request).inference_result
  File "/home/pi/AIY-projects-python/src/aiy/vision/inference.py", line 160, in _communicate
    response.ParseFromString(self._transport.send(request.SerializeToString()))
  File "/home/pi/AIY-projects-python/src/aiy/_drivers/_transport.py", line 33, in send
    return self._spicomm.transact(request)
  File "/home/pi/AIY-projects-python/src/aiy/_drivers/_spicomm.py", line 117, in transact
    raise SpicommOverflowError(PAYLOAD_SIZE)
aiy._drivers._spicomm.SpicommOverflowError

If the joy_detector and face_detection_camera run, then it wouldn't seem to be a hardware or connection issue with the SPI.

What may be causing SpicommOverflowError in object_detection? Maybe it is the size of the input image? Does it need to be cropped / reduced in some way first? Or is there some other issue?

**Comment by dmitriykovalev** [comment]
@saltrupiano 

Yes, this is because your input image is too big. For now image data is sent uncompressed, i.e. if you have W x H image (RGB), then you need to send 3 * W * H bytes which should not exceed PAYLOAD_SIZE (12MB = 12 * 1024 * 1024). To avoid this you can downscale your image to smaller resolution. We are working on a more flexible approach for image inference.
