### ISSUE TITLE
Issue with configure-driver.sh

### ISSUE THREAD

**Issue by jjfretired** [google/aiyprojects-raspbian#268]
In scripts/configure-driver.sh there are three greps

grep -q "dtoverlay=i2s-mmap" /boot/config.txt || \
  echo "dtoverlay=i2s-mmap" >> /boot/config.txt
grep -q "dtoverlay=googlevoicehat-soundcard" /boot/config.txt || \
  echo "dtoverlay=googlevoicehat-soundcard" >> /boot/config.txt
grep -q "dtparam=i2s=on" /boot/config.txt || \
  echo "dtparam=i2s=on" >> /boot/config.txt
I may be wrong but the 3 greps returne true as the config.txt file has the search items commented out.
If they test returns true the || (or) statement is never executed and the lines are never uncommented.

**Comment by sheridat** [comment]
Relates to the aiyprojects branch image. To get going I had to edit /boot/config.txt and uncomment 
dtoverlay=i2s-mmap
dtoverlay=googlevoicehat-soundcard

**Comment by drigz** [comment]
Great catch - thank you! We've updated the workaround posted on #255 and we'll look into fixing configure_driver.sh.
