### ISSUE TITLE
Continuous Listening Available?

### ISSUE THREAD

**Issue by idealist33** [google/aiyprojects-raspbian#273]
From the python example, a person should trigger AIY kit by saying 'Okay google' or press a button whenever saying commands.
I want to let AIY keep listening. First a person say 'change' and AIY executes a command. After that without triggering AIY again, I want to let AIY waits for person's speech.

**Comment by seanandre** [comment]
I believe you're talking about the assistant_library_demo.py
You can say "Okay Google" for every question just as a normal Google Home without pressing the button. The problem I'm having now is my speaker, it seems to be crackling when she speaks :(
Check out this link as it seems to be a little more updated than the MagPi that came in the box. 
https://aiyprojects.withgoogle.com/voice

**Comment by divx118** [comment]
@idealist33 You can restart the listening after it has finished with `self._assistant.start_conversation()`

**Comment by seanandre** [comment]
I seemed to fix the crackling in the speaker by overclocking the RPI in boot.

**Comment by idealist33** [comment]
Thanks a lot I used assistant.start_conversation().
