### ISSUE TITLE
Speaker making crackling noise

### ISSUE THREAD

**Issue by seanandre** [google/aiyprojects-raspbian#274]
So it seems my speaker is crackling every time Google Assistant speaks making it difficult to understand what she's saying. Any leads?

**Comment by drigz** [comment]
This isn't a software issue, so GitHub isn't the right place. You can try the [AIY Forums](https://www.raspberrypi.org/forums/viewforum.php?f=114) or [emailing support](mailto:support-aiyprojects@google.com).
