### ISSUE TITLE
errors running checkpoints/check_audio.py 

### ISSUE THREAD

**Issue by jjfretired** [google/aiyprojects-raspbian#277]

**Comment by jjfretired** [comment]
Sorry about leaving no comment prior.

1 - python3  checkpoints/check_audio.py should be run in env.

2 - code in file does check for Voice Hat and if so, tries to update /boot/config.txt.  But, when it tries to back up the file it fails.  Should this code be removed.
[audio.txt](https://github.com/google/aiyprojects-raspbian/files/1683194/audio.txt)

**Comment by drigz** [comment]
Thanks for the feedback! There's a new release on the way, which should resolve these issues.
