### ISSUE TITLE
aiyprojects makers-guide-3-4--run-your-app-automatically - New directory structure

### ISSUE THREAD

**Issue by sheridat** [google/aiyprojects-raspbian#279]
Hi, 

On the AIY forum people seem to be coming unstuck when following the instructions for "Voice" at 
https://aiyprojects.withgoogle.com/voice#makers-guide-3-4--run-your-app-automatically.

The instructions which are centred on the aiyprojects branch rather than voicekit tell you how to setup systemd config file and one of the lines in the content is 
`ExecStart=/bin/bash -c '/home/pi/AIY-voice-kit-python/env/bin/python3 -u src/my_assistant.py'`

perhaps that would be better amended to read 

`ExecStart=/bin/bash -c '/home/pi/AIY-voice-kit-python/env/bin/python3 -u src/examples/voice/my_assistant.py'
`
to reflect the new directory structure. 

There is also a sentence **Assuming that your app is src/my_assistant.py**
perhaps that should be amended to Assuming that your app is src/examples/voice/my_assistant.py

**Comment by drigz** [comment]
Thanks for passing that through! I just pushed a change to fix it.
