### ISSUE TITLE
will aiy vision kit be mass-produced in the future?

### ISSUE THREAD

**Issue by sainttelant** [google/aiyprojects-raspbian#284]
like the title,anyone knows? 

it is hard to purchase the vision kit from micro center, besides they are only sold in stores in US,not for international users, any one knows when will the kits be  available for international users apart from US?

**Comment by drigz** [comment]
We haven't made any announcements about future production runs of the Vision Kit, but if you sign up for the [AIY mailing list](https://services.google.com/fb/forms/aiycommunicationpreferences/) you'll be among the first to hear about availability of new and existing kits.
