### ISSUE TITLE
Error after changing client secrets: The OAuth client was deleted.

### ISSUE THREAD

**Issue by andrewtvuong** [google/aiyprojects-raspbian#288]
Thanks!

**Comment by drigz** [comment]
If you delete the cached credentials: `rm ~/.cache/voice-recognizer/assistant_credentials.json`

Then you can overwrite `~/assistant.json` with the new client secrets and rerun your script to trigger the auth process again.

Let us know how it goes!

**Comment by andrewtvuong** [comment]
@drigz sorry I had reflashed already. I believed I could have just deleted the old `~/assistant.json` and replacing it with a new credential file, but then receive "('deleted_client: The OAuth client was deleted.', '{\n "error" : "deleted_client",\n "error_description" : "The OAuth client was deleted."\n}')"

**Comment by drigz** [comment]
Maybe the code should handle that error by saying to the user: "If you intentionally changed your client secrets, please delete ~/.cache/voice-recognizer/assistant_credentials.json" and/or provide a command to reauth with new client secrets.

**Comment by JoelOsler** [comment]
This worked for me perfectly! I also feel that running any of the code with the framework should alert back to remove the cached file, as I was stuck for a while till I found this GitHub issue!
