### ISSUE TITLE
Unable to run scripts on startup

### ISSUE THREAD

**Issue by shivasiddharth** [google/aiyprojects-raspbian#29]
I have set up a wake word using snowboy. But when i tried to start the script on boot it does not seem to do anything. Following are the things that i tried.
1. setup crontab.
2. included the script in rc.local
3. tried adding it in init.d 
But all these seem to do nothing.
Any help is appreciable. TIA

**Comment by ensonic** [comment]
Nice job!
FYI, we're including ready made systemd startup scripts:
https://aiyprojects.withgoogle.com/voice/#users-guide-3-3--led-status-codes
If it works when you start it manually, all you need to do is:

    sudo systemctl enable voice-recognizer

Lets us know if that fixes it and please share your work!

**Comment by shivasiddharth** [comment]
What i actually meant is, the voice recognizer is working fine on boot but the script to start the snowboy is not running on start-up. If i could get the snowboy script to start on boot, i could complete the documentation and share them here.

**Comment by ensonic** [comment]
You can take some inspiration from
https://github.com/google/aiyprojects-raspbian/blob/master/systemd/voice-recognizer.service
and make one for snowboy. Here is the script that installs the services:
https://github.com/google/aiyprojects-raspbian/blob/master/scripts/install-services.sh

**Comment by shivasiddharth** [comment]
Thanks for the pointers Stephan.

**Comment by ensonic** [comment]
Please reopen if you still have issues.
