### ISSUE TITLE
No demo files?

### ISSUE THREAD

**Issue by jdquaff** [google/aiyprojects-raspbian#293]
Hello, I am all set up and powered on. When I was starting my demo process, my browser opened up and asked me for authentication. When I allowed it, it went to a timed out screen and would not let me go back and re-allow. 

Now, when I try to start my demo the terminal responds “src/assistant_library_demo.py bash:src/assistant_library_demo.py: No such file or directory”

Any ideas? I think it has to do with that timeout, and any help is appreciated.

**Comment by drigz** [comment]
The demo files have moved to `src/examples/voice/`. Does it work if you run from that path?

**Comment by jdquaff** [comment]
That worked! Thanks a ton! ~~
