### ISSUE TITLE
Can't install as a service on official image

### ISSUE THREAD

**Issue by bfenty** [google/aiyprojects-raspbian#295]
I've got the voice assistant running when I run the demo py script, but I can't seem to get it installed as a service via systemd. I've tried running the installer script, following the instructions from hacking.md, and the service fails every time I try to start it.

Here's what the console says:

 sudo systemctl status voice-recognizer.service
● voice-recognizer.service - voice recognizer
   Loaded: loaded (/lib/systemd/system/voice-recognizer.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2018-03-04 20:44:01 CST; 4s ago
  Process: 2134 ExecStart=/opt/aiy/projects-python/env/bin/python3 -u src/main.py (code=exited, status=203/EXEC)
 Main PID: 2134 (code=exited, status=203/EXEC)

Mar 04 20:44:01 gamepi2 systemd[1]: voice-recognizer.service: Main process exited, code=exited, status=203/EXEC
Mar 04 20:44:01 gamepi2 systemd[1]: voice-recognizer.service: Unit entered failed state.
Mar 04 20:44:01 gamepi2 systemd[1]: voice-recognizer.service: Failed with result 'exit-code'.
Mar 04 20:44:01 gamepi2 systemd[1]: voice-recognizer.service: Service hold-off time over, scheduling restart.
Mar 04 20:44:01 gamepi2 systemd[1]: Stopped voice recognizer.
Mar 04 20:44:01 gamepi2 systemd[1]: voice-recognizer.service: Start request repeated too quickly.
Mar 04 20:44:01 gamepi2 systemd[1]: Failed to start voice recognizer.
Mar 04 20:44:01 gamepi2 systemd[1]: voice-recognizer.service: Unit entered failed state.
Mar 04 20:44:01 gamepi2 systemd[1]: voice-recognizer.service: Failed with result 'exit-code'.

**Comment by divx118** [comment]
I noticed it too. It seems `VIRTUAL_ENV` is not used anymore so the [.service file](https://github.com/google/aiyprojects-raspbian/blob/aiyprojects/systemd/voice-recognizer.service) should be adjusted.
Something like below should do it.

```
# This service can be used to run your code automatically on startup. Look in
# HACKING.md for instructions on creating main.py and enabling it.

[Unit]
Description=voice recognizer
After=network.target ntpdate.service

[Service]
Environment=PATH=/home/pi/AIY-projects-python/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ExecStart=/usr/bin/python3 -u src/main.py
WorkingDirectory=/home/pi/AIY-projects-python
StandardOutput=inherit
StandardError=inherit
Restart=always
User=pi

[Install]
WantedBy=multi-user.target
```
If I am correct then [HACKING.md](https://github.com/google/aiyprojects-raspbian/blob/aiyprojects/HACKING.md) should also be updated by removing the `source env/bin/activate`

**Comment by mpamal** [comment]
I also had to change the User to root instead of pi, and also set RestartSec to 50. With the pi user, the assistant would cut off after couple of seconds speech

[Service]
Environment=VIRTUAL_ENV=/home/pi/AIY-projects-python/env
Environment=PATH=/home/pi/AIY-projects-python/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ExecStart=/usr/bin/python3 -u src/main.py
WorkingDirectory=/home/pi/AIY-projects-python
StandardOutput=inherit
StandardError=inherit
Restart=always
User=root
RestartSec=50

**Comment by mcduarte2000** [comment]
Just tried the solution above, without success (as any others I found through the web)... Very frustrating. The script as many people say, ran well by itself. The copy main.py, actually, not (should we make it executable?)...

I also don't see any "bin" folder on my AIY-projects-python. Not sure if that could not be a problem.

My service file right now, based on the comment above is like the one below. Can I help anyone test a different solution?

[Unit]
Description=voice recognizer
After=network.target ntpdate.service

[Service]
Environment=VIRTUAL_ENV=/home/pi/AIY-projects-python/env
Environment=PATH=/home/pi/AIY-projects-python/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr$
ExecStart=/usr/bin/python3 -u src/main.py
WorkingDirectory=/home/pi/AIY-projects-python
StandardOutput=inherit
StandardError=inherit
Restart=always
User=root
RestartSec=50

[Install]
WantedBy=multi-user.target

**Comment by divx118** [comment]
@mcduarte2000 It should be without the VIRTUAL_ENV so like below
```
# This service can be used to run your code automatically on startup. Look in
# HACKING.md for instructions on creating main.py and enabling it.

[Unit]
Description=voice recognizer
After=network.target ntpdate.service

[Service]
Environment=PATH=/home/pi/AIY-projects-python/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ExecStart=/usr/bin/python3 -u src/main.py
WorkingDirectory=/home/pi/AIY-projects-python
StandardOutput=inherit
StandardError=inherit
Restart=always
User=pi

[Install]
WantedBy=multi-user.target
```

main.py doesn't need to be executable, because you start it with `/usr/bin/python3  -u src/main.py`
Is main.py in `/home/pi/AIY-projects-python/src`?
`/home/pi/AIY-projects-python/bin` isn't there anymore. so it could be removed from `Environment=PATH=` however it doesn't break anything if `/home/pi/AIY-projects-python/bin` is in the service file.
Can you manually start main.py with `/usr/bin/python3  /home/pi/AIY-projects-python/src/main.py`?

**Comment by mcduarte2000** [comment]
Many thanks. Copied/pasted your code, unfortunately still not working.

 Yes, /usr/bin/python3 /home/pi/AIY-projects-python/src/main.py works perfectly.

Also strange if write on the crontab the command below, the led turns on, but, the assistant doesn't answer...

@reboot /usr/bin/python3 /home/pi/AIY-projects-python/src/main.py

**Comment by floresboy** [comment]
when i redirect output (/usr/bin/python3 /home/pi/AIY-voice-kit-python/src/examples/voice/main.py >> /tmp/out.txt) it doen't work either. When i leave the redirection out everything is fine.

Beats me but i don't get it.

**Comment by divx118** [comment]
@mcduarte2000 Just to be sure, you did enable the service with `sudo systemctl enable voice-recognizer.service`
Can you give the output of `sudo systemctl --all | grep voice-recognizer.service`
and the output of `sudo journalctl -u voice-recognizer -n 14 --no-hostname`

**Comment by floresboy** [comment]
(sorry @divx118,  just my results)

pi@raspberrypi:~ $ sudo systemctl --all | grep voice-recognizer.service
  voice-recognizer.service                                                                        loaded    active     running            voice recognizer  

pi@raspberrypi:~ $ sudo journalctl -u voice-recognizer -n 14 --no-hostname
-- Logs begin at Thu 2016-11-03 18:16:42 CET, end at Wed 2018-04-25 19:46:09 CEST. --
Apr 25 19:44:55 systemd[1]: Started voice recognizer.
Apr 25 19:45:08 pulseaudio[908]: [pulseaudio] server-lookup.c: Unable to contact D-Bus: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
Apr 25 19:45:08 pulseaudio[908]: [pulseaudio] main.c: Unable to contact D-Bus: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
pi@raspberrypi:~ $

**Comment by divx118** [comment]
@floresboy You could try adding a $DISPLAY variable to the service file like below. Maybe that can get you get rid of the error, so main.py can start correctly.
```
# This service can be used to run your code automatically on startup. Look in
# HACKING.md for instructions on creating main.py and enabling it.

[Unit]
Description=voice recognizer
After=network.target ntpdate.service

[Service]
Environment=DISPLAY=:0
Environment=PATH=/home/pi/AIY-projects-python/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ExecStart=/usr/bin/python3 -u src/main.py
WorkingDirectory=/home/pi/AIY-projects-python
StandardOutput=inherit
StandardError=inherit
Restart=always
User=pi

[Install]
WantedBy=multi-user.target
```

**Comment by floresboy** [comment]
Got it working on raspi 3+: I see a lot of issues with the old v1 HAT and this model raspi.

```
sudo apt-get update
sudo apt-get -y dist-upgrade

```
this deletes all modifications you've made.
so recreate main.py file by copiing one example file to main.py

edited the  /etc/systemd/system/multi-user.target.wants/voice-recognizer.service as follows:


```
# This service can be used to run your code automatically on startup. Look in
# HACKING.md for instructions on creating main.py and enabling it.

[Unit]
Description=voice recognizer
After=network.target ntpdate.service

[Service]
Environment=DISPLAY=:0
Environment=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ExecStart=/usr/bin/python3 /home/pi/AIY-voice-kit-python/src/examples/voice/main.py
WorkingDirectory=/home/pi/AIY-voice-kit-python/src/examples/voice
StandardOutput=inherit
StandardError=inherit
Restart=always
User=pi

[Install]
WantedBy=multi-user.target
```



Thanks divX!

**Comment by mcduarte2000** [comment]
Hi again @divx118 , tried the script above, but still not working...

Regarding your questions (note: using a Pi 2 Model B):

```
sudo systemctl --all | grep voice-recognizer.service
● voice-recognizer.service                                                                     loaded    failed   failed    voice recognizer  

```

```
sudo journalctl -u voice-recognizer -n 14 --no-hostname
-- Logs begin at Thu 2016-11-03 17:16:43 UTC, end at Wed 2018-04-25 22:21:57 UTC. --
Apr 25 22:18:32 systemd[1]: voice-recognizer.service: Unit entered failed state.
Apr 25 22:18:32 systemd[1]: voice-recognizer.service: Failed with result 'exit-code'.
Apr 25 22:18:32 systemd[1]: voice-recognizer.service: Service hold-off time over, scheduling restart.
Apr 25 22:18:32 systemd[1]: Stopped voice recognizer.
Apr 25 22:18:32 systemd[1]: Started voice recognizer.
Apr 25 22:18:32 systemd[1]: voice-recognizer.service: Main process exited, code=exited, status=203/EXEC
Apr 25 22:18:32 systemd[1]: voice-recognizer.service: Unit entered failed state.
Apr 25 22:18:32 systemd[1]: voice-recognizer.service: Failed with result 'exit-code'.
Apr 25 22:18:33 systemd[1]: voice-recognizer.service: Service hold-off time over, scheduling restart.
Apr 25 22:18:33 systemd[1]: Stopped voice recognizer.
Apr 25 22:18:33 systemd[1]: voice-recognizer.service: Start request repeated too quickly.
Apr 25 22:18:33 systemd[1]: Failed to start voice recognizer.
Apr 25 22:18:33 systemd[1]: voice-recognizer.service: Unit entered failed state.
Apr 25 22:18:33 systemd[1]: voice-recognizer.service: Failed with result 'exit-code'.
```

**Comment by divx118** [comment]
@mcduarte2000 there seems to be a problem with your main.py . Could you post the code?
Or you could add yourself some more debugging info to see where it fails.

**Comment by mcduarte2000** [comment]
@divx118 

If you need more logs, please tell me what command I should run. I know how to do basic stuff, but not a linux pro. :) I am using the latest version of the script examples, which were updates 2 months ago. Just as a precaution I copied again the script to main.py and tried again to activate the service. The logs results changed (but still no success, go to the end to see current status after some further changes):

**1st Try**

```
May 01 10:58:40 systemd[1]: voice-recognizer.service: Failed with result 'exit-code'.
May 01 10:58:40 systemd[1]: voice-recognizer.service: Service hold-off time over, scheduling restart.
May 01 10:58:40 systemd[1]: Stopped voice recognizer.
May 01 10:58:40 systemd[1]: Started voice recognizer.
May 01 10:58:40 systemd[440]: voice-recognizer.service: Failed at step EXEC spawning /home/pi/AIY-projects-python/env/bin/python3: No s
May 01 10:58:40 systemd[1]: voice-recognizer.service: Main process exited, code=exited, status=203/EXEC
May 01 10:58:40 systemd[1]: voice-recognizer.service: Unit entered failed state.
May 01 10:58:40 systemd[1]: voice-recognizer.service: Failed with result 'exit-code'.
May 01 10:58:41 systemd[1]: voice-recognizer.service: Service hold-off time over, scheduling restart.
May 01 10:58:41 systemd[1]: Stopped voice recognizer.
May 01 10:58:41 systemd[1]: voice-recognizer.service: Start request repeated too quickly.
May 01 10:58:41 systemd[1]: Failed to start voice recognizer.
May 01 10:58:41 systemd[1]: voice-recognizer.service: Unit entered failed state.
May 01 10:58:41 systemd[1]: voice-recognizer.service: Failed with result 'exit-code'.
```

A bit more detail from using journalctl -xb:

```
voice-recognizer.service: Failed at step EXEC spawning /home/pi/AIY-projects-python/env/bin/python3: No such file or directory
-- Subject: Process /home/pi/AIY-projects-python/env/bin/python3 could not be executed
-- Defined-By: systemd
```

**2nd Try**

Tried to create a symbolic link to solve the error "No such file or directory", and now the log gives me the error:

```
May 01 12:31:57 systemd[1]: voice-recognizer.service: Unit entered failed state.
May 01 12:31:57 systemd[1]: voice-recognizer.service: Failed with result 'exit-code'.
May 01 12:31:57 systemd[1]: voice-recognizer.service: Service hold-off time over, scheduling restart.
May 01 12:31:57 systemd[1]: Stopped voice recognizer.
May 01 12:31:57 systemd[1]: Started voice recognizer.
May 01 12:31:58 systemd[1]: voice-recognizer.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 01 12:31:58 systemd[1]: voice-recognizer.service: Unit entered failed state.
May 01 12:31:58 systemd[1]: voice-recognizer.service: Failed with result 'exit-code'.
May 01 12:31:58 systemd[1]: voice-recognizer.service: Service hold-off time over, scheduling restart.
May 01 12:31:58 systemd[1]: Stopped voice recognizer.
May 01 12:31:58 systemd[1]: voice-recognizer.service: Start request repeated too quickly.
May 01 12:31:58 systemd[1]: Failed to start voice recognizer.
May 01 12:31:58 systemd[1]: voice-recognizer.service: Unit entered failed state.
May 01 12:31:58 systemd[1]: voice-recognizer.service: Failed with result 'exit-code'.
```

On startup getting the error:

```
-- The start-up result is done.
May 01 12:35:50 raspberrypi dnsmasq[436]: started, version 2.76 cachesize 150
May 01 12:35:50 raspberrypi dnsmasq[436]: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify
May 01 12:35:50 raspberrypi dnsmasq[436]: warning: interface usb0 does not currently exist
May 01 12:35:50 raspberrypi dnsmasq-dhcp[436]: DHCP, IP range 192.168.11.50 -- 192.168.11.100, lease time 2h
May 01 12:35:50 raspberrypi dnsmasq[436]: read /etc/hosts - 5 addresses
May 01 12:35:50 raspberrypi python3[391]: /home/pi/AIY-projects-python/env/bin/python3: can't open file 'src/main.py': [Errno 2] No such file or directory
May 01 12:35:50 raspberrypi systemd[1]: voice-recognizer.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 01 12:35:50 raspberrypi systemd[1]: voice-recognizer.service: Unit entered failed state.
May 01 12:35:50 raspberrypi systemd[1]: voice-recognizer.service: Failed with result 'exit-code'.
May 01 12:35:50 raspberrypi lightdm[405]: Error getting user list from org.freedesktop.Accounts: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Accou
May 01 12:35:50 raspberrypi dhcpcd[302]: wlan0: carrier acquired
May 01 12:35:50 raspberrypi kernel: IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
May 01 12:35:50 raspberrypi dhcpcd[302]: DUID 00:01:00:01:22:63:da:d2:b8:27:eb:79:ad:0a
May 01 12:35:50 raspberrypi dhcpcd[302]: wlan0: IAID 38:6e:46:89
May 01 12:35:50 raspberrypi dhcpcd[302]: wlan0: adding address fe80::5b6d:aeed:8f14:a7af
May 01 12:35:50 raspberrypi dnsmasq[436]: no servers found in /run/dnsmasq/resolv.conf, will retry
May 01 12:35:50 raspberrypi systemd[1]: Started Light Display Manager.
```

**3rd Try**

Because of the error above, copied main.py to the src folder. The light blinks. The service is working! The lights blink. Google doesn't answer.

```
sudo systemctl --all | grep voice-recognizer.service

voice-recognizer.service                                            loaded    active   running   voice recognizer
```

On the startup log also no problems, so I am stuck...

```
-- Subject: Unit voice-recognizer.service has finished start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit voice-recognizer.service has finished starting up.
```

**Conclusion:** After some corrections, I got the service running, like I got previously with cron, with blue light blinking and turning on when pressed, but Google Assistant seams deaf..

**Comment by divx118** [comment]
@mcduarte2000 Can you post the output of `cat /etc/systemd/system/multi-user.target.wants/voice-recognizer.service`
I believe you still are trying to run python in the environment because of 
```
voice-recognizer.service: Failed at step EXEC spawning /home/pi/AIY-projects-python/env/bin/python3: No such file or directory
-- Subject: Process /home/pi/AIY-projects-python/env/bin/python3 could not be executed
```

**Comment by millennialcoder** [comment]
@divx118

Thanks for posting here! I've followed what you said and was able to get my service running when checking the status of the service but now the voice kit won't respond. If I start the main.py manually it works as it should. 

I ended up checking sudo journal like you mentioned and found that it says I need client secrets for API to work. Add a assistant.json to root. I've already done this, API works manually why would it not be able to other wise? Any suggestions? Thank you again.

**Comment by RowanZee** [comment]
@divx118 I am also experiencing the same issue. My service will not start due to looking the assistant.json file in the /root/ directory which obviously doesny exist. Should be looking in /home/pi/...

Have you solved this? Any other solutions?

**Comment by divx118** [comment]
@RowanZee Can you post the output of `cat /etc/systemd/system/multi-user.target.wants/voice-recognizer.service`

**Comment by RowanZee** [comment]
@divx118 
[Unit]
Description=voice recognizer
After=network.target ntpdate.service

[Service]
Environment=VIRTUAL_ENV=/home/pi/voice-recognizer-raspi/env
Environment=PATH=/home/pi/voice-recognizer-raspi/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ExecStart=/home/pi/voice-recognizer-raspi/env/bin/python3 -u src/main.py
WorkingDirectory=/home/pi/voice-recognizer-raspi
StandardOutput=inherit
StandardError=inherit
Restart=always
User=root

[Install]
WantedBy=multi-user.target

I've moved my package to an older one which still used the virtual env. I couldnt get the new one to work. Works perfectly when run manually inside the virtual environment

**Comment by divx118** [comment]
@RowanZee It should be `User=pi` and not `User=root` in the service file.
Also the environment is still active in your file. See my first post second one from the top in this issue

**Comment by RowanZee** [comment]
@divx118 I have tried that, makes no difference. Service also seems to start but when I run sudo journalctl -u voice-recognizer -n 14 --no-hostname shows the following

May 28 18:41:53 python3[14317]: You need client secrets to use the Assistant API.
May 28 18:41:53 python3[14317]: Follow these instructions:
May 28 18:41:53 python3[14317]:     https://developers.google.com/api-client-library/python/auth/installed-ap
May 28 18:41:53 python3[14317]: and put the file at /root/assistant.json
May 28 18:41:53 systemd[1]: voice-recognizer.service: Main process exited, code=exited, status=1/FAILURE
May 28 18:41:53 systemd[1]: voice-recognizer.service: Unit entered failed state.
May 28 18:41:53 systemd[1]: voice-recognizer.service: Failed with result 'exit-code'.

**Comment by divx118** [comment]
@RowanZee Just to be absolutely sure, you have in `/etc/systemd/system/multi-user.target.wants/voice-recognizer.service` the below code and you get the above error you posted when you restart the service or after a reboot?

```
# This service can be used to run your code automatically on startup. Look in
# HACKING.md for instructions on creating main.py and enabling it.

[Unit]
Description=voice recognizer
After=network.target ntpdate.service

[Service]
Environment=PATH=/home/pi/AIY-projects-python/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ExecStart=/usr/bin/python3 -u src/main.py
WorkingDirectory=/home/pi/AIY-projects-python
StandardOutput=inherit
StandardError=inherit
Restart=always
User=pi

[Install]
WantedBy=multi-user.target
```

**Comment by RowanZee** [comment]
@divx118 That is correct. But I have managed to solve it. I changed the user to pi and reran the authentication process. This seems to have solved the problem as the service now runs. Thanks for  all the help :)

**Comment by KevinZhou92** [comment]
@divx118 Holy shit! You are a fking genius!!!. I played around with the autostart stuff all day but just can't get it work.
Can you explain how this magic environment setting works?
`Environment=DISPLAY=:0`

**Comment by divx118** [comment]
@KevinZhou92

It just defines `$DISPLAY` in the environment you are launching the service, because there was the below error in the log. I didn't have this problem, but am still on an old version without pulseaudio.

```
Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
```

Btw no genius, just looking at the error messages. :)

**Comment by ShapeShifter499** [comment]
Changing my unit file to the following works for me.

```

# This service can be used to run your code automatically on startup. Look in
# HACKING.md for instructions on creating main.py and enabling it.

[Unit]
Description=voice recognizer
After=network.target ntpdate.service

[Service]
Environment=DISPLAY=:0
Environment=PATH=/home/pi/AIY-projects-python/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ExecStart=/usr/bin/python3 -u src/main.py
WorkingDirectory=/home/pi/AIY-projects-python
StandardOutput=inherit
StandardError=inherit
Restart=always
User=pi

[Install]
WantedBy=multi-user.target
```
