### ISSUE TITLE
AIY Vision's spare ribbon cables

### ISSUE THREAD

**Issue by tranqkhue** [google/aiyprojects-raspbian#299]
Hi,
Where can I get spare ribbon cables for AIY Vision kit?

**Comment by daverck** [comment]
what part number on the list ?
https://aiyprojects.withgoogle.com/vision

**Comment by dmitriykovalev** [comment]
@tranqkhue Long flex cable from VisionKit (which goes to the camera module) can be replaced with [this one](https://www.adafruit.com/product/3157).
