### ISSUE TITLE
Support of Media Responses

### ISSUE THREAD

**Issue by hyzhak** [google/aiyprojects-raspbian#304]
I'm working right now on actions which use Media Responses but they don't work on AIY Voice. Is there any plan to support it on AIY Voice?
https://developers.google.com/actions/assistant/responses#media_responses

**Comment by drigz** [comment]
@hyzhak The AIY library just provides a wrapper around the Assistant SDK, so we're limited to what that supports. Does https://github.com/googlesamples/assistant-sdk-python/issues/132 describe your issue accurately? If not, you could open an upstream issue.

**Comment by hyzhak** [comment]
@drigz thanks! I've created dedicated issue https://github.com/googlesamples/assistant-sdk-python/issues/203 because Media Response is a very fresh thing, so that issue could be obsolete.

**Comment by hyzhak** [comment]
@drigz @dmitriykovalev could you get new Assistant SDK, so we be able to try Media Response here?
This issue might be solved by new update https://github.com/googlesamples/assistant-sdk-python/issues/203

**Comment by hyzhak** [comment]
As I see you still use old `0.1.0` version here https://github.com/google/aiyprojects-raspbian/blob/aiyprojects/src/setup.py#L17 but we already could use modern one `1.0.0` https://github.com/googlesamples/assistant-sdk-python/blob/master/google-assistant-library/CHANGELOG.rst

**Comment by dmitriykovalev** [comment]
We are going to use the latest assistant library in the next SD card image release. I don't have exact release date but probably during a month timeframe.

**Comment by whoo** [comment]
Hi Guys,

Have you got information regarding that?
- It works with x86 version of SDK
- it does not on RaspberryPi3 /B+


Tks
