### ISSUE TITLE
Unable to Record via Voicehat Mic Board 

### ISSUE THREAD

**Issue by Flowdeeps** [google/aiyprojects-raspbian#307]
I'm using the latest image, updated and upgraded via apt but the kit is the first revision running on an RPi 3.

The button light pulses when using the demo scripts, assistant_library_demo.py for example. The speakers work when testing the audio but no mic recording. When I use audacity I can see and record the mic board and get play back.

```
$aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: sndrpigooglevoi [snd_rpi_googlevoicehat_soundcar], device 0: Google voiceHAT SoundCard HiFi voicehat-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

$ arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: sndrpigooglevoi [snd_rpi_googlevoicehat_soundcar], device 0: Google voiceHAT SoundCard HiFi voicehat-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

/boot/config.txt has the dtoverlay lines enabled

```
dtoverlay=i2s-mmap
dtoverlay=googlevoicehat-soundcard
```

If anyone can help with that I'd be really grateful.

**Comment by drigz** [comment]
Can you clarify what you mean by "no mic recording"? For example, what happens when you run the Check Audio script - do you get an error message or just silence?

**Comment by Flowdeeps** [comment]
It's just silence. As it's a brand new installation and I can get sound out of it with no issues in Audacity it makes me think it's a setup or software issue.

**Comment by KarmaMonk** [comment]
Same Problem here. The microphone stopped working after I upgraded (sudo apt-get upgrade) and restarted the raspi.

**Comment by Flowdeeps** [comment]
I had a spare SD card so I thought I'd try reverting to the older image. Worked straight away.

**Comment by wezmininger** [comment]
Ive had the same issue with the Feb 21 2018 image but only after doing update/upgrade/reboot.

**Comment by devalnor** [comment]
+1

**Comment by drigz** [comment]
Thanks for the feedback, everyone! We're working on a new release that fixes this issue. Until then, you'll need to use the 2018-01-03 image or reflash 2018-02-21 and avoid running `apt-get upgrade`. Alternatively, you can try the steps in https://github.com/google/aiyprojects-raspbian/issues/313#issuecomment-376046952.

**Comment by af987** [comment]
I see that a new image has been released (dated 2018-04-13).  Is this issue fixed in this new image?  I might be being a bit thick, but is there a release note for the image indicating which issues it fixes?  If there is, where can it be found as I can't seem to find it.

**Comment by LondonSi72** [comment]
Documentation on updates seems to be a bit ad-hoc at best. I tend to wait for others to try and find the bits that have been added/broken and comment here before I spend ages trying to figure out why something has changed.

**Comment by bwims** [comment]
The 2018-04-13 version works - BUT.

I have the original installation (2017-05-03), upgraded according the instructions here: http://eduncan911.com/stem/embedded/aiy-google-assistant-upgrades-may-2017.html

And the playback volume of a voice recorded wav file is about twice as loud as one you get from the newest version (2018-04-13)

I want to run the latest version as the old one is almost entirely deprecated, but this recording volume thing is a killer!

Here are the test wav files (Testing, 1 2 3 ) produced by both versions, if you are interested.

https://www.dropbox.com/s/ogi1rhmd5u6vz44/OriginalAIY.wav?dl=0
https://www.dropbox.com/s/9aryvvy1i9j29kf/NewAIY.wav?dl=0

**Comment by drigz** [comment]
@bwims Just to confirm, is your issue that the volume is too low with 2018-04-13, or that it is too high when you do the upgrade yourself?

If the latter, I'm afraid we don't support that process, although maybe the workaround to #47 would help you.

**Comment by bwims** [comment]
Hi.  

The answer to your question is: "that the volume is too low with 2018-04-13".  

I have just noticed that there is a way to attach files, for which I previously gave dropbox links
I dragged a zip file here called TestWavFiles.zip

[TestWavFiles.zip](https://github.com/google/aiyprojects-raspbian/files/1967213/TestWavFiles.zip)

You should notice that the 2017-05-03 version (OriginalAIY )
produces a much louder, more audible recording than the 2018-04-13 version (NewAIY).

Something about the changes in the new version produced to incorporate the V2 boards has reduced the volume of the recording to unacceptably quiet levels, and I can find no way to affect them.

What I would hope that you mightprovide is a means of adjusting the recording level as per alsamixer, or at least a .ini file with the default setting in an editable form.

Thanks,
Brian
