### ISSUE TITLE
Problems using 4-mic ReSpeaker board with AIY image

### ISSUE THREAD

**Issue by melzoghbi** [google/aiyprojects-raspbian#319]
Hi,

I was using Voice Hat board for working with google assistant sdk on my RPI3. Now, i removed the voice hat hardware board and installed respeaker board. I am not able to reset my audio driver so i can install respeaker driver.  

Is there reference document that someone can point me to so i can install other audio drivers on RPI3?

Thanks.

**Comment by drigz** [comment]
Hey @melzoghbi, thanks for the feedback. I'm not familiar with ReSpeaker, so I'll need some clarification: Could you point to the exact ReSpeaker hardware you're using, and explain exactly how you're trying to install the audio driver?

I expect you'll need to remove the AIY ALSA config, which is stored at /etc/asound.conf and ~/.asoundrc, and replace it with config suitable for the ReSpeaker.

How was the AIY driver installed? Are you using the AIY SD card image or did you follow HACKING.md? It may be easier to start from the vanilla RPi SD card image.

**Comment by melzoghbi** [comment]
Hi @drigz 

Here is the details of respeaker board on PI: https://github.com/SeeedDocument/ReSpeaker-4-Mic-Array-for-Raspberry-Pi/blob/master/ReSpeaker-4-Mic-Array-for-Raspberry-Pi.md

I tried but failed to completely remove AIY drivers from the OS so i started from scratch with a new raspbian image.

**Comment by drigz** [comment]
Thanks for info - glad you found another approach.

I'll leave the issue open in case anyone else encounters this.

**Comment by dmitriykovalev** [comment]
We switched to PulseAudio, ALSA configs are not relevant anymore.
