### ISSUE TITLE
Assistant is unable to call or send messages

### ISSUE THREAD

**Issue by viggy96** [google/aiyprojects-raspbian#320]
Upon asking the assistant to make a call, or make a text/e-mail etc, it replies that it can't do so yet.

**Comment by drigz** [comment]
This is a limitation of the [Assistant SDK](https://github.com/googlesamples/assistant-sdk-python). It can't do everything that the Google Home can at the moment.

**Comment by viggy96** [comment]
@drigz Do you know if that functionality is planned on being added, or where I can find out?

**Comment by drigz** [comment]
There's a brief description of the roadmap on the [Assistant SDK website](https://developers.google.com/assistant/sdk/overview#developer_preview_and_roadmap). I'm not aware of plans to implement call/message functionality.
