### ISSUE TITLE
Can't run bonnet_model_compiler.par -- Unexpected error

### ISSUE THREAD

**Issue by rachelspykerman** [google/aiyprojects-raspbian#323]
Hi,

I'm trying to run the bonnet_model_compiler.par on a Ubuntu 14.04 virtual machine, however, I run into an "Unexpected error." message. I'm am trying to run it on the "mobilenet_ssd_256res_0.125_person_cat_dog.pb" as well as on the "mobilenet_v1_160res_0.5_imagenet.pb", however, both give me the same errors. See the following:

./bonnet_model_compiler.par --frozen_graph_path=./mobilenet_ssd_256res_0.125_person_cat_dog.pb --output_graph_path=./mobilenet_v1_160res_0.5_imagenet.binaryproto --input_tensor_name="image_tensor" --output_tensor_names="Preprocessor/sub" --input_tensor_size=256 --output_graph_path="./converted_graph.binaryproto"
Unexpected error.

Am I missing some setup requirement? Also are there any flags to show more debug messages?

Thanks
Rachel

**Comment by sainttelant** [comment]
plz check the issue of #314

**Comment by dmitriykovalev** [comment]
Closing this, check #314 instead.
