### ISSUE TITLE
Why response is slow in cloudspeech demo?

### ISSUE THREAD

**Issue by varad1311** [google/aiyprojects-raspbian#324]
Hi! I'm using cloudspeech for home automation ( to control various electrical appliances like lights,fan etc). When I give instruction like "turn on lights", it takes much time to execute that operation and make the corresponding GPIO pin HIGH. Why this happens? Is it due to slow internet connection? I'm using my mobiles hotspot to connect raspberry pi.

**Comment by drigz** [comment]
I'd expect it would be limited by the network connection. It just uploads the audio Google's servers, and the action executes as soon as the transcription text is returned.

How slow is slow? eg how many seconds from command to response?

**Comment by varad1311** [comment]
Hi! Sometimes it is very slow. It takes 10 to 15 seconds to respond.
Sometimes the program crashes.

**Comment by dmitriykovalev** [comment]
@varad1311 Do you still have this issue even with the latest SD card image?

**Comment by nunziofiore** [comment]
without any update to the code I have the same issue. Last week it was ok and I have a quick response, today I have 15/20seconds to wait. No problem on my wifi speed.

**Comment by dmitriykovalev** [comment]
@nunziofiore Can you try check Cloud Speech web control panel and see if everything is fine there?
