### ISSUE TITLE
Vision_Bonnet_compiler Link Broken?

### ISSUE THREAD

**Issue by leecarraher** [google/aiyprojects-raspbian#328]
The vision_bonnet_compiler download link
https://dl.google.com/dl/aiyprojects/vision/bonnet_model_compiler_2017_12_13.tgz
appears to be broken. Does anyone have an alternate link?

**Comment by kodukulav** [comment]
Yes, even I'm not able to download at the link given in the website.

**Comment by sainttelant** [comment]
as i know, Google teams are trying to update the compiler tool to solve some compiler issues,plz refer to the issue #314

**Comment by chadwallacehart** [comment]
Link is broken for me too. I found a copy I downloaded a while ago: [https://www.dropbox.com/s/sedgmjaf9ng2mnd/bonnet_model_compiler_2017_12_13.tgz?dl=0](https://www.dropbox.com/s/sedgmjaf9ng2mnd/bonnet_model_compiler_2017_12_13.tgz?dl=0)

**Comment by kodukulav** [comment]
@chadwallacehart :Thanks for sharing!

**Comment by minakhan01** [comment]
@chadwallacehart thanks for the link!

**Comment by weiran-work** [comment]
@leecarraher @kodukulav @chadwallacehart @sainttelant @minakhan01 
Folks, we just released an updated version of the compiler. It fixed some issues people are experiencing when compiler customized TF model. It also added an option to print more debug information when the tool fails.
https://dl.google.com/dl/aiyprojects/vision/bonnet_model_compiler_latest.tgz

**Comment by leecarraher** [comment]
@chadwallacehart  @weiranzhao Thank you for the links.

**Comment by dmitriykovalev** [comment]
Closing, compiler download link is working now.
