### ISSUE TITLE
face_detection.binaryproto unreadable in regular tensorflow

### ISSUE THREAD

**Issue by vincentteyssier** [google/aiyprojects-raspbian#330]
Hi, 

I'm trying to read the binaryproto model for face detection in tensorflow, using both binary or text method and I get encoding errors.
Is there a way to decode the model in TF?
I see that protobuf files are available to download for object detection, but not for the joy detector demo.

**Comment by sainttelant** [comment]
it seems TF can read the graph.pb model for detection, not for binaryproto models which are used to execute on vision kit.

**Comment by dmitriykovalev** [comment]
@vincentteyssier Face detection binaryproto will not easily work with TF, it's VisionKit specific. You can find all binaries including one for face detection in `~/models`.

**Comment by vincentteyssier** [comment]
@dmitriykovalev *Thanks. Yes that's where I found the binary and was trying to load it. Is there any tool to convert it to a .pb file? Should be possible with protobuf?

**Comment by lleonid** [comment]
There's no tool to convert face detection binary proto back to use with TF.
The designed flow is one-way from TF to VisionKit specific format.
