### ISSUE TITLE
Source code and dts file for Voice Bonnet

### ISSUE THREAD

**Issue by htruong** [google/aiyprojects-raspbian#332]
I noticed that the Voice Bonnet comes with the new raspbian build and perhaps a specialized-built kernel, but I couldn't find the source for the `snd_aiy_voicebonnet` kernel driver anywhere, and the dts for the corresponding dtbo file. I wonder where can I find the source code for the components.

Thank you so much :)

**Comment by dmitriykovalev** [comment]
Please look at `/usr/src/` for `snd_aiy_voicebonnet` source code.

**Comment by htruong** [comment]
Thank you - found it!
