### ISSUE TITLE
Vision Kit 1.1 Camera Orientation Upside Down Per Setup Instructions.

### ISSUE THREAD

**Issue by andrewtvuong** [google/aiyprojects-raspbian#333]
Any way to flip it via software?

**Comment by dmitriykovalev** [comment]
Could you please clarify what kind of issue do you have? You can always flip image from the camera using `vflip/hflip` parameters from the Renderers API, https://picamera.readthedocs.io/en/release-1.13/api_renderers.html

**Comment by andrewtvuong** [comment]
I'm sorry I resolved the issue of my own doing. Turns out I was using code that included -vf -hf already, flipping the video orientation.

Sorry for the trouble.
