### ISSUE TITLE
Where do I find older Images?

### ISSUE THREAD

**Issue by fabianwindbacher** [google/aiyprojects-raspbian#338]
The current image 13/4/18 doesn't work for me as described in #310 (stuck at the 4 raspberries screen with an underscore below them ticking indefinitely". 
But I used the voice kit before on 3/3/18, and the image I used then worked for me. Is there a way to find this or another older image? Or does someone still have it and can provide it?

**Comment by drigz** [comment]
The previous image is available here: https://dl.google.com/dl/aiyprojects/aiyprojects-2018-02-21.img.xz

**Comment by mikernorton** [comment]
I'm helping teach a class in using the AIY voice product, and would like to reduce variables by asking everyone to install the same image before the class. Is there a generic way to check when images are released and what the image names are? There are no tags or releases for newer images on github, and you can't view the list of images on the dl.google.com link, you have to know in the name in advance.

**Comment by dmitriykovalev** [comment]
We are trying to make everything more organized, you can download old SD card images here https://github.com/google/aiyprojects-raspbian/releases
