### ISSUE TITLE
AIY Speech V2 LED Example

### ISSUE THREAD

**Issue by bewernick** [google/aiyprojects-raspbian#340]
It looks like with the new speech bonnet, the code to control the LEDs needs to be revised. I've gone through and tried to use the Vision LEDs example, however, there are a couple colors that are not behaving the same, noticeably 'red'. 

How can I port the _led code for the speech hat to use with the new arcade button led?

**Comment by dmitriykovalev** [comment]
That's been fixed in the latest code update, please take a look at `board.py`:

https://github.com/google/aiyprojects-raspbian/blob/5c74ce5154fe9ecdab5901e01b567d47fbdc068f/src/aiy/board.py#L286-L298
