### ISSUE TITLE
scripts/install-deps.sh is not present

### ISSUE THREAD

**Issue by noajshu** [google/aiyprojects-raspbian#343]
This file in mentioned by README.md and HACKING.md in the initial install steps. Was this file accidentally deleted, or is it no longer needed?

**Comment by drigz** [comment]
Is this the script you're referring to?

https://github.com/google/aiyprojects-raspbian/blob/aiyprojects/scripts/install-services.sh

EDIT: I realised you're referring to install-deps.sh and updated the issue.

**Comment by theilgaard** [comment]
It was removed in commit [98cb243a7cba2d7b084e3e1be23f60d3908fe8d4](https://github.com/google/aiyprojects-raspbian/commit/98cb243a7cba2d7b084e3e1be23f60d3908fe8d4) 

This now means there are no functioning installation instructions available.

**Comment by janvda** [comment]
I am having the same issue.  I want to upgrade my voicekit installation to the latest version but I am stuck now due to no functioning installation instructions.

**Comment by tobyweston** [comment]
dup of #378
