### ISSUE TITLE
Instructions for configuring AIY Vision HAT on Raspbian

### ISSUE THREAD

**Issue by anilmaddala** [google/aiyprojects-raspbian#344]
After going through the aiyprojects branch, I did not find clear documentation to setup the Vision HAT with Raspbian.

Could someone plese point to documentation in this regard?

**Comment by dmitriykovalev** [comment]
@anilmaddala Could you please clarify what kind of instruction you are looking for? We have all setup instructions for VisionKit at https://aiyprojects.withgoogle.com/vision right now.

**Comment by anilmaddala** [comment]
@dimitriykovalev https://aiyprojects.withgoogle.com/vision work just fine with the SD card/OS provided with the kit.

I am trying to configure the kit with a new reaspbian flashed OS. 

I found https://github.com/google/aiyprojects-raspbian/blob/aiyprojects/HACKING.md  which is to configure raspbian for Voice Hat.

Are there similar instructions for setting up Vision Hat on raspbian?

**Comment by dmitriykovalev** [comment]
Please check the latest version of `HACKING.md`.
