### ISSUE TITLE
Bounding_box  from aiy.vision.inference

### ISSUE THREAD

**Issue by Bstrum36** [google/aiyprojects-raspbian#354]
How would I get the bounding box of the detected face from CameraInference.

I see that annotator was invoked but have no idea how to st up the code to get the bounding box.

I have modified the camera trigger demo to return images with faces in them as detected but want to extract bounding box to save just the face.

Any ideas?

**Comment by dmitriykovalev** [comment]
Each face object has `bounding_box` attribute, check the example code: https://github.com/google/aiyprojects-raspbian/blob/e48363018e37b1fdc22d5ddc4b221db97c2cf47b/src/examples/vision/face_detection_camera.py#L80

**Comment by Bstrum36** [comment]
Thanks Dimitri,
I have played with aiyprojects-raspbian/src/examples/vision/face_detection_camera.py but it locks out camera.capture("filename") as the Vision Bonnet is running a real time video stream.  

I want to add getting the bounding box in the  face.camera.trigger example.

I have modified it to capture a face when detected, save it to a file,  and then use it as a label scale it and place the images in a grid.

What I wasnt is the bounding box here.

I am having difficulty understanding the relationship with annotator and the bounding box. Is bounding_ box a property?

with CameraInference(face_detection.model()) as inference:
            for result in inference.run():
                if len(face_detection.get_faces(result)) >= 1:
                    camera.capture('faces.jpg')

How do I get the bounding box before camera.capture ??

Is there a real API description for main vision libraries (aiy.vision.inference) .

More documentation would probably get a lot of people productive.

Thanks!

**Comment by dmitriykovalev** [comment]
In this example `face_detection.get_faces(result)` returns a list of detected faces.  You can access bounding boxes in the following way:

```
with CameraInference(face_detection.model()) as inference:
  for result in inference.run():
    faces = face_detection.get_faces(result)
    if len(faces) >= 1:
      for face in faces:
        print(face.bounding_box)  # <-- bounding box object 
      camera.capture('faces.jpg')
```

Please look at the source code and examples to check how everything works, that's the best way for now. We are going to provide better API documentation soon.

**Comment by Bstrum36** [comment]
Thanks!!!!  Got it going.  If you want a reviewer for the API I'd be glad to put in some time.

**Comment by Bstrum36** [comment]
Well almost got it.

The data type returned is float (?) Yes or no.

The data is x, y, height, width
 where (x,y) is the lower or upper left hand corner??

I want to pass the data to image.crop(x,y,height width) to extract the recognized face.
Can you define what x and y are giving me so I can specify the crop.

I'm probably being dense here.

**Comment by dmitriykovalev** [comment]
That's correct, bounding box is (x, y, w, h) tuple of integer numbers, coordinate system origin is at top-left corner.  We run inference on image coming from the sensor, you can access its width as `result.width` and height as `result.height`. If you want to save image which has different size (e.g. downscaled or upscaled) you need to recalculate coordinates of bounding box, for example:

```
x = int(your_width  * (face.bounding_box[0] / result.width))
y = int(your_height * (face.bounding_box[1] / result.height))
w = int(your_width  * (face.bounding_box[2] / result.width))
h = int(your_height * (face.bounding_box[3] / result.height))
```

**Comment by Bstrum36** [comment]
Now I got it
 
My issue was not understanding image.crop((x,y, x+width,y+height))  seems to crop out the bounding box!

**Comment by dmitriykovalev** [comment]
Perfect! Closing this issue.
