### ISSUE TITLE
google-api-core 0.1.4 has requirement requests<3.0.0dev,>=2.18.0

### ISSUE THREAD

**Issue by mpember** [google/aiyprojects-raspbian#355]
Since one of my [SDK-related questions](https://github.com/googlesamples/assistant-sdk-python/issues/132) was closed and it suggested that there was an update, I tried performing an update.

I pulled down the latest code from the git branch and when executing install-deps.sh, the following error appears:
**google-api-core 0.1.4 has requirement requests<3.0.0dev,>=2.18.0, but you'll have requests 2.14.2 which is incompatible.**

**Comment by drigz** [comment]
The latest code no longer includes install-deps.sh - could you check that you're using the latest code in the aiyprojects branch?

Unfortunately HACKING.md wasn't updated consistently in recent releases, so we can't point to any instructions on how to update to the latest code - the easiest way is to download the latest SD card image from the AIY website, but of course that means starting from scratch.

You could try using `env/bin/pip install requests==2.18.4` and then `cd src && ../env/bin/pip install .` (assuming you're using a virtualenv).

**Comment by ndmax** [comment]
> The latest code no longer includes install-deps.sh

It appears to be included in the `scripts` director in the latest commit of the aiyprojects branch.

(And I'm receiving the same message...)

**Comment by dmitriykovalev** [comment]
There should be no any dependency issues on the latest SD card image.
