### ISSUE TITLE
Help running the AIY Project on my own Raspberry Pi 2+ 

### ISSUE THREAD

**Issue by luzer** [google/aiyprojects-raspbian#357]
i got the image running on my own Pi2, getting an error, looking for the vision bonnet (i dont have)

`Traceback (most recent call last): File "/opt/aiy/projects-python/src/aiy/drivers/_spicomm.py", line 91, in __init_ self._dev = open(SPICOMM_DEV, 'r+b', 0) FileNotFoundError: [Errno 2] No such file or directory: '/dev/vision_spicomm'`

**Comment by dmitriykovalev** [comment]
@luzer Could you please clarify, are you trying to run AIY examples without attaching VisionBonnet board to the Pi?

**Comment by dmitriykovalev** [comment]
Please reopen if you are still having problems.
