### ISSUE TITLE
aiyprojects.withgoogle.com does not handle responsiveness correctly - hidden text

### ISSUE THREAD

**Issue by methodbox** [google/aiyprojects-raspbian#360]
https://aiyprojects.withgoogle.com/voice/#google-assistant
I'm using this on Chrome 65.0.3325.181 on macOS 10.13.4.

When viewing this page under about 1690px wide text starts to get cut off - for example

```/home/pi/AIY-projects-python/checkpoints/check_audio.py```
<img width="683" alt="screen shot 2018-05-07 at 8 48 03 pm" src="https://user-images.githubusercontent.com/12660440/39733358-fc1f6718-5237-11e8-9109-14d288b5427e.png">
I noticed this while doing the setup on my AIY Voice Kit.

Other text appears to wrap correctly when resizing the browser window.

It looks like this is probably due to the ```<pre>``` take used to wrap the ```<code>``` tag for styling - I don't have to tell you, since you're Google, but pre ignores CSS.
<img width="1294" alt="screen shot 2018-05-07 at 8 49 12 pm" src="https://user-images.githubusercontent.com/12660440/39733392-22be6bee-5238-11e8-996b-297403195629.png">

Removing the tag via browser inspector rendered the text exactly the same but with responsiveness.
<img width="1199" alt="screen shot 2018-05-07 at 8 50 08 pm" src="https://user-images.githubusercontent.com/12660440/39733429-4830ba26-5238-11e8-9b25-9a12fce64c5d.png">

**Comment by PeterMalkin** [comment]
Awesome! THank you so much for reporting this. Will fix soon
