### ISSUE TITLE
WiFi problems and VisionBonnet doesn't go into pairing mode

### ISSUE THREAD

**Issue by ghost** [google/aiyprojects-raspbian#362]
When I press the button on the VisionBonnet for 5 seconds or longer the led does not come on or start blinking as described in the instructions for connecting the AIY VisionKit to WiFi. The Vision Kit is fully assembled and seems  to be working.

I also cannot connect the AIY Vision kit to a Wifi network manually. Meaning I log into the Raspberry PI with Monitor, keyboard and Mouse attached. In the upper righthand corner where usually the WiFi connections are listed, when you click on the WiFI icon, are two red crosses display when I move my mouse over the icon it says "No interface found". 

So I have no way to connect the Vision Kit to my WiFi network.

**Comment by dmitriykovalev** [comment]
Could you please share `dmesg` command output after clicking on Wi-Fi icon?

**Comment by ghost** [comment]
„No interface detected“

**Comment by dmitriykovalev** [comment]
`dmesg` command prints kernel log, it's pretty long output.

**Comment by ghost** [comment]
Ok will come back to you on this traveling at the moment

**Comment by ghost** [comment]
I have just up-dated to the new firmware and it is now working correctly

**Comment by cansakirt** [comment]
@Hofi2010 How did you updated to the new firmware with no wifi connection?
