### ISSUE TITLE
Thermal model for Myriad2

### ISSUE THREAD

**Issue by kodukulav** [google/aiyprojects-raspbian#366]
Hi,

Can you provide me a thermal model to compute the junction temperature for Myriad2? Also, can you provide me the junction-to-board, board-to-ambient, junction-to-case, case-to-ambient resistances of Myriad2?

Thanks,
Venky

**Comment by dmitriykovalev** [comment]
Unfortunately, we cannot provide this. Try to contact [Intel/Movidius](https://www.movidius.com/myriad2) to get more info about Myriad2 chip.

**Comment by algila** [comment]
Appear to me that the temperature of the processors is quite high.  
Next week I will try to measure. 
Is it recommended to add a dissipator on Myriad2 and/or Raspberry chip ? 
I would use the kit for multiple hours  (8h / days)
