### ISSUE TITLE
No module name 'google.assistant.library'

### ISSUE THREAD

**Issue by theilgaard** [google/aiyprojects-raspbian#374]
When I try to follow hacking.md for the VoiceKit, in the following step 

```
cd ~/voice-recognizer-raspi
source env/bin/activate
python3 src/assistant_library_demo.py
```

I get the following error.

```
(env) pi@raspberrypi:~/voice-recognizer-raspi $ python3 src/assistant_library_demo.py
Traceback (most recent call last):
  File "src/assistant_library_demo.py", line 33, in <module>
    from google.assistant.library import Assistant
ImportError: No module named 'google.assistant.library'
```

**Comment by drigz** [comment]
HACKING.md hasn't been properly updates, so sorry about the confusion.

You should be able to resolve that issue with:

`pip3 install google-assistant-library==0.1.0`

**Comment by dmitriykovalev** [comment]
HACKING.md is pretty outdated, we have an updated version but it's not published yet. We got rid of virtualenv, so you don't need to use it now.

**Comment by theilgaard** [comment]
Having installed the requirements outside of the virtualenv, I get an Illegal instruction error.

```
pi@raspberrypi:~/voice-recognizer-raspi $ python3 src/assistant_library_demo.py
Illegal instruction
```

**Comment by dmitriykovalev** [comment]
@theilgaard You are probably trying to run demo on Pi Zero. There are two ways of using assistant: assistant library and assistant gRPC. Assistant library works only on Pi 3 and doesn't work on Pi Zero (it's not powerful enough) -- https://developers.google.com/assistant/sdk/overview. Assistant gRPC works on both Pi 3 and Pi Zero.
