### ISSUE TITLE
Vision Kit version 1.1 won't boot and or run demo with RPi3B+

### ISSUE THREAD

**Issue by ccwu000** [google/aiyprojects-raspbian#375]
Hardware that I'm using:
-Raspberry Pi 3 B+
-Vision Bonnet from version 1.1
-Corresponding flex cable in the correct orientation between RPi3B+ and Vision Bonnet
Software that I am running:
-aiyprojects-2018-04-13.img.xz
I ran upgrade, update, and reboot afterward.

I am having issue booting up the setup when the Vision Bonnet is attached.
However, it boots fine when is just connected with the flex cable.

Whenever I try to run demo examples, I get stuck at the _spicomm.py script.

File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 93, in __init__
    raise SpicommDevNotFoundError
aiy._drivers._spicomm.SpicommDevNotFoundError

Have anyone successfully ran the Vision Kit with Raspberry Pi 3 B+?

**Comment by dmitriykovalev** [comment]
VisionBonnet will not work on Pi 3B+ (it will be fine on Pi 3B though) because of hardware issue, please check details in #349.
