### ISSUE TITLE
install-deps.sh assumes that the user is `pi`

### ISSUE THREAD

**Issue by drigz** [google/aiyprojects-raspbian#38]
It would be better to look at the owner of the voice-recognizer-raspi directory to figure this out.

TBD: should the services also guess the appropriate user name? I'd say not, since edits there are unlikely to be committed by accident.

**Comment by axilleas** [comment]
@drigz fyi in https://github.com/google/aiyprojects-raspbian/pull/46/files I used `id -u $SUDO_USER` to find out the `uid` of the user that runs the script.
