### ISSUE TITLE
Trying to Use Pi Zero Voice Bonnet (pHAT) on Pi 3

### ISSUE THREAD

**Issue by PatrickUtz** [google/aiyprojects-raspbian#380]
After playing around with Voice Kit V2, I decided to upgrade to the Pi 3 in order to enable "Ok Google" and use other features. However, I am having trouble using the voice bonnet from the Pi zero kit on the Pi 3.  I have installed a clean version of Raspbian stretch and proceeded in following the instructions on HACKING.md (link below) to set up the Pi. Yet after I install the drivers and run `env/bin/python checkpoints/check_audio.py` , it returns `Failed to find the voiceHat soundcard. Refer to HACKING.md`. I assume this is due to the fact that the drivers are made for the old voice hat. Yet I am wondering if there is any way I can use the bonnet I have from the Pi zero  on the Pi 3. Any form of help would be greatly appreciated, thanks!

HACKING.md: https://github.com/google/aiyprojects-raspbian/blob/aiyprojects/HACKING.md

**Comment by rollynoel** [comment]
Instead of trying to update a fresh Raspian, just use the same version that came with the Pi zero
  (its @ [here](https://dl.google.com/dl/aiyprojects/aiyprojects-latest.img.xz)).

**Comment by dmitriykovalev** [comment]
Right, just download the latest [SD card image](https://github.com/google/aiyprojects-raspbian/releases) and run it on Pi 3 with Voice Kit v2. HACKING.md is pretty outdated, we are working on a new one.

**Comment by PatrickUtz** [comment]
Great! So I went ahead and used the latest SD card image however I have two issues. First, the volume coming out of the speaker is significantly lower than when it was hooked up to the pi zero (I have to have it set to at least 70 to hear anything). Second, the assistant_demo_library.py runs however the hotword "Ok Google" does not work and when I go to exit the program using ctrl+c nothing happens. Let me know what I should do, thanks!

**Comment by rollynoel** [comment]
I'm trying to get AIY Voice 2 running on a RPi3B+, and am running in to problems also ( #381 ).
I think there's some kind of deadlock in the calls to sound support.
The only one I've found works well is assistant_grpc_demo.py, & it only works with a button push.
Ctrl+z, or x, or c usually work for me, then often I hear the first few seconds of the stuck audio.

**Comment by mindflash-ops** [comment]
I'm having the exact same issue with a RPi3B+.  I can't seem to get it to work consistently, the microphone is completely broken and the button press only works once usually.  Any subsequent attempt fails.

**Comment by manoj7410** [comment]
@PatrickUtz 
Try to run the following commands:

echo "default-sample-rate = 48000" > ~/.config/pulse/daemon.conf
sudo rm ~/.asoundrc
sudo rm /etc/asound.conf

Then reboot and try assistant library demo on.
