### ISSUE TITLE
aiy.audio.play_audio, & aiy.audio.say calls often block on AIY Voice 2 with a RPI3B+

### ISSUE THREAD

**Issue by rollynoel** [google/aiyprojects-raspbian#381]
Task Manager shows pulseaudio consuming up to 42% of the cpu time forever, and no sound comes out.
If I run my app from the Thonny IDE, & hit the Interrupt/Reset button, after several seconds I hear a couple seconds of the start of the audio, as a sort of dying gasp.

**Comment by rollynoel** [comment]
It gets stuck in /opt/aiy/projects-python/src/aiy/_drivers/_player.py, line 52 (in play_bytes, in the call aplay.stdin.write(audio_bytes).

**Comment by dmitriykovalev** [comment]
Thank you for reporting this! Could you attach a minimalistic python example code which consumes a lot of CPU on your system?

**Comment by rollynoel** [comment]
All I need to do is to run the unaltered assistant_library_with_local_commands_demo.py, tell it "OK Google, ip address", & the described situation occurs on my RPI3B+.

**Comment by firechen** [comment]
So do I. My current working environment is AIY voice kit version 2.0 and Raspberry Pi 3 model B. Grpc assistant demo and cloud speech demo work well, but google assistant library demos do not work. It seems that there is some kind of deadlock, which runs out of CPU resources.

**Comment by rollynoel** [comment]
I emailed more or less the following to Google AIY support. If you can suggest something I might try, I'm game.

"After many days of trying to get a handle on this problem, I'm at a standstill.
The pulseaudio server starts consuming up to 40% of the cpu, and a call to aplay gets stuck, & won't return.
I've tried various strategies to prevent the aplay call from overburdening pulseaudio, to no avail.
I don't know what calls I can make to pulseaudio or aplay to unplug things.
Killing pulseaudio takes my application down (a segment fault, or somesuch?).
I see there's at least one other poor sap with a RPi 3 experiencing the same problem. Is it common to RPi 3s, or are we unique?"

**Comment by rollynoel** [comment]
Received the following advice from Google AIY support:
From a terminal window, enter:
echo autospawn = no >> ~/.config/pulse/client.conf
killall pulseaudio
echo "default-sample-rate = 48000" > ~/.config/pulse/daemon.conf
sudo rm ~/.asoundrc
sudo rm /etc/asound.conf

then reboot.

This is working wonderfully well for me (RPi 3B+, Google AIY Voice 2, assistant library demo, "hey Google" spoken.
