### ISSUE TITLE
AIY Project Vision Kit doesn't work

### ISSUE THREAD

**Issue by matthewycpang** [google/aiyprojects-raspbian#384]
Hi, 
I have tried the example for my Vision Kit, but it doesn't work. I have followed the guideline from:
https://blog.hackster.io/teething-troubles-for-the-new-aiy-projects-vision-kit-625ed4e9287a

$ cat /proc/cpuinfo | grep Revision
Revision	: 9000c1
$ sudo systemctl stop joy_detection_demo.service
$ sudo rmmod aiy_vision
rmmod: ERROR: Module aiy_vision is not currently loaded
$ sudo rmmod adc
rmmod: ERROR: Module aiy_adc is not currently loaded

Does it mean that there is error in booting the system? I have used the SD Image of 03/01/2018.

Many thanks for your help!

Matthew

**Comment by dmitriykovalev** [comment]
Could you please share which example code did you try to run and which error message did you get?

**Comment by dmitriykovalev** [comment]
Please reopen if you can provide requested details.

**Comment by ghost** [comment]
Hello,

I have exactly the same problem, do you have a solution?

Thank's
