### ISSUE TITLE
Using the Myriad for non NN Computer Vision?

### ISSUE THREAD

**Issue by metainf** [google/aiyprojects-raspbian#389]
I've searched around the internet if the vision bonnet is capable of other computer vision tasks, like computing optical flow and feature detection, but I haven't found any answers. Is it possible to use the Myriad on the vision bonnet without using a neural net, and if so, are there any resources about doing so?

**Comment by dmitriykovalev** [comment]
You can only run compute graphs via our APIs, there is no support for other Myriad features right now.
