### ISSUE TITLE
Install on fresh raspbian is no longer possible

### ISSUE THREAD

**Issue by Superdrac** [google/aiyprojects-raspbian#393]
The file install-deps.sh is not present anymore. 

And there isn't any instruction on how to install the last version.

Any instructions about how to install it now ?

**Comment by t1m0thyj** [comment]
I've been maintaining up-to-date instructions for how to install it on Raspbian here: https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=204865

Until Google provides documentation for how to install the latest version, my suggested workaround is to still use the `install-deps.sh` from the older version, along with a few other commands that are necessary. The commands listed below can be found in the forum post as well (they assume your installation directory is */home/pi/AIY-projects-python*, but you can substitute whatever folder you placed it in):
```
cd ~/AIY-projects-python
wget https://raw.githubusercontent.com/google/aiyprojects-raspbian/voicekit/scripts/install-deps.sh -nc -P scripts
chmod +x scripts/install-deps.sh
scripts/install-deps.sh
sudo scripts/install-services.sh
echo "$HOME/AIY-projects-python/src" > $HOME/AIY-projects-python/env/lib/python3.5/site-packages/aiy.pth
```

**Comment by dmitriykovalev** [comment]
We are working on instruction update and will try to release soon. There is no `install-deps.sh` and `virtualenv` anymore.

**Comment by Superdrac** [comment]
@t1m0thyj I sucessfully launched src/examples/voice/assistant_library_demo.py with your method. But I can only launch a few voice commands until, then google assistant just stop speaking.. (Maybe it's not related at all) I have a raspy 3 B+

@dmitriykovalev nice ! I will wait for this release then.

**Comment by xiapoy** [comment]
@dmitriykovalev this update is good news. When is the release planned? I faced the same issue as @Superdrac.

And the voice kit is great 💯 !

**Comment by bphermansson** [comment]
@Superdrac  How did you manage that? I fail at "ImportError: No module named 'aiy.voicehat'".

**Comment by jannewmarch** [comment]
The current HACKING.md says to run install-deps.sh and the github comment on scripts says this was removed two months ago. It also refers to aiy_voice_classic service which doesn't seem to exist. I've got an AIY Voice kit running alongside a raspbian on a 3B+ with as many changes as I can follow from HACKING.md. But I can see a mass of modules from lsmod in the google project that aren't loaded from following HACKING.md. Do I just modprobe them all? Or is there more to it? Would much appreciate an updated HACKING.md

Thanks, Jan

**Comment by dmitriykovalev** [comment]
@jannewmarch we are working on the update and new SD-card image release. Sorry for the inconsistency we have right now in the repo.

**Comment by anuraj1** [comment]
@dmitriykovalev Any update on the update for installing on clean Raspbian? My awesome project has been on hold for 2 months while waiting for an updated HACKING.md !

**Comment by nickdex** [comment]
@dmitriykovalev Hi, I'm waiting for the updated instructions as well

**Comment by dmitriykovalev** [comment]
Please check updated `HACKING.md` and [new SD card image](https://github.com/google/aiyprojects-raspbian/releases)!

**Comment by bphermansson** [comment]
Great news, thanks! Will try it out asap.

**Comment by dmitriykovalev** [comment]
Please open new issues regarding new `HACKING.md`, closing this one now.
