### ISSUE TITLE
Reference error on step 79: https://aiyprojects.withgoogle.com/vision/

### ISSUE THREAD

**Issue by hajilekwah** [google/aiyprojects-raspbian#396]
Just got my vision and voice kit last week from Target. Really digging the work being put forth into this! Nice tetris-themed piezo buzzer song guys! :)

Just wanted to point out a reference error on step 79 of the above landing page. A "micro" HDMI adapter is referenced here where "mini" is referenced elsewhere.

When I was gathering adapters galore last week, I made the error of getting a "micro" adapter. I don't think it was because of this step since "mini-HDMI adapter" is referenced under the "Gather Additional Items - Option 1" section.

Hope that it's ok that I posted this here, I'll probably send an email to: support-aiyprojects@google.com as well. Thanks again!

**Comment by dmitriykovalev** [comment]
Thank you very much, we'll fix it!
