### ISSUE TITLE
Refusing to change unit

### ISSUE THREAD

**Issue by Ouroboros4991** [google/aiyprojects-raspbian#398]
I've just installed the google AIY voice kit with a new account. it works but when I asked it to change it's units to celcius it responds like this:
 To get you that information, I'll need your permission. You can give it to me in the Google Assistant settings on your phone. Once that's done, ask me again!

I've enabled all the required activities so I don't know where the problem is

**Comment by manoj7410** [comment]
@Ouroboros4991 Can you try the steps given at : https://smartphones.gadgethacks.com/how-to/google-assistant-101-manage-account-permissions-0179314/

And allow assistant to access your account at https://myaccount.google.com/activitycontrols
