### ISSUE TITLE
Vision Kit long flex cable replacement

### ISSUE THREAD

**Issue by watchMe** [google/aiyprojects-raspbian#399]
I damaged the long flex cable connecting the camera to the vision bonnet. Does anyone know if the cables sold to connect the camera directly to the Raspberry Pi Zero are compatible or perhaps identical?

**Comment by dmitriykovalev** [comment]
https://www.adafruit.com/product/3157 — this cable should work to connect Pi camera module and Vision Bonnet.

**Comment by watchMe** [comment]
Thanks. I shall try one.

**Comment by watchMe** [comment]
It worked great. My Vision Kit is working again.

**Comment by dmitriykovalev** [comment]
Perfect!

**Comment by shoulih** [comment]
can I use the long flex cable (Bonnet cable) to connect the camera and pi zero directly?
