### ISSUE TITLE
AIY Vision Kit Setup Issues

### ISSUE THREAD

**Issue by robbinl1** [google/aiyprojects-raspbian#401]
My AIY Vision Kit has a few issues:

First, on startup, I don't always get the beep. When installing updates, I didn't get the beep, only the LED, but after that I heard the beep on two different boots (out of maybe ten), so I don't believe this to be an issue with the buzzer.

Additionally, I cannot get the kit to go into pairing mode.

After these issues, I decided to hook it up to a monitor and keyboard, but the keyboard won't work with the kit and boot doesn't seem to complete; the monitor shows the initial raspberry image and maybe a few lines of boot text (not consistently), then goes black. The keyboard itself shouldn't be an issue, it works fine with another Pi I have used it with. On one boot that beeped, the Pi gave me a message that said (paraphrasing) enabling ssh was unsafe because the default username and password had not been changed. Since the keyboard won't work, I couldn't leave this message.

**Comment by dmitriykovalev** [comment]
Can you please confirm that you are using wall power adapter?  E.g. something like https://www.adafruit.com/product/1995

**Comment by robbinl1** [comment]
Yes, I am using a 5V/2.4A wall adapter.

**Comment by dmitriykovalev** [comment]
I see. Do you still have this situation: "the monitor shows the initial raspberry image and maybe a few lines of boot text (not consistently), then goes black"? It means that Pi probably cannot boot. Did you try to re-flash SD card using our latest SD card image from https://github.com/google/aiyprojects-raspbian/releases ? Does it print any error messages before going black?

**Comment by robbinl1** [comment]
I still have this issue. I see no error messages, and have tried refreshing
the sd with no changes.

**Comment by dmitriykovalev** [comment]
That's very strange. Can you try to flash original Raspberry Pi image from https://www.raspberrypi.org/downloads/ and verify it can boot normally, so you can use your keyboard/mouse? Can you also check the temperature of Pi/VisionBonnet, i.e. how hot they are when powered?

**Comment by putifar** [comment]
I have exatly the same problem. I'm using a 2.5A power supply. Both Pi/VisionBonnet get very hot when powered on for a while, around 50 to 60 °C.

**Comment by dmitriykovalev** [comment]
@putifar Have it worked before? Did you try to connect monitor, keyboard, and mouse and check any logs?

**Comment by putifar** [comment]
Hi,

monitor, keyboard, and mouse are connected. That's how i know the screen goes black. I get the rainbow splash screen, then a small rasbian in the top left corner (sometimes it shows starting processes, sometimes it continues without), then a welcome to rasbian desktop splash screen, then the screen goes black and does not recover. The privacy led turn on after a while. I cannot ssh to the device or do anything with the keyboard/mouse/monitor as the rpi is frozen.

I've been reflashing the SD card several times hoping I would get any further. I once got a bit further in the boot process, I got into the desktop. But the joy demo had not started. At that time I could config the local wifi. That one time I got also ssh to the rpi. Then I tried to start the object recognition demo and it froze again. 

These are the possible issues I'm considering:
Faulty hardware. Either the pi zero or the vision bonnet is bad?

I have the impression the rpi is not powerfull enough to run the rasbian desktop and it chokes. Would it be a good idea to use a normal rpi to test the vision bonnet? 

Another possible cause I suspect is that the sd card does not get flashed properly. I'm using a windows 10 laptop with build in SD card reader and etcher to flash <aiyprojects-2018-04-13.img.xz>.

**Comment by putifar** [comment]
@dmitriykovalev 
I finaly got it working!
I have been testing, the last few days, in the attic where the wifi signal is very weak. Perhaps the pi zero w was consuming to much power to try to make the wifi connection and crashed?
Now i went downstairs, closer to the wifi router. I do not have a screen downstairs, but the pi zero now boots and i was able to connect with ssh.
While connected via ssh i could trouble shoot and discovered that there was a cabling error. After that i got a kernal ooops and ran your command from issue #337 : 
echo over_voltage=4 | sudo tee -a /boot/config.txt && sudo shutdown -r now
After reboot everything works fine, Thanks!!

**Comment by dmitriykovalev** [comment]
@putifar Perfect, I'm glad it works now!

**Comment by dmitriykovalev** [comment]
@robbinl1 are you still having issues with your board? Did you try boot with original Raspbian image?

**Comment by dmitriykovalev** [comment]
Please reopen if you still having problems.

**Comment by mikwaymes** [comment]
Hello,
I have exactly the same issue!
Although my pi has not been able to load the desktop at all. Exactly the same symptoms as above.  

The joy detector sometimes (1/10) works when not connected to the monitor or peripherals. Seems to get very hot. And when connected to a monitor, it only loads in the beginning, startup boot sequence, no errors, sometimes I get the welcome screen, and then just black. 

Tried various power adapters. Now using 3.0A reflashed and tried with 3 different SD cards. Same issue. 

The pi does however load up with a clean raspbian image. 

And suggestions please let me know.

**Comment by dmitriykovalev** [comment]
@mikwaymes You can try the fix from #337:

```
echo over_voltage=4 | sudo tee -a /boot/config.txt && sudo shutdown -r now
```

Let us know if that helps!

**Comment by mikwaymes** [comment]
@dmitriykovalev There is no way to ssh or open terminal because the pi never boots up with a monitor. Is there any way around this?

i have tried unplugging the camera flex cable and booting, I have reflashed multiple times.
the joy detector seems to work for a bit (10 min then freezes) without a monitor or peripherals. but soon as there is a monitor, it just hangs.

**Comment by dmitriykovalev** [comment]
You can try to plugin SD card to laptop/desktop computer and then manually edit file `config.txt` on the mounted volume (should happen automatically). Just add `over_voltage=4` line at the end.

**Comment by maylownaise** [comment]
@robbinl1 Hi. Did you ever get your keyboard/mouse to work? I have the same issue with 2 different sets.

**Comment by rangodjango** [comment]
hi there, I am new to raspi. I have similar problem related with mouse and keyboard connected with AIY Vision Kit. Current AIY Vision kit version being used is v1.1 and so far,it able to boot without any tone heard and shows desktop icons but the keyboard and mouse unable to function although they are connected to the USB hub.It turns to black screen after 5 minutes its booted. How can I troubleshoot this? Thanks.

**Comment by manoj7410** [comment]
@rangodjango Have you installed the latest sdcard image ? Latest sdcard image can be downloaded from : https://github.com/google/aiyprojects-raspbian/releases/tag/v20180803

And please make sure that your are using at least 2.1amp of power adaptor to boot the kit.

**Comment by rangodjango** [comment]
@manoj7410 @dmitriykovalev I have a question, let's consider that I already install the latest image on AIY Vision Kit v1.1 and, both keyboard and mouse still not functioning, what action can I take to overcome this, if this happened? Thanks.

**Comment by dmitriykovalev** [comment]
@rangodjango Mouse and keyboard should work normally with any SD card image. Please make sure to use good power supply as @manoj7410 already suggested.

**Comment by putifar** [comment]
In my case i got everything working by using a better power supply. It
worked with a 2A power supply when close to the wifi router and no
keyboard/mouse/screen connected. But when connecting mouse/keyboard/screen
it needed a more powerfull powersupply, I used a 3.5A  and moved closer to
the wifi router and everything worked fine.

Op wo 19 sep. 2018 om 04:57 schreef Dmitriy Kovalev <
notifications@github.com>:

**Comment by rangodjango** [comment]
> You can try to plugin SD card to laptop/desktop computer and then manually edit file `config.txt` on the mounted volume (should happen automatically). Just add `over_voltage=4` line at the end.

I did try to modify config.txt by adding the said lines. Once I change it and turn on the vision kit, it seems no change at all, keyboard & mouse can't be detected. But, the desktop icons and joy detector still working since the joy LEDs functioning.

**Comment by rangodjango** [comment]
nevermind..it can detect both keyboard & mouse now. Thanks for help @dmitriykovalev  @putifar

**Comment by MapAfficionado** [comment]
> @putifar Thanks for comment. I seem to have exact same problem but would appreciate more clarity and/or help from anyone.

Most USB power supplies are 5V and 2.1A output. If you used 3.5A power supply, wouldn't that damage Raspberry Pi Zero W as it would have higher than 5V input to it? I do have a "Universal AC/DC Adapter [https://www.rhino-tek.com/products/example-pst-3000mfu-12-volt-dc-3000ma-power-adapter-with-multiple-dc-outputs-dc-plugs](url) but am hesitant to use it. Could you tell me which power supply did you use? Would that be available on Amazon?

2) I am using powered USB hub, keyboard and mouse configuration for AIY Vision Kit. Does this powered USB hub need to an "OTG" USB hub or a regular one will do? Currently this USB hub is powered with an AC adapter with an output of 5vdc 1A. Is this adequate for this Vision kit configuration? 

Currently, RPi Zero is separately powered with another adapter [https://www.amazon.com/gp/product/B0719SX3GC/ref=oh_aui_detailpage_o01_s00?ie=UTF8&psc=1](url) at 5V 2.5A

3) If the AIY Vision kit is (and the RPi Zero W) not using WiFi capability, why would it need to be closer to the router for better signal? (just curious, though I can be very close to it)

Please pardon me but I am a newbie at programming, Linux, RPi as well as electrical anything so I would appreciate a 'basic' response and thanks in advance.

**Comment by ibrunoes** [comment]
pi@ibruno:~/AIY-projects-python/src/examples/vision $ ./image_classification_camera.py
mmal: mmal_vc_component_create: failed to create component 'vc.ril.camera' (1:ENOMEM)
mmal: mmal_component_create_core: could not create component 'vc.ril.camera' (1)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 456, in _init_camera
    self._camera = mo.MMALCamera()
  File "/usr/lib/python3/dist-packages/picamera/mmalobj.py", line 2279, in __init__
    super(MMALCamera, self).__init__()
  File "/usr/lib/python3/dist-packages/picamera/mmalobj.py", line 633, in __init__
    prefix="Failed to create MMAL component %s" % self.component_type)
  File "/usr/lib/python3/dist-packages/picamera/exc.py", line 184, in mmal_check
    raise PiCameraMMALError(status, prefix)
picamera.exc.PiCameraMMALError: Failed to create MMAL component b'vc.ril.camera': Out of memory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./image_classification_camera.py", line 64, in <module>
    main()
  File "./image_classification_camera.py", line 54, in main
    with PiCamera(sensor_mode=4, framerate=30) as camera, \
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 431, in __init__
    self._init_camera(camera_num, stereo_mode, stereo_decimate)
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 460, in _init_camera
    "Camera is not enabled. Try running 'sudo raspi-config' "
picamera.exc.PiCameraError: Camera is not enabled. Try running 'sudo raspi-config' and ensure that the camera has been enabled.

**Comment by ibrunoes** [comment]
lo he probado todo, por lo menos eso creo, la camara la tengo activada desde el raspi.config
no se que hacer mas, por favor ayuda, gracias

**Comment by ibrunoes** [comment]
Hola, alguien ha leido este ultimo problema?
o debo ponerlo en otro post?
