### ISSUE TITLE
Vision Kit Step 74: Let it boot up

### ISSUE THREAD

**Issue by pblin** [google/aiyprojects-raspbian#405]
Don't see any green LED light flashing on the Raspberry Pi board after plugging in the power.

**Comment by dmitriykovalev** [comment]
Can you check if JoyDemo is working (step 75)? E.g. it should beep after the boot.

**Comment by pblin** [comment]
it seems that the raspberry board might be defective? there was no beep even the boards get hot after I plugged in the power cable.

**Comment by dmitriykovalev** [comment]
Did you try to connect HDMI monitor to see what's happening on the screen?

**Comment by manoj7410** [comment]
@pblin Did you try to boot the PI itself (Remove the Bonnet and then try to boot the PI)? Is it booting ?

**Comment by dmitriykovalev** [comment]
Let us know if problem still exits.
