### ISSUE TITLE
Microphone static and low audio on 'new' v1 kit

### ISSUE THREAD

**Issue by ShapeShifter499** [google/aiyprojects-raspbian#407]
I'm getting static and a faint whisper of my voice trying to test with a v1 kit I just got from arrow.com Any ideas or fixes? I used a Raspberry Pi 3B+ and I'm testing using /home/pi/AIY-projects-python/checkpoints/check_audio.py with the aiyprojects-2018-04-13 image.

I also posted about it on reddit
https://www.reddit.com/r/aiyprojects/comments/8qs9ms/microphone_not_working/

and sent an email to 
support-aiyprojects@google.com

**Comment by ShapeShifter499** [comment]
I think I need a new microphone.  No one has gotten back to me via email.  Can someone help out here?

I should add that the rest of my kit appears to work fine. I was able to push and hold the small on board button to get bluetooth pairing working for the Android AIY app and the bigger included button lit up.

**Comment by ShapeShifter499** [comment]
@dmitriykovalev I hope it's ok I'm highlighting you here. You seem to have some connection with the project and were one of the more recent to respond to issues.

**Comment by dmitriykovalev** [comment]
Did you get any reply from support-aiyprojects@google.com? Can you still here you voice after recording or that's just a pure noise?

**Comment by manoj7410** [comment]
@ShapeShifter499 Did you use the email ID : Gero3977@gmail.com or some other email id ? 
Can you please share the email ID that you used to communicate with support-aiyprojects@google.com ?

**Comment by manoj7410** [comment]
@ShapeShifter499 Can you please try this ? 

- Start the assistant_grpc_demo.py
- Tell this to your Assistant : "Increase the volume to 100%"
- Now run the command, "alsamixer" on the terminal and use upper arrow key to maximize the volume. Please share what happens.

**Comment by ShapeShifter499** [comment]
@dmitriykovalev @manoj7410 I have yet to receive a reply via email, gero3977@failserv.com is the email I used to contact support-aiyprojects@google.com      I'll get a recording later today and post that file here.   The included speaker works great, nice and loud.

**Comment by manoj7410** [comment]
This is what we received:

"** Message not delivered ** 

There was a problem delivering your message to gero3977@failserv.com. See the technical details below. 

Learn more here: https://support.google.com/mail/answer/7720 

The response was: 

The recipient server did not accept our requests to connect. Learn more at https://support.google.com/mail/answer/7720 
[mail.failserv.com. 162.218.233.128: timed out] "

Sorry for the inconvenience.  Please try below steps as mentioned in my above comments:

- Start the assistant_grpc_demo.py
- Tell this to your Assistant : "Increase the volume to 100%"
- Now run the command, "alsamixer" on the terminal and use upper arrow key to maximize the volume. Please share what happens.

**Comment by ShapeShifter499** [comment]
@manoj7410  @dmitriykovalev  Weird, I had that email linked to Google Apps.  I meant to send it as gero3977@gmail.com anyways, which is my normal email account.

I ran the script, told the assistant to "Increase the volume to 100%" and then bumped up the playback and capture to 100% in "alsamixer".    

Attached in the zip file is a recording using "arecord test.wav" of me trying to say "Hello, testing 123, hello google developers" after I increased the volume. 

[test.wav.zip](https://github.com/google/aiyprojects-raspbian/files/2118415/test.wav.zip)

Below is the log from "assistant_grpc_demo.py"  It didn't seem to hear me after a few button presses. 

```
pi@raspberrypi:~/AIY-projects-python $ src/examples/voice/assistant_grpc_demo.py
/opt/aiy/projects-python/src/aiy/_drivers/_led.py:51: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(channel, GPIO.OUT)
[2018-06-20 07:52:05,795] INFO:recorder:started recording
Press the button and speak
Listening...
[2018-06-20 07:54:22,135] INFO:speech:event_type: 1
Press the button and speak
Listening...
[2018-06-20 07:55:05,186] INFO:speech:event_type: 1
Press the button and speak
Listening...
[2018-06-20 08:01:50,775] INFO:speech:event_type: 1
Press the button and speak
Listening...
[2018-06-20 08:02:04,186] INFO:speech:event_type: 1
Press the button and speak
Listening...
[2018-06-20 08:02:07,253] INFO:speech:transcript: increase
[2018-06-20 08:02:07,419] INFO:speech:transcript: increase the
[2018-06-20 08:02:07,799] INFO:speech:transcript: increase  the
[2018-06-20 08:02:07,814] INFO:speech:transcript: increase  the volume
[2018-06-20 08:02:07,982] INFO:speech:transcript: increase the  volume to
[2018-06-20 08:02:08,164] INFO:speech:transcript: increase the  volume two
[2018-06-20 08:02:08,346] INFO:speech:transcript: increase the  volume to one
[2018-06-20 08:02:08,360] INFO:speech:transcript: increase the  volume to 100
[2018-06-20 08:02:08,389] INFO:speech:transcript: increase the volume  to 100
[2018-06-20 08:02:08,731] INFO:speech:transcript: increase the volume  to 100%
[2018-06-20 08:02:08,753] INFO:speech:transcript: increase the volume to  100%
[2018-06-20 08:02:09,281] INFO:speech:transcript: increase the volume to 100%
[2018-06-20 08:02:10,943] INFO:speech:event_type: 1
[2018-06-20 08:02:10,998] INFO:speech:transcript: increase the volume to 100%
You said " increase the volume to 100% "
Press the button and speak
Listening...
[2018-06-20 08:03:05,155] INFO:speech:transcript: testing 1
[2018-06-20 08:03:05,273] INFO:speech:transcript: testing one two
[2018-06-20 08:03:05,463] INFO:speech:transcript: testing 1 2 3
[2018-06-20 08:03:05,636] INFO:speech:transcript: testing  1 2 3
[2018-06-20 08:03:06,053] INFO:speech:transcript: testing 1 2 3
[2018-06-20 08:03:07,556] INFO:speech:event_type: 1
[2018-06-20 08:03:07,573] INFO:speech:transcript: testing 1 2 3
You said " testing 1 2 3 "
Press the button and speak
```

**Comment by manoj7410** [comment]
@ShapeShifter499 This seems like a bad hardware. 

You would have received an email from AIY support team on your   ID : gero3977@gmail.com

Kindly respond there directly with the requested information.

Thanks

**Comment by ShapeShifter499** [comment]
@manoj7410 In the email it asks for the "invoice's photo"   do you guys want a photo of me and my face?

**Comment by ShapeShifter499** [comment]
@manoj7410 Ok I sent a followup email with all the info.

**Comment by dmitriykovalev** [comment]
Perfect, looks like the problem is solved!

**Comment by ShapeShifter499** [comment]
I hope so!  If the replacement microphone doesn't work any better then the one I currently have I give up.

Thank you for the help @dmitriykovalev @manoj7410

**Comment by ShapeShifter499** [comment]
@dmitriykovalev @manoj7410 I'm giving one last update on this. I just received my replacement Microphone a few hours ago as of writing and this time everything works great!  I even played a few sessions of "lucky trivia" with my mom using the Assistant mode.  I currently see no further issues at least with the hardware.

Thank you guys for all the help.

**Comment by dmitriykovalev** [comment]
@ShapeShifter499 Thanks for update! Let us know if you find any other issues!

**Comment by dkarma** [comment]
I have this same issue.  When I run arecord -l it shows no capture devices!

dmitriykovalev ...are you google ppl?
Can someone from the AIY team please contact me at dwn4tupac@yahoo.com so I can get a replacement please?

Right now I'm supremely disappointed in this entire project.  Google really dropped the ball with this AIY stuff...esp w/ the Pi 3 B+.  IMO they should be ashamed their stuff is this broken across the board.
Their own instructions don't work either in the AIY book that comes w/ the kit OR the website: install-deps.sh is completely missing from their repo!

I mean this is really bad...

**Comment by manoj7410** [comment]
@dkarma ,
I see that you have already contacted support-aiyprojects@google.com for a replacement. Don't worry, your issue will be resolved.
