### ISSUE TITLE
Accessing Myriad Development Kit in Vision Bonnet

### ISSUE THREAD

**Issue by mikeliao97** [google/aiyprojects-raspbian#410]
Hi, very cool project! Thanks for the hardwork.

So I am aware that the Vision Bonnet is a Movidius 2450, and I am aware that Movidius has a Myriad Development Kit. Do you know if its possible to use the SDK? or follow tutorials using the Intel Compute Stick(which also has a Movidius 2450)?

A beginner question, thanks!

https://uploads.movidius.com/1463156689-2016-04-29_VPU_ProductBrief.pdf

**Comment by dmitriykovalev** [comment]
Hi Mike! We do not expose any Myriad internals because of huge complexity. We only have Python API to run compute graphs on Myriad. Intel Compute Stick is a different product, so there is no way to use our example code there.

**Comment by liyoung1992** [comment]
@dmitriykovalev Hi，I read your  article today [aiy-vision-kit](https://cogint.ai/custom-vision-training-on-the-aiy-vision-kit/),and I am very admire you ！now，I begin to compile own model，and  I meet many difficulties！Do you have any practice in compile own model！For example ：[issues/411](https://github.com/google/aiyprojects-raspbian/issues/411)
Thanks!

**Comment by mikeliao97** [comment]
thanks!

**Comment by elyas20** [comment]
Hi @dmitriykovalev,
I need to use myriad for traditional image processing and computer vision routines. Is there any dev board that contain the myriad that I can purchase ?
Thanks.

**Comment by dmitriykovalev** [comment]
@elyas20 You should contact https://www.movidius.com/ regarding Myriad dev boards.

**Comment by phaseOne** [comment]
Hey @dmitriykovalev, I'd love to hack around with the Movidius SDK. I can arrange an NDA if needed.

**Comment by dmitriykovalev** [comment]
@phaseOne You still need to contact https://www.movidius.com/ for that. You can also send detailed email to our support team support-aiyprojects@google.com.
