### ISSUE TITLE
calendar Access 

### ISSUE THREAD

**Issue by absentdream** [google/aiyprojects-raspbian#419]
ok... missing something here :) how do i let it have permission for calendar ? much tho i love the prase "before i can do that i need your permission" :)

**Comment by Smanar** [comment]
2 possibilities, I don't remeber.
1 - https://developers.google.com/assistant/sdk/guides/activity-controls
2 - on google assistant app, you have same kind of "share private information" to enable.

**Comment by absentdream** [comment]
Got it thanks :)
