### ISSUE TITLE
Voice demo crashing when trying to speak

### ISSUE THREAD

**Issue by mc-coi** [google/aiyprojects-raspbian#423]
I have the Voice 2.0 and everything is installed, speakers are working when I do the sound check (it plays and records and plays my voice). However, when I run the assistant_grpc demo, it listens and determines what I said, then it crashes. I have tried old and new versions of the the code.

I have included a screen shot of the error. Please help, I'm SOOOO close
<img width="903" alt="screen shot 2018-06-28 at 5 19 29 pm" src="https://user-images.githubusercontent.com/26398799/42061746-29cca984-7af9-11e8-9c17-23306a2de231.png">

**Comment by manoj7410** [comment]
@mc-coi Have you tried with the latest software image which is available at : https://aiyprojects.withgoogle.com/help/#updating-your-sd-card

**Comment by mc-coi** [comment]
I have. I updated the image and pulled the newest AIY demos. Still having the same issues.

**Comment by manoj7410** [comment]
@mc-coi Did you try with more sentences (Like, "Hello", "What is your name")? 

Does it crash immediately after printing the sentence that you say or it waits for few seconds before crashing ?

And can you make sure that your internet connection is not slow ?

**Comment by dmitriykovalev** [comment]
@mc-coi SD card image has everything you need to run examples, no need to pull AIY demos separately. Looks like you have a mix of different source code versions. Let us know if problem still exits.
