### ISSUE TITLE
Setup Issue with new install of Voice Assitant

### ISSUE THREAD

**Issue by briankmcm** [google/aiyprojects-raspbian#429]
I recently acquired Voice Kit. I realized it was version 1.0. Went through the set up got through to Chapter 5 step 13 when I ran into an issue. When I enter as instructed "src/assistant_library_demo.py" in the development terminal it returns the following;
"bash: src/assistant_library_demo.py: No such file or directory" 
I went to the folder where that code is located and tried running it from there and got an ImportError.
Need help.
Thank you Brian

**Comment by tiancaipipi110** [comment]
the files are locate at /src/examples/voice now.

**Comment by briankmcm** [comment]
Just to make sure I understand, I need to launch the development terminal and enter;
"src/examples/voice/assistant_library_demo.py" ? To continue with the setup process in the booklet?
Thank you for your guidance.

**Comment by dmitriykovalev** [comment]
@briankmcm Did you try to follow instructions at https://aiyprojects.withgoogle.com/voice-v1/ ?

**Comment by briankmcm** [comment]
I followed the instruction booklet that came with the kit.
Thanks,

**Comment by manoj7410** [comment]
@briankmcm 

Download the latest sdcard image from https://aiyprojects.withgoogle.com/help/#updating-your-sd-card and install it on your sdcard.

You can follow the instructions given at : https://aiyprojects.withgoogle.com/voice/#connect (These will work for Voice V1 as well) to make your assistant work.

**Comment by briankmcm** [comment]
Will give this a try.
Thank you!!
