### ISSUE TITLE
StatusCode Unauthenticated. Request had invalid authentication credentials

### ISSUE THREAD

**Issue by VR6Pete** [google/aiyprojects-raspbian#43]
After a period of random time, the service stops working and I have to restart the service to get it to start working again.

Screenshot of output attached below;

![bug](https://cloud.githubusercontent.com/assets/2682742/26116365/cdeefaf2-3a5a-11e7-919a-9bd560307daf.png)

Unsure what could be causing that. please let me know if you require any more information.

Thanks ,

Pete

**Comment by drigz** [comment]
Thanks for the report! Are you using the Assistant API or the Cloud Speech API?

How long is the period of time approximately? eg is it minutes or hours or days? We'll try to reproduce it here.

**Comment by VR6Pete** [comment]
Hi There @drigz I have using Assistant API. 

I would guess at ~ 1 hour - 2 hours I will be able to extract more approximate information when I take a look at it later.

Cheers

Pete

**Comment by drigz** [comment]
@VR6Pete, have you figured anything out about how to reproduce this?

I saw this two or three times while doing a demo a few days ago, but when I tried to reproduce it on the next day, I couldn't. The cube has been running about 24 hours and still works...

**Comment by VR6Pete** [comment]
That was the same with me but unfortunately it's not happened again since the bug report.
