### ISSUE TITLE
No module named aiy.assistant.grpc   No module named aiy.audio

### ISSUE THREAD

**Issue by tiancaipipi110** [google/aiyprojects-raspbian#430]
Google AIY voice installation went fine, testing sound passed. However when I try to run `python assisstant_grpc_demo.py`  it shows error   `No module named aiy.assistant.grpc`
when run `python cloud_speech_demo.py`   it shows error  `No module named aiy.audio`
Any idea why?

**Comment by slloyd88** [comment]
I get the same thing if I try to run the tests as root instead of pi

**Comment by manoj7410** [comment]
@slloyd88 That is because environment of root user is not setup as per the requirement. You can see the difference between environment of "root" and "pi" by running the command printenv (Once with root and then with pi).

**Comment by slloyd88** [comment]
Is there a way for me to setup root also?  I assume you mean that root needs all the INFINALITY_ environment keys set.  Since I used the image per the instructions at https://aiyprojects.withgoogle.com/voice/ I am not sure what else needs to be setup.

**Comment by dmitriykovalev** [comment]
@slloyd88 Could you please point to the instructions which require root usage?
