### ISSUE TITLE
Spicomm error testing compiled binary model (both default model and own model)

### ISSUE THREAD

**Issue by Aileenlingyu** [google/aiyprojects-raspbian#431]
Hi, I have successfully compiled my own model into binaryproto, I tried using test_run_model_on_bonnet.py to test it but received the following error:
aiy._drivers._spicomm_SpicommInternalError
StopCameraInference: Camera inference is not running
![1](https://user-images.githubusercontent.com/22608026/42584628-9fa1eb94-8501-11e8-8dac-c09d29693bab.jpg)
![2](https://user-images.githubusercontent.com/22608026/42584629-9fafcdb8-8501-11e8-91db-5736958f757f.jpg)
![3](https://user-images.githubusercontent.com/22608026/42584630-9fbce30e-8501-11e8-8bc6-b2edf407dca2.jpg)
![4](https://user-images.githubusercontent.com/22608026/42584631-9fcc9ff6-8501-11e8-8309-798b7e178e03.jpg)

I followed the instruction [here](https://github.com/google/aiyprojects-raspbian/issues/335) in issue #335 and updated my SD card image to the latest one, but the error is still there.

I also tried to test the built-in default graph in /opt/aiy/models/face_detection.binaryproto, without making any changes, and got the same error. Also if I test on the squeezenet_160res_5x5_0.75.binaryproto, same error message will show after printing out some inference result like below:
![img-1937](https://user-images.githubusercontent.com/22608026/42583792-b8c5226e-84ff-11e8-905e-f42510a07b56.jpg)

Could anyone please advise? Many thanks! 

By the way, I can run all the built-in demos without no error messages.

**Comment by ritwikbiswas** [comment]
What does your full call to `test_run_model_on_bonnet.py` look like?

**Comment by Aileenlingyu** [comment]
Hi @ritwikbiswas, I am using the following command to run:
python3 ~/AIY-projects-python/src/examples/vision/test_run_model_on_bonnet.py \
  --model_path ~/models/my-graph.binaryproto \
  --input_height 64 \
  --input_width 64

**Comment by ritwikbiswas** [comment]
What about your labels path? And your input and output layers?

Does your input heigh and width match that of your input heigh/width when you compiled the model?

**Comment by weiran-work** [comment]
@Aileenlingyu 
It seems like you are building a model with 64x64 input, I don't think this is a supported configuration for Vision Kit.
https://aiyprojects.withgoogle.com/vision/#makers-guide--tensorflow-model-compiler

**Comment by Aileenlingyu** [comment]
Hi @ritwikbiswas  , I am using a regression model rather than the classification, so I do not have labels. Yes the input height and width are exactly same as the values for compiling. Is it possible for me to use a regression model? Thanks much!

**Comment by Aileenlingyu** [comment]
Hi @weiranzhao , I found the following instruction [here](https://aiyprojects.withgoogle.com/vision/#constraints) suggesting that as long as the input size is a multiple of 8, it will be fine, 

> Model takes square RGB image and input image size must be a multiple of 8.
> Note: Vision Bonnet handles down-scaling, therefore, when doing inference, you can upload image that is larger than model's input image size. And inference image's size does not need to be a multiple of 8.

is that correct or not? Many thanks!

**Comment by weiran-work** [comment]
@Aileenlingyu That is like a general guideline. It also depends on the model structure you used and whether operator configuration is supported. The reason I'm concerned about using a 64x64 model input is that if your network is deep, there might be intermediate tensors that have size 2x2xdepth, and  if you use a 3x3 conv kernel on that input, Vision Kit can not handle that case.

This is also why there's a script to test_run your model.

**Comment by Aileenlingyu** [comment]
Hi @weiranzhao, I am using only 3 convolution layers as below, 
![graph_large_attrs_key _too_large_attrs limit_attr_size 1024 run](https://user-images.githubusercontent.com/22608026/42837289-abe52492-89cb-11e8-8d57-7e833e0bf9df.png)

I was wondering that, is there any other possible reason I may consider for my case, i.e., there is no error when compiling frozen pb into binaryproto, but getting spicomm error and camera no data error when testing the model?

Thanks a lot!

**Comment by weiran-work** [comment]
@Aileenlingyu Could you try to get rid of LRN during inference and try again? I don't think LRN is a supported operator.
https://aiyprojects.withgoogle.com/vision/#makers-guide--tensorflow-model-compiler

**Comment by Aileenlingyu** [comment]
Thanks much, will try!

**Comment by Aileenlingyu** [comment]
@weiranzhao , thank you for your advice! I removed the LRN layer and tried with a simple sub-network, and I am able to successfully pass the test script now.
