### ISSUE TITLE
json.decoder.JSONDecodeError Issue 

### ISSUE THREAD

**Issue by QuantumLimitsDesign** [google/aiyprojects-raspbian#444]
So im wokring of a RPi 2 and trying to run your voice aiy software and it all works fine untill i run this piece of code

 src/examples/voice/assistant_grpc_demo.py

and then i get this error

File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

not sure how to fix thanks

**Comment by dmitriykovalev** [comment]
Are you using the latest SD card image from https://github.com/google/aiyprojects-raspbian/releases?

**Comment by manoj7410** [comment]
@QuantumLimitsDesign Are you trying to run it on PI terminal or via SSH ?
