### ISSUE TITLE
Can I encourage "OK Google" to use a twenty four hour clock

### ISSUE THREAD

**Issue by DougieLawson** [google/aiyprojects-raspbian#445]
If I say "OK Google, what time is it?", she replies "7:58 Pee Emm".

I'd like her to reply with "19 58" as that's the format I prefer.

How can I configure AIY to use 24-hour clock (aka military time)?

**Comment by dmitriykovalev** [comment]
This is not actually related to AIY because we use [Assistant SDK](https://developers.google.com/assistant/sdk/) internally, you can probably try to ask [here](https://github.com/googlesamples/assistant-sdk-python/issues).

**Comment by DougieLawson** [comment]
Thank you.
