### ISSUE TITLE
Duplicate alert events

### ISSUE THREAD

**Issue by mpember** [google/aiyprojects-raspbian#449]
Whenever a timer or alarm is set, the following occurs when the timer / alarm goes off:

A **ON_ALERT_STARTED** event is followed by an immediate **ON_ALERT_FINISHED** event, followed by a second **ON_ALERT_STARTED** event.

A second **ON_ALERT_FINISHED** event is not triggered until you wake the assistant, to stop the alarm.

Is this expected?  Is this because the API generates multiple, redundant events?

**Comment by dmitriykovalev** [comment]
This issue probably should be reported to https://github.com/googlesamples/assistant-sdk-python/issues  We are actually using an old version (0.1.0) but going to upgrade soon.

**Comment by dmitriykovalev** [comment]
We use the latest Assistant Library in [the new SD card image](https://github.com/google/aiyprojects-raspbian/releases/tag/v20181116).
