### ISSUE TITLE
enable actions via config file

### ISSUE THREAD

**Issue by ensonic** [google/aiyprojects-raspbian#45]
We're gettting PRs for actions like:

- shutdown and reboot commands: https://github.com/google/aiyprojects-raspbian/pull/30
- hue lights: https://github.com/google/aiyprojects-raspbian/pull/33

Some of the actions need parameters (hue) and some actions are potentially dangerous, so that not everyone wants them. It would be nice to have a way to enable/disable them and also pass options for them. We would then split action.py into files under action/*.py and load them as enabled in the config file. Ideally we pass each plugin its config section to the constructor.

We can't keep using configargparse since that has no section support.
We would switch to ConfigParser to read the config. Then we can see the command-line arg defaults with the config file (so that the command line args can override config value). Unforunately the ConfigParser API does not allow to pass a section object around to constrain reading it. Maybe we just read the section on behalf of the plugin and pass it as a dict?

**Comment by VR6Pete** [comment]
Great idea

**Comment by sheridat** [comment]
Excellent - exactly what is needed to stop src/action.py becoming a nightmare.

**Comment by drigz** [comment]
Since the new direction of this project is to provide a support library (along with demos of how to use it) rather than a full-featured solution, I'm going to close this issue.
