### ISSUE TITLE
soundcard is not a first sound device

### ISSUE THREAD

**Issue by mra1984** [google/aiyprojects-raspbian#451]
I am trying to test my voicehat audio but getting the error your AIY sound card is not a first sound device.  It tells me to remove other sound drivers.  Please could someone help me to do this?
Thanks

**Comment by dmitriykovalev** [comment]
@mra1984  Which SD card image do you use? 

Can you also check what's inside `/boot/config.txt`? `dtparam=audio=on` line should be commented out.

**Comment by mra1984** [comment]
Thanks that did the trick.

**Comment by mra1984** [comment]
Fixed

**Comment by ayushmishr998** [comment]
HAT (V1) isntalled at index 2!
