### ISSUE TITLE
Question #voice - switch off

### ISSUE THREAD

**Issue by mra1984** [google/aiyprojects-raspbian#455]
(1) I have made an autoboot file so that I can plug in the AIY voice without the need for mouse/keyboard/screen etc - this works.  However, are there then issues with just switching the pi off by the button on my cable?  Can I get the voice device to poweroff safely?

**Comment by dmitriykovalev** [comment]
You can update your python code and implement something like this:

```
if recongnized_text == 'shutdown now':
    subprocess.check_output('sudo shutdown -h now')
```

Basically use special voice command to run shell command which shutdowns Pi.

**Comment by dmitriykovalev** [comment]
By the way, there is already an example file which does that: `assistant_library_with_local_commands_demo.py`
