### ISSUE TITLE
aiy-python-wheels: too many levels of symbolic links error during installation

### ISSUE THREAD

**Issue by jessecha** [google/aiyprojects-raspbian#457]
As the title suggests, when I try to install aiy-python-wheels, I get an dpkg error indicating too many levels of symbolic links.

**Comment by dmitriykovalev** [comment]
Can you please copy error message here?

**Comment by jessecha** [comment]
I ended up ditching the ubuntu mate installation attempt, and I do not have a copy of the error message.

**Comment by dmitriykovalev** [comment]
Oh, Ubuntu Mate, got it. That's an important information you should've put in the description.

**Comment by sagescolorado** [comment]
same issue -  i'm using Ubuntu made 16.04 on an rpi3

I get the same error every time I install anything now.

Error message:
Setting up aiy-python-wheels (1.0-0) ...
Failed to execute operation: Too many levels of symbolic links
dpkg: error processing package aiy-python-wheels (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 aiy-python-wheels

**Comment by dmitriykovalev** [comment]
`aiy-python-wheels` debian package is already fixed.
