### ISSUE TITLE
AIY Kits Release 2018-08-03 still doesn't support the leds on a Voice 2 kit

### ISSUE THREAD

**Issue by rollynoel** [google/aiyprojects-raspbian#458]
assistant_library_demo.py (for example) makes the calls to "status_ui.status('ready')"
  but no enlightenment occurs.
(I presume the fact that I'm running it on a RPi 3B+ isn't a factor).

**Comment by Jianan-Li** [comment]
Same here. Running on RPi 3B.

**Comment by dmitriykovalev** [comment]
That's a bug, status UI works for Voice HAT and doesn't work for Voice Bonnet, will be fixed in the next release.

**Comment by rollynoel** [comment]
This release does, however, fix the problem experienced by Voice 2 kit and Raspberry Pi 3B/3B+ as mentioned in [issue #400](https://github.com/google/aiyprojects-raspbian/issues/400).

**Comment by dmitriykovalev** [comment]
That's fixed in the new SD card [image release](https://github.com/google/aiyprojects-raspbian/releases/tag/v20181116). There is an API to get LED instance which works on all boards: https://github.com/google/aiyprojects-raspbian/blob/5c74ce5154fe9ecdab5901e01b567d47fbdc068f/src/aiy/board.py#L294
