### ISSUE TITLE
assistant_with_local_commands - option to modify wakeword? 

### ISSUE THREAD

**Issue by mra1984** [google/aiyprojects-raspbian#459]
this is a great file as I can boot and shutdown with only the google voice aiy kit.

it would be great if it could somehow work to modify the wakeword though. 

the only way to do it seems to be with the button press version of the code and using snowboy - I attempted this but couldn't get it to work.  Does anyone have any tutorial or plans to modify the python file 'with local commands'? 

I have made my own account on snowboy and a wakeword file but just don't know how to integrate this with the local commands file.

**Comment by dmitriykovalev** [comment]
Wakeword (or hotword) cannot be modified, you can get more details by asking developers of [Assistant Library](https://github.com/googlesamples/assistant-sdk-python/).
