### ISSUE TITLE
SSD Mobilenet Binaryproto run Object Detection with bounding boxes live in AIY Camera

### ISSUE THREAD

**Issue by JakeMalis** [google/aiyprojects-raspbian#460]
I managed to retrain the Mobilenet v1 SSD (256 x 265, 0.125 multiplier) for my deck of cards. I converted the .pb file into a .binaryproto. I need help modifying the object_detection.py file to have the bounding boxes in the live camera feed. Does anyone happen to have code to run it live in the camera preview?

Thanks!

**Comment by giacomobartoli** [comment]
@JakeBMalis I did it. Take a look at my repo: https://github.com/giacomobartoli/vision-kit/tree/master/pikachu-detector

**Comment by JakeMalis** [comment]
How would I make it so that the bounding boxes are in real time, rather than having it take a photo when a object is detected and putting the bounding box on later? PS. Sorry I took so long to respond, school was starting and I was busy.

Thanks!

**Comment by giacomobartoli** [comment]
Again, take a look at my repository. You need those two libraries + a protobinary file.

**Comment by JakeMalis** [comment]
I can't figure out how to make it work real-time. Even following along with your code.

**Comment by giacomobartoli** [comment]
Open an issue into my repo and I'll be glad to help you.
