### ISSUE TITLE
No Sales support Team?

### ISSUE THREAD

**Issue by hazemati** [google/aiyprojects-raspbian#463]
Hey, I work for a startup company, we want to buy 100,000 units and want to speak with someone (I'm wondering if Google could cut the cost of individual unit. My understanding is that some stores originally sold them for $44, which is the price I'm looking for). I already tried calling the sales team for G-Suit, and emailed  support-aiyprojects@google.com (I didn't have any luck with either). Who do I contact for this?

**Comment by PeterMalkin** [comment]
Thank you for your interest. I believe you should have received communication by now.

**Comment by hazemati** [comment]
Dear Mr. Malkin, 
Thank you very much for getting in touch with me. Unfortunately, you're the first person I heard from. Please make sure that whoever is responsible contact me at ha245@cornell.edu. I look forward to hearing from you guys.
Thanks,
Houman

**Comment by hazemati** [comment]
Dear Mr. Malkin, 
I wanted to thank you for doing taking care of this. Someone finally emailed me. 
Regards, 
Houman
