### ISSUE TITLE
the mistake with burning aiyprojects into sd card 

### ISSUE THREAD

**Issue by childswong** [google/aiyprojects-raspbian#467]
format the sd card
iburned the aiyproject into the sd card
then start
the power light of the raspi was open at the first beggining,then shut down
the sd card light flashed alwasys
the hdmi is ok but stop in the start show (colour picture),not go into the system

**Comment by dmitriykovalev** [comment]
It's actually unclear what's happening from your description. Can you provide more details? It's always good to try to reflash SD card again.

**Comment by manoj7410** [comment]
@childswong please make sure to use adequate power to boot the kit. It requires minimum of 2.1amp in order to boot properly.
