### ISSUE TITLE
Microphone clips in loud environments

### ISSUE THREAD

**Issue by drigz** [google/aiyprojects-raspbian#47]
The current configuration applies a 30dB gain to the microphone input (with the `route` plugin in `/etc/asound.conf`). This is so that if you record speech in a quiet environment, you can hear it clearly in the recorded file. This is useful for testing the audio, although it doesn't appear to affect close-range speech recognition (we've not done much long-range testing).

The mic gain causes clipping when the voice recognizer is used in loud environments. This makes speech recognition work much worse, because the user has to speak very loudly into the mic, which the voice recognizer can't understand.

A workaround is to edit `/etc/asound.conf`, and change both `30.0` values in the `micboost` section to `10.0` or lower (but not below `1.0`).

Changing the mic boost to `10.0` (20dB) may be the right long-term fix, although check_audio.py will need to be adjusted to apply another 10dB gain (or perhaps to normalize the volume?) to ensure audible output in quiet environments.

**Comment by dmitriykovalev** [comment]
We switched to PulseAudio, so `/etc/asound.conf` is obsolete.
