### ISSUE TITLE
AIY vision kit with a different camera

### ISSUE THREAD

**Issue by jessecha** [google/aiyprojects-raspbian#474]
Is it possible to use the vision board with a different camera?
I know the V1 is not supported, but is it possible to create a generic driver for the vision bonnet? I would like to use a 360 camera.

**Comment by dmitriykovalev** [comment]
Pi Camera is fully managed by Pi's driver, VisionBonnet just intercepts raw image frames. There is a crypto chip on Pi Camera, so Pi's driver will not work with any custom camera.

**Comment by jessecha** [comment]
If this is the case, why doesnt the vision bonnet work with a v1 camera? I was specifically looking at using a kogeto dot camera for the vision bonnet

**Comment by dmitriykovalev** [comment]
v1 and v2 have completely different image sensors (OmniVision vs Sony) and our internal imaging pipeline on Myriad is optimized for v2. Why don't you use v2 with Kogeto Dot?
