### ISSUE TITLE
Click/pop noise at end of aiy.audio.say() playback in 2018-08-03 image

### ISSUE THREAD

**Issue by TM-hub** [google/aiyprojects-raspbian#475]
Seems to be due to the _volume level_ modifier in _say()_ (in file aiy/voice/tts.py)
To recreate, from the command line:

**Click version**
`pico2wave -w ~/temp.wav -l en-US "<volume level='40'>hello</volume>"`
`aplay  ~/temp.wav`

**No click version**
`pico2wave -w ~/temp.wav -l en-US "hello"`
`aplay  ~/temp.wav`

The click version above has the same result (makes a click/pop) on both 2018-08-03 and 2018-04-13 images. The old (2018-04-13) implementation of aiy.audio.say(), using _tts.py, didn't have this issue.

**Comment by mikeyroth** [comment]
I also have a pop at the end when using aiy.audio.say()

**Comment by f4n** [comment]
Same here, some workarounds available?

**Comment by TheArduinist** [comment]
I also have the same problem. By using this code:

`cmd = 'pico2wave -w %s -l en-US "<volume level=\'40\'>hello</volume>"' % ('temp.wav')`
`subprocess.check_call(cmd, shell=True)`
`cmd = 'aplay %s' % ('temp.wav')`
`subprocess.check_call(cmd, shell=True)`

Which basically explicitly uses the command @TM-hub used, the pop was avoided in my case. I guess that means the problem might lie in the way tts.py issues the command? I'm not sure.

**Comment by dmitriykovalev** [comment]
That's already fixed in our internal codebase, we'll publish to GitHub soon. That's the new code:

```python
import os
import subprocess
import tempfile

TMP_DIR = '/run/user/%d' % os.getuid()

def say(text, lang='en-US', volume=60, pitch=130, speed=100, device='default'):
    data = "<volume level='%d'><pitch level='%d'><speed level='%d'>%s</speed></pitch></volume>" % \
        (volume, pitch, speed, text)
    with tempfile.NamedTemporaryFile(suffix='.wav', dir=TMP_DIR) as file:
       cmd = 'pico2wave --wave %s --lang %s "%s" && aplay -q -D %s %s' % (file.name, lang, data, device, file.name)
       subprocess.check_call(cmd, shell=True)

```

**Comment by dmitriykovalev** [comment]
Fixed, you can try new SD card image: https://github.com/google/aiyprojects-raspbian/releases/tag/v20181116
