### ISSUE TITLE
Vision Bonnet Button Connector pinout

### ISSUE THREAD

**Issue by algila** [google/aiyprojects-raspbian#477]
Is it possible to have the Vision Bonnet Button Connector pinout ?
I whould use a smaller button to reduce the final package of the AIY kit.

**Comment by scottamain** [comment]
Absolutely. We'll put it online soon. For now, see the attached image

![vision-button-pinout](https://user-images.githubusercontent.com/1672461/45247491-e62b6700-b2bc-11e8-9d8a-b900ba6f3ce6.jpg)

**Comment by algila** [comment]
Many thanks, 
- may you also communicate how to connect the led to the related pin ? I suppose the pin is closing to 
  Ground, is it correct ? What is the max current ?
- About pin 1 what is the max current it should absorb ?
- About pin6 BTN. If it is the button, do I need to connect the second button's pin to GND or 5V  ?

**Comment by dmitriykovalev** [comment]
We use this part https://www.kinet-ic.com/ktd2027/ as a LED driver, I guess you can find all information there. LEDs are active-low by the way.
