### ISSUE TITLE
Play music through deezer

### ISSUE THREAD

**Issue by Superdrac** [google/aiyprojects-raspbian#479]
Hi, I have installed the latest image on my SD card. 

I tried the assistant_library_demo.py and everything is working. I can ask question, get the weather for tomorrow (I've set the address of the device though google assistant app on my phone)

But I can't play music through my linked deezer account. Is it normal ?

**Comment by manoj7410** [comment]
@Superdrac Yes, it is normal because feature of playing music is still not part of the Google Assistant SDK. You can refer https://developers.google.com/assistant/sdk/release-notes to get more details.
