### ISSUE TITLE
Bonding Boxes On Other Classifiers

### ISSUE THREAD

**Issue by SwannSchilling** [google/aiyprojects-raspbian#480]
Is there any chance to get bounding boxes on other image classifiers than the face and the person, cat, dog classifier.
I would love to get those out of my camera Interference, to move a servo...

**Comment by dmitriykovalev** [comment]
[Object Detection](https://github.com/google/aiyprojects-raspbian/blob/aiyprojects/src/aiy/vision/models/object_detection.py) model does support bounding boxes, please check e.g. [here](https://github.com/google/aiyprojects-raspbian/blob/93a6306438492464c25916b6b2f53d8e4750579b/src/aiy/vision/models/object_detection.py#L49).

**Comment by SwannSchilling** [comment]
Thanks a lot for the information! :)

**Comment by dmitriykovalev** [comment]
No problem!
