### ISSUE TITLE
This new aiy image file would not download completed or failed 

### ISSUE THREAD

**Issue by jimbo95-beep** [google/aiyprojects-raspbian#491]
I tried to download the new image file more then once and it failed to download or was incomplete

**Comment by manoj7410** [comment]
@jimmy95 Where are you downloading it from ?
Can you try to download it from : https://github.com/google/aiyprojects-raspbian/releases/tag/v20180803

**Comment by dmitriykovalev** [comment]
@jimmy95 Which error did you get and which URL did you try?

**Comment by dmitriykovalev** [comment]
All download links should work.
