### ISSUE TITLE
How to use AIY in the official system of raspberry?

### ISSUE THREAD

**Issue by zouzhe1** [google/aiyprojects-raspbian#492]
I didn't use the img provided by the AIY project, so how should my sound driver, speaker and microphone driver be set? Is ALSA using?

my AIY is  voice v1 @atvrager @dberlin

**Comment by zouzhe1** [comment]
And Is this aiy project hardware open source? Where can I find the SCH and PCB for voice v1?

**Comment by dmitriykovalev** [comment]
@zouzhe1 Regarding you second question: SCH and PCB are not available for public. Regarding the first question, please take a look at https://github.com/google/aiyprojects-raspbian/blob/aiyprojects/docs/voice.md#drivers. You need to enable VoiceHAT overlay on the Raspbian image and everything should start working. You probably also need to comment out `dtparam=audio=on` in the `/boot/config.txt` to make VoiceHAT a single sound device.

**Comment by mpember** [comment]
> And Is this aiy project hardware open source? Where can I find the SCH and PCB for voice v1?

There are some who have created alternative HATs that provide near-identical functionality.
https://github.com/shivasiddharth/custom-voice-hat

**Comment by dmitriykovalev** [comment]
We've added VoiceHAT schematic files to the `docs` folder: https://github.com/google/aiyprojects-raspbian/tree/aiyprojects/docs/design/voice_hat
