### ISSUE TITLE
UP board

### ISSUE THREAD

**Issue by joekh1** [google/aiyprojects-raspbian#498]
Dear Sir,

Can I use this library on Up board that runs on Ubuntu 16.04 LTS instead of a raspberry pi?

Thank you,

**Comment by manoj7410** [comment]
@joekh1 This needs to be given a try. This should work because both(Ubuntu and Raspbian) are Debian based distributions but haven't tested it yet.

**Comment by dmitriykovalev** [comment]
@joekh1 You have to install all required drivers first, check https://github.com/google/aiyprojects-raspbian/blob/aiyprojects/HACKING.md for details.

**Comment by dmitriykovalev** [comment]
Please open new issues if you have problems installing our drivers to Ubuntu.
