### ISSUE TITLE
How to make face_detection_trigger by default when started using the kit (vision kit v1.1)

### ISSUE THREAD

**Issue by rangodjango** [google/aiyprojects-raspbian#499]
Hi everyone. I am currently using vision kit v1.1 and as all we know, start up demo is joy_detector_demo by default. How can I set it to face_detection_trigger by default when vision kit begin startup? I am new in this and your advises is much appreciated.  Thank you.

**Comment by manoj7410** [comment]
@rangodjango Very first thing is to stop the joy_detection_demo from starting on every boot.
Run the command : 
"sudo systemctl stop joy_detection_demo" ==> To Stop
Then,
"sudo systemctl disable joy_detection_demo" ==> To disable from starting at every boot.

Now is the time to create a service which will start face_camera_trigger. You can follow the instructions given at : https://aiyprojects.withgoogle.com/voice/#makers-guide-run-your-app-automatically


Your script (my_face_trigger.service) will look like : 
```
[Unit]
Description=My awesome face trigger app

[Service]
Environment=XDG_RUNTIME_DIR=/run/user/1000
ExecStart=/bin/bash -c 'python3 -u src/examples/vision/face_camera_trigger.py'
WorkingDirectory=/home/pi/AIY-projects-python
Restart=always
User=pi

[Install]
WantedBy=multi-user.target
```

Now, run below commands:

`sudo mv my_face_trigger.service /lib/systemd/system/
`
`sudo systemctl enable my_face_trigger.service
`
Now, reboot your kit and if everything is good then face_camera_trigger should start at every boot.
