### ISSUE TITLE
_player.py play_wave() not working

### ISSUE THREAD

**Issue by pierrextardif** [google/aiyprojects-raspbian#500]
I got an error when trying to play a wav file.

I believe the error comes from the with statement in the _player.py : 
```         with wave.open(wav_path, 'r') as wav: ```

Replaced it with :
```         wav = wave.open(wav_path, 'r') ```

and it worked.

**Comment by manoj7410** [comment]
@pierrextardif Did you make any changes in Python version  ?

**Comment by pierrextardif** [comment]
No, 

I use python 3.

line 64 of the aiy/_drivers/_player.py, I changed the with statement:
```with wave.open(wav_path, 'r') as wav:```

Replaced it with :
```wav = wave.open(wav_path, 'r')```

**Comment by jfatula** [comment]
Looks like context manager support using with was added for wave.open() at Python 3.4. 
[https://python.readthedocs.io/en/latest/whatsnew/3.4.html](url)

**Comment by dmitriykovalev** [comment]
Please update you python version, @jfatula is right.
