### ISSUE TITLE
Setting the GPIO for vision kit v1.1

### ISSUE THREAD

**Issue by rangodjango** [google/aiyprojects-raspbian#502]
Hi, all. I have an issue here regarding setting the GPIO vision bonnet v1.1. I am a newbie in Raspi. The issue is the GPIO that i assigned in joy_detection_demo.py did not give any signal or output. I did make changes on joy_detection_demo.py line by importing the libraries:

from time import sleep
from signal import pause
from aiy.vision.pins import LED_1
from aiy.vision.pins import PIN_A
from gpiozero import LED
from gpiozero import Button
pin=LED(PIN_A)  ///as seen on vision bonnet GPIO A pin
led= LED(LED_1) 

I also make minor changes on Class Animator(object)

joy_score>0. 60 ///previously it was joy_score>0:
      self._leads.update(Leds.rgb_on(blend(JOY_COLOR,SAD_COLOR, joy score)))
      pin.on()

Once i run it, the there is no output at PIN_A that i connected to the red LED diode that i connected seperately using jumper/wire on the breadboard. What did I miss? How can I solve this? Your advice is much appreciated. Thanks.

**Comment by dmitriykovalev** [comment]
Can you please make sure that you are using the latest SD card image from https://github.com/google/aiyprojects-raspbian/releases ?
