### ISSUE TITLE
Error Running Unique Commands

### ISSUE THREAD

**Issue by ghost** [google/aiyprojects-raspbian#504]
When attempting to call Unique commands through the assistant, the whole process seems to crash. 
Errors were encounted earlier with the apparent non existence of the module, but now the error is something else. 
I am running a Raspberry pi 3

![image](https://user-images.githubusercontent.com/42822179/46912593-02f24300-cfbd-11e8-8b34-e94d94d7c839.png)

**Comment by dmitriykovalev** [comment]
Which SD card image do you use? Please download the latest one from https://github.com/google/aiyprojects-raspbian/releases.

**Comment by Colin1964** [comment]
@Hcookie  I had a similar problem. Quick fix for me was to install pico2wav. See full thread on @t1m0thyj  repo here https://github.com/t1m0thyj/AssistantPi/issues/14#issuecomment-431383174
