### ISSUE TITLE
How to perform face recognition?

### ISSUE THREAD

**Issue by rangodjango** [google/aiyprojects-raspbian#511]
Hi all. I got a question. I am using vision kit v1.1, raspi version stretch. I am able to run face_camera_trigger.py on and can save captured image inside the working directory where face_camera_trigger.py located . The next steps is on how to make face recognition,means that able to recognize the person the picture and then send the output on the terminal,that's all .Any ideas? Your help is much appreciated as I am a newbie in this field. Thanks. :)

**Comment by dmitriykovalev** [comment]
@rangodjango Our face detection model can only **detect** a face in the image, i.e. provide bounding box, face confidence score, and joy score. You cannot use it for face recognition, i.e. recognize a concrete person. You can try to train your own network for that.
