### ISSUE TITLE
[Q] Quantization level on bonnet comilper

### ISSUE THREAD

**Issue by chamcham115** [google/aiyprojects-raspbian#512]
Dear everyone. 
I have a question for bonnet compiler. 

In tutorial, we can convert to trained model using bonnet compiler. 
Can the converted model support model quantization ?

If it can support quantization, how many support quantization level?
FP16? INT8?

I just wonder this information. 

Thanks.

**Comment by bowu-google** [comment]
bonnet does computation in 16-bit float (half float)
