### ISSUE TITLE
AIY Vision not working 

### ISSUE THREAD

**Issue by trsbalaji** [google/aiyprojects-raspbian#513]
Hi, I bought vision kit version 1.1. Normal Raspberry pi zero w boots fine. Once connected MIPI flat flex cable to Raspberrypi zero w board is not booting.

https://aiyprojects.withgoogle.com/vision-v1/

Please help me.
![raspberrypizerow cable](https://user-images.githubusercontent.com/9653886/47544772-8ead7e80-d89d-11e8-8b81-47381487760a.jpg)
![raspberrypizerow and cable-board notbooting](https://user-images.githubusercontent.com/9653886/47544779-9836e680-d89d-11e8-87f2-fd219a2add5a.jpg)
![raspberrypizerow without cable board booting fine](https://user-images.githubusercontent.com/9653886/47544790-9f5df480-d89d-11e8-9dd7-b6ba815cc632.jpg)

**Comment by dmitriykovalev** [comment]
Did you lock a small latch on the VisionBonnet's flex connector? Please also attach photograph of the bonnet board where flex contacts are visible.

**Comment by trsbalaji** [comment]
Hi dmitriy, Thanks for your response. Connected flex cable board is not booting. Attached: photos

Could you please help me.

Thanks & Regards,

Balaji Babu

Attached: 
![bonnetflexcableraspberrypizeroconnectpowersupply](https://user-images.githubusercontent.com/9653886/47598898-3b4c3680-d958-11e8-8e5f-aa51c286901c.jpg)
![visionbonnetandraspberrypi3zero](https://user-images.githubusercontent.com/9653886/47598912-5454e780-d958-11e8-9694-a49dd506a2ae.jpg)
![20181026_193944](https://user-images.githubusercontent.com/9653886/47598916-70588900-d958-11e8-8717-23874a89d05e.jpg)

**Comment by trsbalaji** [comment]
Hi dmitriykovalev,

Raspberry pi zero reverse flex cable  connected bonnet vision board is booting.  Bonnet connected with camera 

Getting error message

raspistill -w 1640 -h 922 -o image.jpg
mmal: Cannot read camera info, keeping the defaults for OV5647
mmal: mmal_vc_component_create: failed to create component 'vc.ril.camera' (1:ENOMEM)
mmal: mmal_component_create_core: could not create component 'vc.ril.camera' (1)
mmal: Failed to create camera component
mmal: main: Failed to create camera component
mmal: Camera is not detected. Please check carefully the camera module is installed correctly

**Comment by dmitriykovalev** [comment]
VisionBonnet on your photo is not connected correctly. You connected short flex to the camera connector and that's wrong. Please carefully follow the steps from https://aiyprojects.withgoogle.com/vision/#assembly-guide

**Comment by trsbalaji** [comment]
Hi Dmitriy,

Thanks for your suggestion. Normal raspberry pi zero works fine after connecting vision bonnet getting below error.

mmal: mmal_vc_component_enable: failed to enable component: ENOSPC
mmal: camera component couldn't be enabled
mmal: main: Failed to create camera component
mmal: Failed to run camera app. Please check for firmware updates

Could you please help me.

Regards

Balaji Babu

**Comment by manoj7410** [comment]
@trsbalaji Can you make sure that you have stopped joy_detection_demo before trying another demo ?

Command to stop joy_detection is : "sudo systemctl stop joy_detection_demo"

**Comment by trsbalaji** [comment]
> @trsbalaji Can you make sure that you have stopped joy_detection_demo before trying another demo ?
> 
> Command to stop joy_detection is : "sudo systemctl stop joy_detection_demo"

Thanks for your timely help. Could you please tell me, where i will find to download  cat.jpg, dog.jpg file

**Comment by trsbalaji** [comment]
> VisionBonnet on your photo is not connected correctly. You connected short flex to the camera connector and that's wrong. Please carefully follow the steps from https://aiyprojects.withgoogle.com/vision/#assembly-guide

Finally worked.  Thanks for your timely help

Could you please tell me, where i will find to download  cat.jpg, dog.jpg file

Thanks,
Balaji Babu

**Comment by dmitriykovalev** [comment]
Test images can be downloaded using `make` command: https://github.com/google/aiyprojects-raspbian/blob/aiyprojects/src/tests/images/Makefile

**Comment by trsbalaji** [comment]
> Test images can be downloaded using `make` command: https://github.com/google/aiyprojects-raspbian/blob/aiyprojects/src/tests/images/Makefile

Hi, Thanks for your help. After download the hotdog.jpg image i run the program getting error message.

Sorry for the disturb. Could you please help me

pi@raspberrypi:~/AIY-projects-python/src/examples/vision $ object_detection.py  --input=hotdog.jpg --output=/home/pi/AIY-projects-python/src/examples/vision/result.jpg
Traceback (most recent call last):
  File "/usr/local/bin/object_detection.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/opt/aiy/projects-python/src/examples/vision/object_detection.py", line 60, in <module>
    main()
  File "/opt/aiy/projects-python/src/examples/vision/object_detection.py", line 50, in main
    result = inference.run(image_center)
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 98, in run
    return self._engine.image_inference(self._key, image, params)
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 317, in image_inference
    return self._communicate(request).inference_result
  File "/opt/aiy/projects-python/src/aiy/vision/inference.py", line 187, in _communicate
    response.ParseFromString(self._transport.send(request.SerializeToString()))
  File "/opt/aiy/projects-python/src/aiy/_drivers/_transport.py", line 33, in send
    return self._spicomm.transact(request)
  File "/opt/aiy/projects-python/src/aiy/_drivers/_spicomm.py", line 117, in transact
    raise SpicommOverflowError(PAYLOAD_SIZE)
aiy._drivers._spicomm.SpicommOverflowError

**Comment by dmitriykovalev** [comment]
Please download and flash the latest SD card image from https://github.com/google/aiyprojects-raspbian/releases
