### ISSUE TITLE
voicebonnet led

### ISSUE THREAD

**Issue by yiyowei** [google/aiyprojects-raspbian#517]
Hello. When I connect voice kit2 with WIFI, the led flashes red. But I can still attach the Internet, I wonder why this happens.

**Comment by dmitriykovalev** [comment]
What exactly is wrong in your situation?

**Comment by yiyowei** [comment]
> What exactly is wrong in your situation?

I connect wifi with the app AIY PROJECTS. I follow the instructions in the app. 
After 5 seconds of pressing the button, the led is supposed to flash green as it always was. 
But since I flashed the latest image, the led has flashed red. And I can still connect wifi. 
Thanks.
