### ISSUE TITLE
Will Edge TPU support be added?

### ISSUE THREAD

**Issue by EddieOne** [google/aiyprojects-raspbian#521]
Hi,

I'm looking for Edge TPU support but I don't have the hardware yet. I'm curious about the status and plans for that hardware.

Thanks

**Comment by dmitriykovalev** [comment]
You can find information about Edge TPU on our website: https://aiyprojects.withgoogle.com/edge-tpu/

**Comment by EddieOne** [comment]
ok, thanks. I will keep waiting. They said q3 of 2018. Sounds like AIY have some other software.
