### ISSUE TITLE
Where is protocol.proto?

### ISSUE THREAD

**Issue by bgao** [google/aiyprojects-raspbian#523]
Can anybody tell me where file protocol.proto is or from which .proto file [protocol_pb2.py](https://github.com/google/aiyprojects-raspbian/blob/aiyprojects/src/aiy/vision/proto/protocol_pb2.py) is generated?

**Comment by dmitriykovalev** [comment]
`protocol.proto` is not yet included in the source code. The protocol is already pretty stable, so we'll probably add it soon.
