### ISSUE TITLE
Mr James harris 

### ISSUE THREAD

**Issue by jimbo95-beep** [google/aiyprojects-raspbian#534]
I have an aiy google assistant kit
I had to download the old image to get it to work the mic had stopped working so l used a PlayStation camera with mic built-in this worked after changing the settings on the new image which had installed once l had it running  on the old image l then set it up to 
work  without have to put command prompt in the the terminal.  Its working fine . I am trying get it to work with the magic mirror project. I used google assistant in my setup. 
Hope this helpful any one else setup voice .
I the new image needs looking at as it seems to have some issues?

**Comment by dmitriykovalev** [comment]
Could you please provide more details? E.g. what exactly fails and which settings did you change. Any command line output with error message would be very helpful.
