### ISSUE TITLE
Mr James Harris 

### ISSUE THREAD

**Issue by jimbo95-beep** [google/aiyprojects-raspbian#535]
I have a raspberry pi 3 and the bluetooth has stopped working l did an up date and update sudo apt-get install pi-bluetooth and l have the latest version installed but l still can't get it to work l also run bluetooth comand scan its still will not work any help please?

**Comment by dmitriykovalev** [comment]
Which AIY SD card image do you use? What exactly do you do to test bluetooth state, can you provide command lines and their outputs?

**Comment by jimbo95-beep** [comment]
I tried to update pi-bluetooth it said i have the latest version installed  I need to turn on my bluetooth how do I do this thank for any help

**Comment by dmitriykovalev** [comment]
Looks like this is out of AIY scope. Try to find any Raspberry Pi Bluetooth setup guides and follow the steps there.
