### ISSUE TITLE
LED not lighting up - installed on own raspberry build

### ISSUE THREAD

**Issue by VR6Pete** [google/aiyprojects-raspbian#54]
Hi there,

I have setup as per HACKING.MD and the LED button doesn't light up, nor does voice recognizer start from systemctl on boot up.

If I start from main.py - the console says: info:audio:started recording but doesn't actually appear to be accepting any commands and LED still does not light up.

If I insert the card with the AIY image already loaded it works fine, LED lights up and everything works as expected. 

Are there some steps missing ?

What can I do to troubleshoot ?

**Comment by drigz** [comment]
Can you post the output of this command?

`sudo journalctl -u status-led -n 20`

**Comment by VR6Pete** [comment]
-- Logs begin at Fri 2017-05-19 13:40:44 UTC, end at Fri 2017-05-19 15:08:38 UTC. --
May 19 13:40:50 raspberrypi systemd[1]: status-led.service: main process exited, code=exited, status=1/FAILUR
May 19 13:40:50 raspberrypi systemd[1]: Unit status-led.service entered failed state.
May 19 13:40:50 raspberrypi systemd[1]: status-led.service holdoff time over, scheduling restart.
May 19 13:40:50 raspberrypi systemd[1]: Stopping status led service...
May 19 13:40:50 raspberrypi systemd[1]: Starting status led service...
May 19 13:40:50 raspberrypi systemd[1]: Started status led service.
May 19 13:40:51 raspberrypi bash[1452]: Traceback (most recent call last):
May 19 13:40:51 raspberrypi bash[1452]: File "src/led.py", line 160, in <module>
May 19 13:40:51 raspberrypi bash[1452]: main()
May 19 13:40:51 raspberrypi bash[1452]: File "src/led.py", line 117, in main
May 19 13:40:51 raspberrypi bash[1452]: import configargparse
May 19 13:40:51 raspberrypi bash[1452]: ImportError: No module named 'configargparse'
May 19 13:40:51 raspberrypi systemd[1]: status-led.service: main process exited, code=exited, status=1/FAILUR
May 19 13:40:51 raspberrypi systemd[1]: Unit status-led.service entered failed state.
May 19 13:40:51 raspberrypi systemd[1]: status-led.service holdoff time over, scheduling restart.
May 19 13:40:51 raspberrypi systemd[1]: Stopping status led service...
May 19 13:40:51 raspberrypi systemd[1]: Starting status led service...
May 19 13:40:51 raspberrypi systemd[1]: status-led.service start request repeated too quickly, refusing to st
May 19 13:40:51 raspberrypi systemd[1]: Failed to start status led service.
May 19 13:40:51 raspberrypi systemd[1]: Unit status-led.service entered failed state.

**Comment by drigz** [comment]
Once #55 has been merged, you'll need to run:
```
git pull
sudo scripts/install-services.sh
```

**Comment by VR6Pete** [comment]
Excellent - seems to be working ok now - I manually made the change to the service file and seems to be OK now.

**Comment by drigz** [comment]
Great - thanks for reporting the issue!
