### ISSUE TITLE
Self-trained model worked on PC but not on Vision Bonnet

### ISSUE THREAD

**Issue by zye1996** [google/aiyprojects-raspbian#541]
Hi, I trained a model with 256*256 0.125 depth multiplier SSD-Mobilenet for object detection. The model is tested to work on my PC. But when I move it onto vision bonnet, it shows a bunch of target boxes in the view and seems targeting randomly. 

Can anyone give any suggestion for debugging?

**Comment by dmitriykovalev** [comment]
Could you please share more information about your model and what exactly doesn't work in your case?

**Comment by zye1996** [comment]
My bad. I did not revise the decode function in objection detection file
