### ISSUE TITLE
ImportError: No module named 'aiy.pins'

### ISSUE THREAD

**Issue by darrenchiu** [google/aiyprojects-raspbian#543]
I am trying to control the LED with a very simple script but it doesn't seem to be able to import from `aiy.pins`. Could anyone shed some light on this?

my simple script:
```
import aiy.audio
import aiy.cloudspeech
import aiy.voicehat

from time import sleep
from gpiozero import LED
from aiy.pins import LED_1

led = LED(LED_1)
while True:
                 led.on()
                sleep(1)
                led.off()
                sleep(1)

```

Thanks a lot!

**Comment by manoj7410** [comment]
@darrenchiu This might be helpful. https://github.com/google/aiyprojects-raspbian/blob/v20181116/src/examples/gpiozero/led_chaser.py

And this too : https://github.com/google/aiyprojects-raspbian/blob/v20181116/src/examples/gpiozero/led_example.py

Try to add this line : #!/usr/bin/env python3

**Comment by Onewayfong** [comment]
Darren, do you solve the issue now? because we have a similar problem. it warns: no aiy.vision.pin. would you like to give some instruction? thanks.

**Comment by dmitriykovalev** [comment]
@Onewayfong Do you use the latest SD card image from  https://github.com/google/aiyprojects-raspbian/releases ?  We moved `pins` from `aiy.vision` to `aiy` long time ago.

**Comment by Onewayfong** [comment]
@dmitriykovalev Yes. we use the latest SD card image. and we also change the pin name from aiy.vision to aiy. it didn't work. and we found there is something wrong with the PI. after we urgrade it, it is okay now. thanks for your attention.

**Comment by dmitriykovalev** [comment]
@Onewayfong Sounds good!
