### ISSUE TITLE
How to adapt script for iphone?

### ISSUE THREAD

**Issue by Tylersuard** [google/aiyprojects-raspbian#546]
Hello.  I know this isn't your job, and I'm sure you are busy, but I was hoping you can point me in the right direction.  I'd like the function of the "Joy Detector" demo, but on my iphone.  As in, I would like my iphone to sense visually when a person is smiling.  Can you give me some pointers on how to make that happen?

**Comment by dmitriykovalev** [comment]
I guess that's not directly related to the VisionKit if you want to implement the same functionality on iPhone. You can look at [TensorFlow Lite ](https://www.tensorflow.org/lite/) which should work on iOS. And of course you need a trained model for that.

**Comment by Tylersuard** [comment]
Ok, thank you :)
