### ISSUE TITLE
Accessing the SAM D09's 12-bit ADC

### ISSUE THREAD

**Issue by fjifdg895ngdf** [google/aiyprojects-raspbian#553]
The Vision Bonnet exposes a few of the SAM D09's analog pins (PA04 and PA05). Are there any Python API examples of reading voltage values from these pins?

**Comment by dmitriykovalev** [comment]
You can use kernel [IIO](https://www.kernel.org/doc/html/v4.14/driver-api/iio/index.html) subsystem to read voltages:
```bash
cat /sys/bus/iio/devices/iio\:device0/in_voltage0_user0_input
cat /sys/bus/iio/devices/iio\:device0/in_voltage1_user1_input
cat /sys/bus/iio/devices/iio\:device0/in_voltage2_user2_input
cat /sys/bus/iio/devices/iio\:device0/in_voltage3_user3_input
```

**Comment by fjifdg895ngdf** [comment]
I just confirmed this works for PA04 (A). Cool! And thank you...

I'm surprised you can use PA10 (C) and PA11 (D) for analog input. According to the SAM D09 datasheet, those are digital pins.

**Comment by dmitriykovalev** [comment]
Datasheet actually looks correct:

<img width="403" alt="atmel" src="https://user-images.githubusercontent.com/716798/50495870-e2912c80-09e0-11e9-8067-47f52727348a.png">

**Comment by fjifdg895ngdf** [comment]
You're right. The datasheet I was looking at had a diagram that led me to believe those were digital-only pins.

![screen shot 2018-12-27 at 3 37 12 pm](https://user-images.githubusercontent.com/6088768/50496459-6224f880-09ed-11e9-8743-ca6f3311efc4.png)

**Comment by dmitriykovalev** [comment]
Alright, I guess this can be closed :)
