### ISSUE TITLE
Support request of Node-RED

### ISSUE THREAD

**Issue by zuhito** [google/aiyprojects-raspbian#555]
Node-RED is a standard development environment for Raspbian. It makes AI application development easy for a lot of beginner programmers without coding. For example, Node-RED can easily connect to Google Translation, Cloud Vision and other Google Cloud services. Of course, python command in AIY can be run using exec node on the Node-RED flow editor. Why is it removed from the default Rasbian? Is there any plan to install it to AI Kits image? (Installation is just one command as the following instructions.)
https://nodered.org/docs/hardware/raspberrypi

**Comment by dmitriykovalev** [comment]
Looks Node-RED was removed from Raspbian, e.g. there is some info [here](https://core-electronics.com.au/tutorials/node-red-setup.html). We are using Raspbian images as is and only adding AIY stuff, we don't install any other software.

**Comment by zuhito** [comment]
@dmitriykovalev That web site has old information. The latest Rasbian (November version) has Node-RED as pre-installed software. As the web site explained, the Node-RED was removed temporarily because of image size. After that, a lot of developers complained about the removing it. Therefore, November version of Rasbian supported Node-RED again. This history means that Node-RED has tremendous fans, especially hobby users which is same target of Google AIY. I really appreciate if Google considers to install Node-RED.

**Comment by dmitriykovalev** [comment]
@zuhito Got it. We are going to release new SD card image soon, it will be based on the latest Raspbian release.

**Comment by zuhito** [comment]
@dmitriykovalev Great! Thank you for your understanding! I really like Google AIY!
