### ISSUE TITLE
Running auto update after flashing 11.16 breaks camera 

### ISSUE THREAD

**Issue by branflake2267** [google/aiyprojects-raspbian#556]
Camera sensor fails to work after updating the system. Seems the drivers that are updated break operations. 

Reproduction:
1. Flash 11.16
2. Boot up system
3. Reset password to pi, add wifi, set location...
4. Wait for auto-update prompt and say ok
5. Wait for auto-update to finish hour(s) later...
6. Try joy demo, or  camera detection demo, or raspistill -o test.png - it won't work

**Comment by branflake2267** [comment]
Looks like this duplicates: https://github.com/google/aiyprojects-raspbian/issues/527

**Comment by branflake2267** [comment]
By the way, I did take it apart and check all the cable connections and that wasn't it. The reason I could tell is I re-flashed the sd card and booted again. The camera works after fresh flash...

**Comment by branflake2267** [comment]
I did another update. I've found that `raspistill -o test.jpg` is working but the `face_detection_camera.py` won't work, and it complains about the /dev/vision_spicomm is missing.

**Comment by branflake2267** [comment]
Related: https://github.com/google/aiyprojects-raspbian/issues/382

**Comment by branflake2267** [comment]
Related: https://github.com/google/aiyprojects-raspbian/issues/377 

I get the same error in the kern.log `aiy-vision spi0.0: Incoming crc mismatch: slave ec6zef0 vs computed e2b16736`...

**Comment by nicholst** [comment]
Same happens to me, but it kills the even `raspistill` generating either this error

```
Camera control callback  cmd=0x4f525245mmal: No data received from sensor. Check all connections, including the Sunny one on the camera board
```

or a repetition of

```Message from syslogd@raspberrypi at Feb 26 17:15:48 ...
 kernel:[  312.650945] Code: bad PC value```

**Comment by manoj7410** [comment]
This issue seems to be fixed with the latest AIY image : https://github.com/google/aiyprojects-raspbian/releases/tag/v20191113.
