### ISSUE TITLE
In Image Classification guide: fix documentation arguments, add space

### ISSUE THREAD

**Issue by branflake2267** [google/aiyprojects-raspbian#558]
Documentation cmd arguments are wrong, it makes it tough to copy and paste. 

Reproduction: 
1. Go to: https://aiyprojects.withgoogle.com/model/image-classifier/
2. Note cmd: `wget https://farm4.staticflickr.com/4110/5099896296_2e2617a0a8_o.jpg-O flower.jpg`
3. add space to the argument -O

<img width="733" alt="screen shot 2019-01-01 at 11 20 27 am" src="https://user-images.githubusercontent.com/1326504/50575671-58b5da80-0db7-11e9-9bdf-de44aaae27f1.png">

**Comment by dmitriykovalev** [comment]
Fixed, thanks!
