### ISSUE TITLE
assistant_library_demo.py for AIY Voice Kit v.2

### ISSUE THREAD

**Issue by anishg24** [google/aiyprojects-raspbian#560]
As the title suggests, I would like to know how to run assistant_library_demo.py for the 2nd edition of the kit. I know in the comments that the Pi Zero is not supported, but is there any work around or anything that can be done to gain similar results?
Browsing this GitHub I've seen people use Snowboy to do hotword detection, but I'm afraid that if I do use Snowboy, it will only be tuned to my voice, and no one else can use it because their voice sounds different than mine.
Maybe in the future, the team would be nice enough to release an alternative for us 2.0 users

**Comment by dmitriykovalev** [comment]
Hotword detection depends on the Pi model. For example, you can use Voice Bonnet (v2) with Pi 3 instead of Pi Zero and get hotword detection working. Another example [assistant_grpc_demo.py](https://github.com/google/aiyprojects-raspbian/blob/aiyprojects/src/examples/voice/assistant_grpc_demo.py) works for all Pi models but doesn't support hotword detection.

**Comment by Forbin1138** [comment]
This isn't even present in the image from magpi. Where would i find this since the instructions that came with the google aiy kit are useless?

**Comment by manoj7410** [comment]
@Forbin1138  Latest AIY image can be downloaded from https://github.com/google/aiyprojects-raspbian/releases/tag/v20181116 and assistant_library_demo.py can be found at : https://github.com/google/aiyprojects-raspbian/blob/aiyprojects/src/examples/voice/assistant_library_demo.py 
AIY website : https://aiyprojects.withgoogle.com/voice/ has the updated information.

**Comment by anishg24** [comment]
@dmitriykovalev That's cool and all, but I prefer the smaller profile of the Pi Zero. Is there no way to get Hotword detection on the Pi Zero?

**Comment by dmitriykovalev** [comment]
@generaldefence You can look for third party libraries for hotword detection on Pi Zero. Unfortunately  assistant library doesn't support this feature on Pi Zero.
