### ISSUE TITLE
Light won't come on when pairing voice kit

### ISSUE THREAD

**Issue by Orangeshavecitrus** [google/aiyprojects-raspbian#561]
When I try holding down the button to pair the voice kit the led light next to the button does not turn on.

**Comment by manoj7410** [comment]
Can you run /home/pi/AIY-projects-python/src/examples/gpiozero/led_example.py and check if on-board LED glows ?
Make sure that you have installed https://github.com/google/aiyprojects-raspbian/releases/tag/v20181116

**Comment by dmitriykovalev** [comment]
@Orangeshavecitrus Are you using the latest SD card image from https://github.com/google/aiyprojects-raspbian/releases ?

**Comment by dmitriykovalev** [comment]
There are no any additional details provided — closing.
