### ISSUE TITLE
Question: VisionBonnet & TensorFlow

### ISSUE THREAD

**Issue by edrdo** [google/aiyprojects-raspbian#566]
I have a few questions regarding the AIY Vision Kit in particular regarding VisionBonnet  and also TensorFlow  - sorry if some most of these go beyond strict development issues, but here seems to be the better place to ask:

* Does the VisionBonnet chip use TensorFlow? 
* Either way, is it possible to convert the models available at the [AIY projects]( https://aiyprojects.withgoogle.com/models/) for use with TensorFlow in other settings (e.g. using the TF API directly) ?
* Is  the standalone VisionBonnet chip available for sale? Also, how does it releate to the upcoming [Edge TPU Devices](https://aiyprojects.withgoogle.com/edge-tpu/) ?

**Comment by dmitriykovalev** [comment]
VisionBonnet is based on [Myrad2450](https://www.movidius.com/myriad2) chip. 

There is a special binary format to represent compute graphs. VisionBonnet [Python API](https://github.com/google/aiyprojects-raspbian/blob/aiyprojects/src/aiy/vision/inference.py) is designed to run these files. Some compute graphs can be converted from TensorFlow by using our [compiler](https://aiyprojects.withgoogle.com/vision/#makers-guide--tensorflow-model-compiler).

EdgeTPU devices are based on a different chip (Edge TPU) designed by Google.

**Comment by edrdo** [comment]
Thanks for the answers.

>  Some compute graphs can be converted from TensorFlow by using our compiler.

I see, but I was looking for a way to accomplish the reverse operation, i.e., to convert a Vision Kit model to TensorFlow format. In particular I was interested in doing so for the [Nature Explorer model](https://aiyprojects.withgoogle.com/model/nature-explorer/).

**Comment by weiran-work** [comment]
@edrdo 

Unfortunately, there's no method to do the reverse, during the conversion, some information is lost.
