### ISSUE TITLE
AIY Vision 1.1 possible to work with Pi 3A+?

### ISSUE THREAD

**Issue by ghost** [google/aiyprojects-raspbian#571]
Seems my connections are correct, but it is unable to boot, only solid red light, no green at all. I was wondering if it was even designed to allow 3A+. 

Thanks

**Comment by dmitriykovalev** [comment]
Vision Kit doesn't work on Pi 3B+, looks that's the same problem with 3A+. There are mode details in #349

**Comment by datarainfall** [comment]
Thanks @dmitriykovalev seems like it might be broadcom bcm2837b0 as the culprit as both 3B+ and 3A+ share this similarity.
