### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by CarlP66** [google/aiyprojects-raspbian#577]
AIY Voice has been working fine for months. No changes on my side, but today when I run the python script that I have been using, I get:

"requests.exceptions.HTTPError 500 Server Error: Internal Server Error for url: https://embeddedassistant.googleapis.com/v1alpha2/projects/voice-assistant-213123/deviceModels/voice-assistant-213123-voice-kit"

This looks very much like an issue at Google's end. Can someone confirm, and advise when it will be back up.

Thanks, Carl.

**Comment by CarlP66** [comment]
Seems OK now. I'm in no rush to close it though - lets see if it stays fixed.

**Comment by dmitriykovalev** [comment]
Similar problems already happened before for other users. Looks like a server-side issue. Please reopen if that still happens.

**Comment by CarlP66** [comment]
Need to re-open this - I am having a repeat occurrence.  As per comment from dmitriykovalev.
