### ISSUE TITLE
using voice without the voice bonnet

### ISSUE THREAD

**Issue by ElisaPLima** [google/aiyprojects-raspbian#581]
Hi! I would like to use the AIY Voice system image, in order to build a google assistant-enabled device, but without the voice bonnet, using a personal microphone and speaker. I need some coding in order to make the file check-audio.py to work with the Raspberry Pi 3 B original sound board.

**Comment by dmitriykovalev** [comment]
Right, that's possible and you probably need to do some coding. If your sound card becomes a default playback/recording device, then everything should pretty much working.
