### ISSUE TITLE
Android Things and AIY V2 (VoiceBonnet)

### ISSUE THREAD

**Issue by developeruk** [google/aiyprojects-raspbian#589]
Hi, Wondering if anyone here can help. 
Ive just bought the Google AIY Kit, but have the newer version 2. Im currently following through the Android things examples.
All of the google assistant examples for Android Things seem to be for version 1. Voice Hat

Is there an Android Things Driver for the Voice Bonnet? As the Voice hat driver doesnt seem work, or is outdated for the examples.

The current gradle driver link is  "api 'com.google.android.things.contrib:driver-voicehat:1.0'"

At present, the examples seem to connect to the google cloud, and send a voice input to the cloud. however, i cant seem to get an output. 

Thank you in advance

**Comment by dmitriykovalev** [comment]
There is no VoiceBonnet driver for Android Things. The only driver available is in `aiy-voicebonnet-soundcard-dkms` package, check [HACKING.md](https://github.com/google/aiyprojects-raspbian/blob/aiyprojects/HACKING.md) for more details. The driver for VoiceHAT is already a part of Raspberry Pi OS, so doesn't require any special installation.
