### ISSUE TITLE
Cannot get the Assistant's text response

### ISSUE THREAD

**Issue by michellemxm** [google/aiyprojects-raspbian#590]
I'm using AIY Voice Kit v2 and the Assistant Library. What I was trying to do is to get the Assistant's response and show the text on a display.

I checked other previous posts saying that the text is included in the parameter of event ON_RENDER_RESPONSE. But when I ran the library demo, ON_RENDER_RESPONSE was not being called at all, or at least nothing was being printed on the console. Events being printed were like this:
`INFO:root:ON_RECOGNIZING_SPEECH_FINISHED:`
`  {"text": "where is New York"}`
`INFO:root:ON_RESPONDING_STARTED:`
`  {"is_error_response": false}`
`INFO:root:ON_RESPONDING_FINISHED`
`INFO:root:ON_CONVERSATION_TURN_FINISHED:`
`  {"with_follow_on_turn": false}`

So my question is, if I'm using the Assistant Library, how can I get the Assistant response as text? Is it in the ON_RENDER_RESPONSE event's parameter? Why this event is not being called at all?

**Comment by manoj7410** [comment]
@michellemxm Is this issue still reproducible ?
