### ISSUE TITLE
Non-executable example files

### ISSUE THREAD

**Issue by holten** [google/aiyprojects-raspbian#601]
The example file voice_recorder.py lacks the `#!/usr/bin/env python3` at the top. It also isn't set to have executable privileges like the other examples. 

The same is true for button_led.py. Might be more.

**Comment by manoj7410** [comment]
@holten Thank you for reporting this. This has been fixed in https://github.com/google/aiyprojects-raspbian/blob/aiyprojects/src/examples/voice/voice_recorder.py. 
A new AIY release is also available at https://github.com/google/aiyprojects-raspbian/releases/tag/v20191113
