### ISSUE TITLE
SSH not working / NaCl 255 error

### ISSUE THREAD

**Issue by Davedwin** [google/aiyprojects-raspbian#603]
I just picked one of these up from Target, and I wasn't able to SSH into it. Using the below link I was able to get it working and decided to share with the community. In addition to the below, I recreated the SSH file so it had a more recent date. 

https://www.losant.com/blog/getting-started-with-the-raspberry-pi-zero-w-without-a-monitor

**Comment by dmitriykovalev** [comment]
There is a way to ssh directly to Pi Zero when it's connected to the host machine by using `ssh pi@192.168.11.2` command. Ethernet-over-USB feature is enabled by default in AIY SD card image.
