### ISSUE TITLE
Using IMU on Vision Bonnet

### ISSUE THREAD

**Issue by yahoo2016** [google/aiyprojects-raspbian#604]
There is an IMU: BMI160 according to AIY Project Documentation.  I'd like to use IMU for smart camera applications.  How can I access the BMI160?

**Comment by admin-reality8** [comment]
Adding a ping on this - Can the IMU be accessed? Thanks to anyone who knows.

**Comment by Waniliowy** [comment]
+1

**Comment by dmitriykovalev** [comment]
Unfortunately, there is no way to access IMU from the Raspberry Pi, it's only available for Myriad chip.

**Comment by mgagvani** [comment]
Is it possible for the Raspberry Pi to read the IMU data from the Myriad chip?
