### ISSUE TITLE
ImportError: No module named aiy.voice.tts

### ISSUE THREAD

**Issue by tummmmmy** [google/aiyprojects-raspbian#607]
Recently I have been trying to trigger GPIO LED on the cloudspeech_demo.py, but it returns the error, any clues?

**Comment by chickenbit** [comment]
Try running with “python3” at the prompt.   That resolved the package import errors I was seeing.

**Comment by manoj7410** [comment]
@tummmmmy Is this issue still reproducible ?

**Comment by dmitriykovalev** [comment]
Closing, please reopen if that's still a problem.
