### ISSUE TITLE
Source and Destination checksums do not match

### ISSUE THREAD

**Issue by chiragbhagat** [google/aiyprojects-raspbian#609]
I got the following error while using Etcher to flash the .img.xz file onto my MicroSD card.

\\.\PhysicalDrive1: Source and Destination checksums do not match: a36f58668eebd042!==44c89104a42cf590

Please help!

Thanks,
Chirag

**Comment by WaffleThief123** [comment]
@chiragbhagat have you extracted the *.img.xz using the command 
`unxz ./aiyprojects-20yy-mm-dd.img.xz 
` 
and then tried using dd to write the .img file to an sd card?

etchr works great 99.999% of the time, until it comes to debugging things like this.

if you need some help with dd, it works like this

```bash
#dd if=/path/to/image/file.img of=/dev/sdX
```

where X is the physical device name, found using the command 

```bash
# fdisk -l 
``` 
from a root shell.  Hope this helps!

**Comment by dmitriykovalev** [comment]
I guess you can try to flash one more time if checksum check fails. If it's consistent then try to use different SD card.
