### ISSUE TITLE
No Files in SD Card

### ISSUE THREAD

**Issue by Nano-AI** [google/aiyprojects-raspbian#611]
Hello, and I am having issues with the Vision Kit. I look at the files for the Vision kit on my computer, as I was interested in seeing the code. So opened the SD Card, and cut and pasted the files onto my computer and used the SD card for something else. So now when I loaded the SD Card, it asked me to format it and I did because I did not have important files on it. Then I pasted the files onto the SD card and flashed the image to the SD Card but it does not work anymore... What should I do?

**Comment by dmitriykovalev** [comment]
Please flash the latest SD card image from [Releases](https://github.com/google/aiyprojects-raspbian/releases) section. Flash instruction can be found in [HACKING.md](https://github.com/google/aiyprojects-raspbian/blob/aiyprojects/HACKING.md).
