### ISSUE TITLE
Failed booting. The button is flashing with a red light.

### ISSUE THREAD

**Issue by Gago55** [google/aiyprojects-raspbian#614]
Hi guys, I followed the instruction, build Vision, install the last image on sdCard, connect the camera to power with power supply(5V - 2A). After 10 minutes without any sound, the button flashing with a red light. I tried everything, reflash sdCard a few times, even I tried to flash sdCard with previous version 2018-08-03 but nothing changes. I'll glad for any help.

**Comment by jamesallen9** [comment]
Hi, I know what’s the problem. The same issue was happened with me. Do you have whatsapp or viber, then I can communicate to you?

**Comment by Gago55** [comment]
> Hi, I know what’s the problem. The same issue was happened with me. Do you have whatsapp or viber, then I can communicate to you?
Yes man I have viber , can you give your mail , I will send you my contacts

**Comment by jamesallen9** [comment]
Yes here is my email address 
allenjames716@yahoo.com

**Comment by Gago55** [comment]
Man but I think it is better to tell the solution here so anybody with the same issue can fix it.

**Comment by jamesallen9** [comment]
Ok, how do you want, but I think it will be easy to chat with you, or we can have a videocall with skype to tell you what to do )

**Comment by jamesallen9** [comment]
I create github account special for your issue )

**Comment by Gago55** [comment]
Anyway  it will be better to tell the solution here if it is not difficult

**Comment by jamesallen9** [comment]
🖕🏿🖕🏿

**Comment by NagaKanaparthy** [comment]
Could you provide pictures of the kit's internal setup. I think it may be a wire being loose or not fully connected. Most likely those yellow flex connectors.

**Comment by Gago55** [comment]
With connections all is OK. Problem in camera, it is defective. I've tried with my friend's camera and all was working.

**Comment by NagaKanaparthy** [comment]
Since this was a hardware issue (camera was defective as a Dead On Arrival part), I don't think this issue should stay open. Could you please close the issue?
