### ISSUE TITLE
 AIY voice kit V1.0 - need help

### ISSUE THREAD

**Issue by boxshifter** [google/aiyprojects-raspbian#616]
Hi

When i try to do the setup credentials on google cloud platform (OAuth consent screen) i'm seeing a totally different screen to the one in the setup guide, instead of being asked for an email and product name like the guide shows i'm being asked for Application Name, Application home page link, Application logo, Support email, Authorised domains etc.... and don't have a clue how to get past his?

![image (1)](https://user-images.githubusercontent.com/49980091/57454760-85946580-7261-11e9-8164-49747c38973e.png)

**Comment by manoj7410** [comment]
@boxshifter what do you see on the credentials tab ?

**Comment by manoj7410** [comment]
You only need to provide your App name (Sample : Voice kit) and nothing else is required on the consent screen.

**Comment by schamu78** [comment]
I follow the steps of providing the App name like you suggested but then I get an error that says "the request failed because one of the field of the resource is invalid."

**Comment by djwdev** [comment]
I got the same error "the request failed because one of the field of the resource is invalid".  Does Anybody have the work around?

**Comment by schamu78** [comment]
I reported to the support email and this is what I got.
![2B3F4F13-A765-428E-A94C-453603DF30DB](https://user-images.githubusercontent.com/66571447/84215906-6af87580-aa8d-11ea-8114-a18be570ef0c.jpeg)

**Comment by manoj7410** [comment]
I followed the below procedure and it worked fine for my personal account:

1. Create a new project.

![CreateProjectStep1](https://user-images.githubusercontent.com/2090835/84491017-92d01f00-acc1-11ea-86e6-8d3bcfb11839.png)
2. Select the project that just got created.

![SelectProjectStep2](https://user-images.githubusercontent.com/2090835/84491025-95327900-acc1-11ea-8b2f-a2e59f6eb906.png)
3. Goto APIs and Services and Click on Library

![GotoLibraryStep3](https://user-images.githubusercontent.com/2090835/84491030-95cb0f80-acc1-11ea-8b24-f1962aadead7.png)
4. Search "assistant" and Select "Google Assistant API"

![SearchAssistantLibraryStep4](https://user-images.githubusercontent.com/2090835/84491032-9663a600-acc1-11ea-9806-00e11b15cc84.png)
5. Enable the API

6. Click on "Create Credentials".

![ClickCreateCredentialsStep6](https://user-images.githubusercontent.com/2090835/84491036-96fc3c80-acc1-11ea-826c-f6b883100d72.png)
7. Select "Google Assistant API" in "Which API are you using?" option.

![SelectGoogleAssistantAPIsStep7](https://user-images.githubusercontent.com/2090835/84491037-9794d300-acc1-11ea-9c2f-cc001f9e97f9.png)
8. Select "Other UI" in "Where will you be calling the API from".

![SelectOtherUIStep8](https://user-images.githubusercontent.com/2090835/84491040-982d6980-acc1-11ea-8361-d502009d7a63.png)
9. Select "User Data" and click "What credentials do I need?".

![SelectUserDataandClickWhatCredentialsNeededStep9](https://user-images.githubusercontent.com/2090835/84491042-982d6980-acc1-11ea-9978-5f44d4cf2f3e.png)
10. Click on "SET UP CONSENT SCREEN".

![ClickOnSetupConsentScreenStep10](https://user-images.githubusercontent.com/2090835/84491045-98c60000-acc1-11ea-9a5b-5ac5bf36c7e6.png)
11. Select "External" in "User Type".

![SelectExternalStep11](https://user-images.githubusercontent.com/2090835/84491046-995e9680-acc1-11ea-8456-becbf99e8bd6.png)
12. Enter an application name on the consent screen page and no other information needs to be provided.

![WriteApplicationNameStep12](https://user-images.githubusercontent.com/2090835/84491047-995e9680-acc1-11ea-8d41-c01609839d1b.png)
13. Click "Save" on Consent Screen.

![ClickSaveStep13](https://user-images.githubusercontent.com/2090835/84491048-99f72d00-acc1-11ea-8adc-3b52844d514e.png)
14. Click on "Credentials" again. 

![ClickOnCredentialsAgainStep14](https://user-images.githubusercontent.com/2090835/84491051-9a8fc380-acc1-11ea-89d9-f23bcac6fb21.png)
15. Click on "Create Credentials" on top.

![ClickOnCreateCredentialsStep15](https://user-images.githubusercontent.com/2090835/84491052-9a8fc380-acc1-11ea-96a7-c5f62d299082.png)
16. Select OAuth Client ID

![SelectOAuthClientIDStep16](https://user-images.githubusercontent.com/2090835/84491053-9b285a00-acc1-11ea-848c-75552112a037.png)
17. Select "Desktop App" and Enter client name and Click on Create.

![SelectDesktopAppAndEnterClientNameStep17](https://user-images.githubusercontent.com/2090835/84491055-9bc0f080-acc1-11ea-82cf-06a7ee61f3af.png)
18. Download the credentials and use them on voice kit with old steps.

![DownloadCredentialsStep18](https://user-images.githubusercontent.com/2090835/84491057-9bc0f080-acc1-11ea-856c-8510b8ec1ff8.png)
