### ISSUE TITLE
Any way to add more GPIOs to AIY Voice Kit V2?

### ISSUE THREAD

**Issue by dyllen** [google/aiyprojects-raspbian#622]
I'm working on a project using the google AIY Voice Kit V2 as a base. I'm planning on adding a keypad which requires 12 GPIOs. Does anyone know of a way to add more GPIOs to the Pi Zero W with AIY Voice Kit v2?

**Comment by dmitriykovalev** [comment]
Possible option could be to use I2C GPIO extender, something like https://www.sparkfun.com/products/13601. It can be connected to the I2C bus on the Pi.
