### ISSUE TITLE
Joy vision cannot save image /root/pictures/ directory missing.

### ISSUE THREAD

**Issue by lewmhill** [google/aiyprojects-raspbian#638]

**Comment by lewmhill** [comment]
I can't figure out how to either create it or change the target location for saved images.

**Comment by lewmhill** [comment]
restarting joy non sudo causes pictures to be saved in home/pi/pictures as advertised but buzzer fails on privileges?

**Comment by manoj7410** [comment]
@lewmhill I would suggest you to download the AIY image from https://github.com/google/aiyprojects-raspbian/releases/tag/v20181116 and install it on your sdcard with help of Etcher (Etcher can be downloaded from https://www.balena.io/etcher/).

**Comment by dmitriykovalev** [comment]
If you need to run JoyDemo as root then just create the directory: `sudo mkdir /root/Pictures`.
