### ISSUE TITLE
Source and Destination checksums do not match

### ISSUE THREAD

**Issue by seowzhixuan** [google/aiyprojects-raspbian#639]
I got the following error while using Etcher to flash the .img file onto my SDHC card.

\.\PhysicalDrive1: Source and Destination checksums do not match. Please help!

**Comment by andrewtvuong** [comment]
Have you tried redownloading the official img?

**Comment by manoj7410** [comment]
@seowzhixuan Can you try to reflash with https://github.com/google/aiyprojects-raspbian/releases/tag/v20191113 ? 
Additionally, did you try to change the SDCARD ?

**Comment by dmitriykovalev** [comment]
Try to replace your SD card if that always happens after flashing.
