### ISSUE TITLE
Raspberry Pi 4 and AIY voice kit V1

### ISSUE THREAD

**Issue by saornek** [google/aiyprojects-raspbian#645]
I build robots and use AIY voice hat with Rpi3b+. I just bought a Rpi4 I wonder if the AIY voice kit is compatible with the RPi4. Thanks in advance.

**Comment by zikotrance** [comment]
Same thing here. Do you had any answer somewhere else to help resolving the issue?
Cheers

**Comment by tarzanek** [comment]
https://github.com/google/aiyprojects-raspbian/issues/627#issuecomment-514403972

**Comment by tupelotech** [comment]
v20181116 and

v20170911 images certainly do not boot on Pi4

**Comment by tarzanek** [comment]
> 
> 
> v20181116 and
> 
> v20170911 images certainly do not boot on Pi4

you need latest raspbian for rpi4, so those images need to be updated first and patched as per https://github.com/google/aiyprojects-raspbian/issues/627#issuecomment-514403972 

hth
L

**Comment by Paprika-Asteria** [comment]
i have tried install aiy-vision in RPi4,but have some problems,i didn't install 'protobuf-3.6.1-cp35-cp35m-linux_armv6l.whl' beacuse i need armv7l,and i have protobuf 3.5 ,i get into trouble,i need help plz

**Comment by tarzanek** [comment]
@Paprika-Asteria check https://github.com/google/aiyprojects-raspbian/releases/tag/v20191113
it will work

**Comment by klomfar** [comment]
hi, i get this error :
pi@raspberrypi:~ $ sudo dtoverlay googlevoicehat-soundcard
* Failed to apply overlay '0_googlevoicehat-soundcard' (kernel)
i have RPi 4 with Voice Kit V1, please help :(

**Comment by Paprika-Asteria** [comment]
> 
> 
> @Paprika-Asteria check https://github.com/google/aiyprojects-raspbian/releases/tag/v20191113
> it will work

i have install this image,but my when i run this examples ,my rpi4 don't work,
"FileNotFoundError: [Errno 2] No such file or directory: '/dev/vision_spicomm'"
i can't find this file,i need help.thanks

**Comment by dmitriykovalev** [comment]
@klomfar My Voice HAT works with Raspberry Pi 4 without any issues. Can you please try to run and copy output from
```
lsmod | grep snd_soc_googlevoicehat_codec
```
before and after executing overlay load command (`sudo dtoverlay googlevoicehat-soundcard`).

In addition, can you attach `dmesg` command output when it fails?

**Comment by ziligy** [comment]
Just to confirm release 2019-11-13 works on my Pi 4 with Voice hat v1  :)

**Comment by klomfar** [comment]
it works now,thanks for help @dmitriykovalev

**Comment by dmitriykovalev** [comment]
Great! Closing this issue then.

**Comment by Paprika-Asteria** [comment]
but i havenot this kit,i have only rpi4.it donot work.whether you install this image on your rpi4?i have a trouble.━(◯Δ◯∥)------------------ 原始邮件 ------------------
发件人: "jeff greenberg"<notifications@github.com>
发送时间: 2019年11月21日(星期四) 凌晨3:02
收件人: "google/aiyprojects-raspbian"<aiyprojects-raspbian@noreply.github.com>;
抄送: "Paprika-Asteria"<1968748621@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [google/aiyprojects-raspbian] Raspberry Pi 4 and AIY voice kit V1(#645)



Just to confirm release 2019-11-13 works on my Pi 4 with Voice hat v1  :)
 
&mdash;
