### ISSUE TITLE
Unable to download anything - Network Error

### ISSUE THREAD

**Issue by Lift25** [google/aiyprojects-raspbian#646]
Hi,
I've tried to download various versions of the AIY Voice Kits Code (version 1).  Each time it fails after downloading about 300MB.  I cannot obtain a copy to proceed with the kit.  Please advise.  Thanks.

**Comment by manoj7410** [comment]
From where are you trying to download the AIY voice kits code ?

**Comment by dmitriykovalev** [comment]
Please reopen and provide more details about your issue.
