### ISSUE TITLE
Polish Language for Google Assistant AIYProject

### ISSUE THREAD

**Issue by rkrysinski** [google/aiyprojects-raspbian#661]
Hello,

The Google Assistant has become available in Poland lately, however I noticed it is not supported on API level though (https://developers.google.com/assistant/sdk/reference/rpc/languages).

Is there any chance that support for polish can be added? Please let me know if this is not the right place to ask such question, and kindly ask to point me out the right channel.

Thank you,
Roman

**Comment by manoj7410** [comment]
IMHO preferred way should be to directly reach out to the Assistant SDK team for additional language support.
