### ISSUE TITLE
Use as posture detector?

### ISSUE THREAD

**Issue by Tylersuard** [google/aiyprojects-raspbian#662]
Hello!  I love the AIY kit, and it's worked perfectly as a smile detector.  I'm wondering how I can program it to become a correct posture detector?  There are models online that detect a person's estimated limb positions, neck, head, etc.  Can I reprogram my AIY to do that limb position estimation, and to alert me when my posture is sub-optimal?

**Comment by manoj7410** [comment]
This can be useful for you https://www.hackster.io/dvillevald/hand-command-recognizer-on-google-aiy-vision-kit-3786f6. This is not exactly posture detection but somehow related to it. I haven't tested this demo though.

**Comment by Tylersuard** [comment]
This is perfect, thank you!

**Comment by dmitriykovalev** [comment]
Please also check https://github.com/google-coral/project-posenet.
