### ISSUE TITLE
Vision bonnet blocks GPIO pins 14 & 15. How can I connect to these?

### ISSUE THREAD

**Issue by webxl** [google/aiyprojects-raspbian#672]
I was thinking about soldering wires to the back side of the pins on the bonnet but would that cause any issues? They appear to be unused: https://pinout.xyz/pinout/aiy_vision_bonnet

There's also the possibility of creating another UART interface using the expansion GPIO pins, but that seems really tricky: https://raspberrypi.stackexchange.com/questions/24019/can-the-gpios-pins-be-used-as-another-rx-and-tx/24039

Hopefully the maintainers can figure out a solution or the product people can provide access in future versions of the hardware. Thanks!

**Comment by manoj7410** [comment]
Is there a specific requirement of soldering the wires on the back side of Bonnet ? You can solder on the back side of the PI too right ?

**Comment by dmitriykovalev** [comment]
That's correct, the only current way to use 'unused' GPIOs is to solder on either Pi or Bonnet side.
