### ISSUE TITLE
password not working 

### ISSUE THREAD

**Issue by barkerd2** [google/aiyprojects-raspbian#673]
default password 'raspberry' doesnt work.

ssh pi@192.168.11.xx
Password:
Password:
Password:
pi@192.168.11.xx's password: 
Permission denied, please try again.
pi@192.168.11.xx's password: 
Permission denied, please try again.
pi@192.168.11.xx's password: 
Received disconnect from 192.168.11.xx port 22:2: Too many authentication failures
Authentication failed.

**Comment by manoj7410** [comment]
Is this issue still reproducible ? 
The default password for user 'pi' is 'raspberry' only.

**Comment by dmitriykovalev** [comment]
We are not changing default login/password for Raspberry Pi OS.
