### ISSUE TITLE
-bash: voice/assistant_grpc_demo.py: No such file or directory ???

### ISSUE THREAD

**Issue by Steve111888** [google/aiyprojects-raspbian#675]
Hello good people, having a little trouble getting  google pi voice project to run, any sugestions much appreciated :)
pi@raspberrypi:~ $ nano assistant.json
pi@raspberrypi:~ $ ls
AIY-projects-python   assistant.json  Documents  MagPi   Music     Public     Videos
AIY-voice-kit-python  Desktop         Downloads  models  Pictures  Templates
pi@raspberrypi:~ $ cd ~/AIY-projects-python
pi@raspberrypi:~/AIY-projects-python $ ls
CHANGES.md   CONTRIBUTING.md  HACKING.md  Makefile     README.md   scripts   src
checkpoints  docs             LICENSE     MANIFEST.in  schematics  setup.py  stdeb.cfg
pi@raspberrypi:~/AIY-projects-python $ voice/assistant_grpc_demo.py
-bash: voice/assistant_grpc_demo.py: No such file or directory

**Comment by manoj7410** [comment]
Run the command : "cd ~/AIY-projects-python/src/examples/voice"
Then run "./assistant_grpc_demo.py"
