### ISSUE TITLE
Captured image is dark due to backlight. Option to adjust camera settings 

### ISSUE THREAD

**Issue by techguyzz** [google/aiyprojects-raspbian#676]
Hello,

During the image captured with external light at back, which is too bright. Not able to get clear image of closer one.

Is it possible to adjust camera settings like shutter speed, brightness, ISO etc.

**Comment by dmitriykovalev** [comment]
You can adjust camera settings any way you like. For example, picamera python library can do [brightness](https://github.com/waveform80/picamera/blob/42d6eb02940f8cc2afd5ea4724fe49ba6e2837eb/picamera/camera.py#L2907) adjustments.
