### ISSUE TITLE
AIY Case

### ISSUE THREAD

**Issue by sunsharebox** [google/aiyprojects-raspbian#678]
Hello,
Can someone explain me where to get a new AIY cardboard Case ? a new one or only the opensource drawings so that I'll print them by myself.

best regards. julien
![product_voice@1x](https://user-images.githubusercontent.com/49123814/76416516-87f0b000-639b-11ea-9c75-ac5331588038.png)

**Comment by manoj7410** [comment]
Reach out to support-aiyprojects@google.com for your requirement.
