### ISSUE TITLE
Visual Response

### ISSUE THREAD

**Issue by marcusmauricio** [google/aiyprojects-raspbian#679]
Hello,
I was wondering how I could implement the "Visual Response" feature that is in the Google Assistant SDK. 

If you do not know what I am referring to, you can click the link below:
https://developers.google.com/assistant/sdk/guides/service/python/embed/next-steps

**Comment by marcusmauricio** [comment]
Bump

**Comment by manoj7410** [comment]
Have you tried to follow the instructions given at : https://github.com/googlesamples/assistant-sdk-python/tree/master/google-assistant-sdk/googlesamples/assistant/grpc#python-samples-for-the-google-assistant-grpc-api and https://github.com/googlesamples/assistant-sdk-python/blob/master/google-assistant-sdk/googlesamples/assistant/grpc/textinput.py#L149

**Comment by marcusmauricio** [comment]
I tried, but with the AIY, it automatically starts when the Rasp PI starts up. I would need more information in order to continue.

**Comment by manoj7410** [comment]
> I tried, but with the AIY, it automatically starts when the Rasp PI starts up. I would need more information in order to continue.

What does automatically start ?

**Comment by dmitriykovalev** [comment]
Please follow the instructions from https://github.com/google/aiyprojects-raspbian/issues/679#issuecomment-627128514.
