### ISSUE TITLE
Is it possible to make calls with the AIY voice kit on raspberry pi

### ISSUE THREAD

**Issue by butteryak** [google/aiyprojects-raspbian#689]
I note it's possible to make calls with google home. I'm wondering if it's possible to set up with the AIY project voice kit.   anytime I try I get "sorry I can't make calls yet" as a response.  

curious if it's possible or perhaps other integrations need to happen.

**Comment by manoj7410** [comment]
@butteryak The AIY Voice Kit doesn't have the full functionality of devices like Google Home - it's limited to the actions supported by the Google Assistant SDK. You can read more about those in the release notes.

https://developers.google.com/assistant/sdk/release-notes
