### ISSUE TITLE
ModuleNotFoundError: No module name 'aiy'

### ISSUE THREAD

**Issue by aanthony11** [google/aiyprojects-raspbian#694]
I have a Raspberry Pi 4, and am trying to implement Google Assistant into my project. I am able to run the google assistant when running a googlesamples-assistant-pushtotalk test, but when trying to run the assistant_grpc_demo.py file I run into the "No module named 'aiy' error. I am running the python file in a venv but am still getting the same error. 

![errors](https://user-images.githubusercontent.com/57596316/84854257-2d688f00-b02f-11ea-97bf-708b20952af0.png)

**Comment by manoj7410** [comment]
Did you try to run it without VENV as well ? Does that work ?

**Comment by aanthony11** [comment]
No running it without VENV doesn't work either

**Comment by dmitriykovalev** [comment]
You need to have `aiy` package in `PYTHONPATH` (that's true by default outside of venv). One way to run the example:

```bash
PYTHONPATH=~/AIY-voice-kit-python/src python3 assistant_grpc_demo.py
```
