### ISSUE TITLE
Can it use a USB microphone and 3.5mm audio to speak?

### ISSUE THREAD

**Issue by superbool** [google/aiyprojects-raspbian#7]
Can it  work without  Voice HAT device? For example use a USB microphone and 3.5mm audio to speak?  And why not ?

**Comment by drigz** [comment]
Yes, it can, as long as you have ALSA configured correctly. [Here's a post about configuring ALSA for a USB microphone with the built-in audio output](https://raspberrypi.stackexchange.com/a/54404).

You can test your configuration with the following commands:

```
# say "Testing, 1 2 3" while this command is recording
python3 src/audio.py dump test.wav -d 3
python3 src/audio.py play test.wav
```

This will record for three seconds, then play what it heard. You should hear your voice back (although it might be very quiet, depending on your microphone/speaker volume settings).
