### ISSUE TITLE
continue to get arecord: device_list:272: no soundcards found...

### ISSUE THREAD

**Issue by bravozulu1979** [google/aiyprojects-raspbian#705]
used a fresh image of Google AIY + raspberry buster from HACKING.md. However, after sudo apt-get upgrade, continue to get : 

arecord: device_list:272: no soundcards found...

I have a feeling something wrong with compatibility with the Kernel version raspberrypi 5.4.51-v7+ , which is what I have

**Comment by manoj7410** [comment]
This is a known issue and a bug has been filed with the development team for this.

**Comment by bravozulu1979** [comment]
@manoj7410 .. thank you. Do you have the bug details? It's disappointing that Google is selling the AIY kit that doesn't perform it's basic sound function after updates?

**Comment by thechamp21** [comment]
I emailed their support team and they said that there's no defined ETA for a fix which is disappointing. Seems like this has been an issue since May

**Comment by nmilenko** [comment]
@thechamp21 interesting - I was told that a fix would _probably_ be released by the end of this month. Hopefully this is the case!

**Comment by thechamp21** [comment]
@nmilenko I hope that is the case! Eager to get this thing built!

**Comment by thechamp21** [comment]
@manoj7410 - do you happen to know when the development team will be able to address this?

**Comment by viraniac** [comment]
@thechamp21 @bravozulu1979 I had the same issue and was able to create a fix for the same. 

To fix it, uninstall your aiy-voicebonnet-soundcard-dkms package and install the new package from [here](https://github.com/google/aiyprojects-raspbian/issues/697#issuecomment-703084054)

**Comment by manoj7410** [comment]
@thechamp21 Since Google tries to keep one build for all the variants of AIY kits (Voice, Vision). The release will only happen once the build has been tested for all the platforms. I don't have any timeline available as of now.

**Comment by viraniac** [comment]
@manoj7410 Google dooesn't need to release a new image to fix the issue, do they? All they need to do is update the aiy-voicebonnet-soundcard-dkms package in their debian repository so that people can safely run apt-get upgrade on their pi. 

That doesn't need the whole image to be built and tested for all the boards, does it? After all, the driver will only load when the voicebonnet is attached to pi and people cannot really attach multiple aiy boards together to the pi, can they?

**Comment by dmitriykovalev** [comment]
We have updated `aiy-voicebonnet-soundcard-dkms` packaged and also released new [SD card image](https://github.com/google/aiyprojects-raspbian/releases/tag/v20201120), please try them.
