### ISSUE TITLE
Hacking.md file implies aiy-voicebonnet-soundcard-dkms  is required for voice hat which is not right

### ISSUE THREAD

**Issue by viraniac** [google/aiyprojects-raspbian#707]
The Hacking.md file states:

> Install the bonnet/HAT drivers:
>
>```sudo apt-get install -y aiy-voicebonnet-soundcard-dkms```

This kind of implies that the above mentioned driver package is actually required for the voice hat to function. This is not really true as the voice hat is actually using `snd_soc_rpi_simple_soundcard` and `snd_soc_googlevoicehat_codec` kernel modules which is already provided by the raspberrypi linux kernel.

All the voice hat user has to do is add `dtoverlay=googlevoicehat-soundcard` in `/boot/config.txt` to get the device tree overlay to load which then pulls up the already available kernel modules from the raspberry pi kernel.

**Comment by dmitriykovalev** [comment]
Thank you! [HACKING.md](https://github.com/google/aiyprojects-raspbian/blob/aiyprojects/HACKING.md) is updated now.
