### ISSUE TITLE
Trying to locate the file mobilenet_ssd_256res_0.125_person_cat_dog_anchors.txt

### ISSUE THREAD

**Issue by juntao** [google/aiyprojects-raspbian#714]
I am trying to find the `mobilenet_ssd_256res_0.125_person_cat_dog_anchors.txt` file referenced in line #28 in `object_detection.py`

https://github.com/google/aiyprojects-raspbian/blob/aiyprojects/src/aiy/vision/models/object_detection.py

I tried to search this repository but could not find it. Any help would be greatly appreciated!

**Comment by dmitriykovalev** [comment]
This file should be in `/opt/aiy/models` on the [SD card image](https://github.com/google/aiyprojects-raspbian/releases).

**Comment by juntao** [comment]
Thanks!
