### ISSUE TITLE
[need help] Where is the list of possible classes for image classification

### ISSUE THREAD

**Issue by yangliu2** [google/aiyprojects-raspbian#730]
`video_capture.py` said there is a file `image_classification_classes.py` that indicate the possible classes it will recognize. I did not find the file and not sure where is list of classes. 
Could anybody point me to the right direction?
Appreciate it!

**Comment by scottamain** [comment]
On the Pi, try looking at /opt/aiy/models/mobilenet_v1_160res_0.5_imagenet_labels.txt

(as per https://github.com/google/aiyprojects-raspbian/blob/aiyprojects/src/aiy/vision/models/image_classification.py#L38)

**Comment by yangliu2** [comment]
Good find. Laziness came over me I guess.
