### ISSUE TITLE
audio not working aiy voice kit with raspberry pi 3 b+

### ISSUE THREAD

**Issue by mexanarock** [google/aiyprojects-raspbian#735]
so recently i was gifted a aiy voice kit and i followed the instructions in the manual,but when i run the check_audio.py no audio plays,i tried reconnecting the speaker and it still dosnt work(i speaker works,i tried using a aux cable to power it and worked,so the speaker isnt faulty)

**Comment by manoj7410** [comment]
@mexanarock Do you see any error while executing 'check_audio.py' ?
Di you try to connect an earphone into 3.5mm audio jack and see if the audio plays there ?

**Comment by mexanarock** [comment]
i used a 2018 image and it works now,vol was low but asking google to set vol to max fixed that
