### ISSUE TITLE
Ok Google - SDK upgrade - Here is the latest news - but there isn't any news

### ISSUE THREAD

**Issue by sheridat** [google/aiyprojects-raspbian#74]
I've updated to a Pi 3 this morning and I've set the trigger to ok-google.  It works exceedingly well.
BUT
Normally I say good morning and it responds by saying hello, tells me the time and weather and what my commute is to get home and tells me to have a nice day

Now I have upgraded to the new version of the google assistant SDK i get the same response except after telling me about my commute and saying have a nice day - it says here is the latest news and then stops - it doesn't tell me any news and the journal shows it is waiting to be triggered.

That seems like a fault/bug to me. 

Switching back to button triggering gets rid of the spurious "here is the latest news" - looks like two different versions of the google assistant gets used depending upon trigger type.

As we say in Britain - there is a rabbit off somewhere.

**Comment by drigz** [comment]
Thanks very much for the report, @sheridat! I've reported this on to the Assistant SDK team - I'll update here when I know more.

**Comment by mangelov95** [comment]
I have the same problem for google-assistant-sdk 0.3.0.

**Comment by drigz** [comment]
The Assistant SDK team has fixed this, so the buggy "Here is the latest news" will be gone in the next release of [google-assistant-library](https://pypi.python.org/pypi/google-assistant-library) (presumably 0.0.3?)

Thanks again for the report!
