### ISSUE TITLE
passing parameters

### ISSUE THREAD

**Issue by Gh0stWires** [google/aiyprojects-raspbian#76]
Is there a way to pass the voice-recognizer parameters? Basically I want bypass the mic and feed  it text instead of speech.  This might sound vague but I can be more specific if need. I just want the recognizer to take text as well as speech.

**Comment by drigz** [comment]
There's no built-in support for this, but you can modify the code to call `[actor.handle](https://github.com/google/aiyprojects-raspbian/blob/487522740728d3a646c1487faf40efca58473da1/src/main.py#L390)` with your own text.

Does that help?

**Comment by Gh0stWires** [comment]
yeah it does thanks for the suggestion

**Comment by drigz** [comment]
Glad to hear it!
