### ISSUE TITLE
Google Home app

### ISSUE THREAD

**Issue by pixelflowxyz** [google/aiyprojects-raspbian#77]
Is the AIY meant to work with the Google Home app?
Some responses end in 'Check your Google Home app for more.' or the like.

**Comment by eduncan911** [comment]
See #6

**Comment by pixelflowxyz** [comment]
Ahh - thanks!
(Also, your blog post on updating the AIY was very helpful, kudos to you)

**Comment by drigz** [comment]
Yep, closing as duplicate. Thanks @eduncan911 for responding so quickly!
