### ISSUE TITLE
Instructions to run on a headless raspbian

### ISSUE THREAD

**Issue by therazor** [google/aiyprojects-raspbian#8]
It'd be great to have a walkthrough to get this working on a base headless raspbian image.

Even with a walkthrough, right now it requires several tweaks to work on a minimal raspbian.
This is an incomplete list of the issues I've found:
- `install.sh` is missing even tho it's [referenced in `check_audio.py`](https://github.com/google/aiyprojects-raspbian/blob/master/checkpoints/check_audio.py#L164)
- sound test cannot find the [file to play](https://github.com/google/aiyprojects-raspbian/blob/master/checkpoints/check_audio.py#L39) (because it doesn't exist)
- `install.sh` doesn't install `dkms`, even tho it's missing
- `check_audio.py` cannot play an existing file, even tho `aplay filepath.wav` can play back on the speaker bundled

**Comment by drigz** [comment]
Thanks very much for your feedback!

We've updated the instructions in [HACKING.md](https://github.com/google/aiyprojects-raspbian/blob/master/HACKING.md) now that a kernel has been released with the Voice HAT driver. This should fix most of your issues (although check_audio.py still refers to the old script #19).

I'm closing this issue, but please reopen or file a new issue if you find problems in the new instructions.
