### ISSUE TITLE
No module 'google.assistant.embedded' found when updating to google-assistant-sdk 0.3.2

### ISSUE THREAD

**Issue by mangelov95** [google/aiyprojects-raspbian#82]
Hello, I have an issue starting the voice recognizer when using the 'OK Google' trigger after updating the google-assistant-sdk to version 0.3.2 (in the python environment). I get:

 `ImportError: No module named 'google.assistant.embedded'`

Do you have any idea how this might be fixed or I have to downgrade google-assistant-sdk back to 0.1.0?

**Comment by drigz** [comment]
Can you try this and see if it resolves the issue?

`env/bin/pip install -r requirements.txt`

**Comment by mangelov95** [comment]
Yes, that worked! I was missing one of the libraries in the requirements file (previously I installed the others manually). Thanks a lot for the help!
