### ISSUE TITLE
Google Assistant SDK / GRPC - click module not installed.

### ISSUE THREAD

**Issue by sheridat** [google/aiyprojects-raspbian#84]
Hi, I've been updating my AIY using the now famous instructions at http://eduncan911.com/stem/embedded/aiy-google-assistant-upgrades-may-2017.html

Everything is going swimmingly well - loving using OK Google as the activation method. 

However in /home/pi/assistant-sdk-python/google-assistant-sdk/googlesamples/assistant/grpc there is a file "pushtotalk.py" if I do python pushtotalk.py I get a failure 

     Traceback (most recent call last):
      File "pushtotalk.py", line 21, in <module>
      import click
      ImportError: No module named 'click'

There is a requirements.txt file in that folder and sure enough click==6.7 is a requirement

Shouldn't this module (and any others needed by the assistant SDK) be in the /home/pi/voice-recognizer-raspi/scripts **install-deps.sh** (that me and hopefully everyone else is running when there are updates).

I started installing the modules in the start dev terminal window and then typing 
python3 /home/pi/assistant-sdk-python/google-assistant-sdk/googlesamples/assistant/grpc/pushtotalk.py

but I decided to chicken out when after installing a few modules I got ERROR:root:Error loading credentials: [Errno 2] No such file or directory: '/home/pi/.config/google-oauthlib-tool/credentials.json'
ERROR:root:Run google-oauthlib-tool to initialize new OAuth 2.0 credentials.

**Comment by drigz** [comment]
> Shouldn't this module (and any others needed by the assistant SDK) be in the /home/pi/voice-recognizer-raspi/scripts install-deps.sh

No - we only install the modules needed for the voice recognizer. This is intentional - otherwise, there's a risk of conflicting dependencies with the Assistant SDK.

If you want to run the samples from the Assistant SDK, you'll have to install their dependencies separately - I'd suggest following the [Assistant SDK instructions](https://pypi.python.org/pypi/google-assistant-sdk).
