### ISSUE TITLE
spurious triggering - hotword

### ISSUE THREAD

**Issue by sheridat** [google/aiyprojects-raspbian#89]
The AIY box when setup for hotword triggering is reacting to spurious phrases/sounds/background noise.

I now have my AIY setup to trigger using hotword.  Like most people I don't spend my day watching it's pulsing LED but I have been assuming that it is only triggered at my behest.

However today I switched on the trigger sound facility - using a wav file already on the pi. So my config looks like this

 trigger = ok-google
 trigger-sound = /usr/share/scratch/Media/Sounds/Electronic/Fairydust.wav

A couple of times today I have just been sitting watching tennis on the TV and the AIY has suddenly triggered and the wav file has been played.  An example from the journal - it was just sitting there and I didn't trigger it by using either Ok Google or Hey Google 

Jun 26 **19:59:24** raspberrypi python3[522]: [2017-06-26 19:59:24,082] INFO:main:ready...
Jun 26 20:14:38 raspberrypi python3[522]: [2017-06-26 20:14:38,053] INFO:root:ON_CONVERSATION_TURN_STARTED
Jun 26 20:14:38 raspberrypi python3[522]: [2017-06-26 20:14:38,054] INFO:main:listening...
Jun 26 20:14:48 raspberrypi python3[522]: [2017-06-26 20:14:48,069] INFO:root:ON_END_OF_UTTERANCE
Jun 26 20:14:48 raspberrypi python3[522]: [2017-06-26 20:14:48,071] INFO:main:thinking...
Jun 26 20:14:48 raspberrypi python3[522]: [2017-06-26 20:14:48,333] INFO:root:ON_RECOGNIZING_SPEECH_FINISHED:
Jun 26 20:14:48 raspberrypi python3[522]: **{'text': "that's pretty old and hasn't for love and it difficult for Everything Jewish results"}**
Jun 26 20:14:49 raspberrypi python3[522]: [2017-06-26 20:14:49,765] INFO:root:ON_CONVERSATION_TURN_TIMEOUT
Jun 26 20:14:49 raspberrypi python3[522]: [2017-06-26 20:14:49,766] INFO:root:ON_CONVERSATION_TURN_FINISHED:
Jun 26 20:14:49 raspberrypi python3[522]: {'with_follow_on_turn': False}
Jun 26 20:14:49 raspberrypi python3[522]: [2017-06-26 20:14:49,768] INFO:main:ready...

The context of the tennis match certainly didn't involve anything that could be construed as either Ok Google or Hey Google. I can understand that the phrase **that's pretty old and hasn't for love and it difficult for Everything Jewish results** does contain a couple of words that are tennis related.

A while later it triggered again - whilst I was watching a TV program that was playing some music. Here is the journal
Jun 26 21:23:44 raspberrypi python3[522]: [2017-06-26 21:23:44,280] INFO:main:ready...
Jun 26 22:10:17 raspberrypi python3[522]: [2017-06-26 22:10:17,197] INFO:root:ON_CONVERSATION_TURN_STARTED
Jun 26 22:10:17 raspberrypi python3[522]: [2017-06-26 22:10:17,198] INFO:main:listening...
Jun 26 22:10:21 raspberrypi python3[522]: [2017-06-26 22:10:21,468] INFO:root:ON_END_OF_UTTERANCE
Jun 26 22:10:21 raspberrypi python3[522]: [2017-06-26 22:10:21,470] INFO:main:thinking...
Jun 26 22:10:21 raspberrypi python3[522]: [2017-06-26 22:10:21,603] INFO:root:ON_RECOGNIZING_SPEECH_FINISHED:
Jun 26 22:10:21 raspberrypi python3[522]: **{'text': 'music'}**
Jun 26 22:10:22 raspberrypi python3[522]: [2017-06-26 22:10:22,497] INFO:root:ON_CONVERSATION_TURN_TIMEOUT
Jun 26 22:10:22 raspberrypi python3[522]: [2017-06-26 22:10:22,498] INFO:root:ON_CONVERSATION_TURN_FINISHED:
Jun 26 22:10:22 raspberrypi python3[522]: {'with_follow_on_turn': False}
Jun 26 22:10:22 raspberrypi python3[522]: [2017-06-26 22:10:22,505] INFO:main:ready...

Interesting that It interpreted the "noise" as "music"

If I need to raise this issue in the assistant sdk repository please advise so.

**Comment by drigz** [comment]
There's nothing we can do about this, I'm afraid. False triggering is pretty much inevitable with current hotwording implementations. Some others (but not the Google Assistant Library) let you adjust the sensitivity, but then you'll miss more real triggers.

**Comment by sheridat** [comment]
And here was I thinking I had found "the ghost in the machine"
